# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
- repo: local
  hooks:
    - id: formatBib
      name: formatBib
      description: Format changed bib files using doot
      language: system
      entry: mamba run "-n" "doot-dev" doot "bib::precommit.format"
      verbose: true
      require_serial: true
      stages: [pre-commit]
    # - id: summarise
    #   name: summarise
    #   description: Re-Generate summaries of any changed files
    #   language: system
    #   entry: mamba run "-n" "doot-dev" doot "summary::precommit.top"
    #   verbose: true
    #   require_serial: true
    #   stages: [pre-commit]
    - id: updateBookmarks
      name: Update Bookmarks
      description: Grab Bookmarks from Firefox
      language: system
      entry: mamba run "-n" "doot-dev" doot "bookmark::update"
      verbose: true
      require_serial: true
      stages: [pre-commit]
    # - id: updateTags
    #   name: Update Tags
    #   description: Extract tags from changed files
    #   language: system
    #   entry: mamba run "-n" "doot-dev" doot "tags::precommit.extract"
    #   verbose: true
    #   require_serial: true
    #   stages: [pre-commit]
    - id: validateMsg
      name: validage commit message
      description: checks the commit msg has a tag at the start
      language: system
      entry: mamba run "-n" "doot-dev" doot "precommit::validate"
      stages: [commit-msg]
    - id: cleanupPdfs
      name: Clean up PDFs
      description: Deletes refiled_* files from the todo dir
      language: system
      entry: mamba run "-n" "doot-dev" doot "bib::cleanup" "export::all"
      verbose: true
      require_serial: true
      stages: [post-commit]
