# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.2.0
   hooks:
   -   id: trailing-whitespace
   -   id: check-yaml
   -   id: end-of-file-fixer
       exclude: ".+?.bookmarks$"
- repo: local
  hooks:
    - id: dootPre
      name: dootPre
      description: Format changed bib files using doot
      language: system
      entry: mamba run "-n" "default" doot "precommit::pre"
      verbose: true
      require_serial: true
      stages: [pre-commit]
    - id: validateMsg
      name: validate
      description: checks the commit msg has a tag at the start
      language: system
      entry: mamba run "-n" "default" doot "precommit::validate"
      stages: [commit-msg]
    - id: dootPost
      name: dootPost
      description: Deletes refiled_* files from the todo dir
      language: system
      entry: mamba run "-n" "default" doot "precommit::post"
      verbose: true
      require_serial: true
      stages: [post-commit]
