# -*- mode:conf-toml; -*-
[settings.general]
notify                   = { say-on-exit = false }
loaders                  = { commands="default", task="default", parser="default"}
location_check           = { make_missing = true, print_levels={action="WARN", execute="WARN" } }

[settings.tasks]
sources = [".tasks"] # Files or directories where task specs can be loaded from, expanded according to [[locations]] keys
code    = []         # Directories where task specific code can be imported from, expanded according to [[locations]] keys
sleep   = { task=0.2, subtask=1, batch=1 }

[logging]
stream  = { level="WARNING", format="{levelname:<8} : {message}", filters=["doot"], target="stdout" }
file    = { level="DEBUG",   format="{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filters=["doot"], target="file" }
printer = { level="INFO",    format="{message}", colour=true, target="stdout", filter=["doot._printer.checkloc"] }

[logging.subprinters]
#     action_exec, action_group, artifact, cmd, fail, header, help, queue,
#     report, skip, sleep, success, task, task_header, task_loop, task_state,
#     track, setup, shutdown
setup        = {level="WARNING", format="---- Setup: {message}", propagate=false}
shutdown     = {level="WARNING", format="---- Shutdown: {message}", propagate=false}
success      = {}
fail         = {target="stdout", format="---- !!!! {message}", propagate=false}
track        = {format="(Tracking) {message}"}
task_header  = {}
task         = {}
task_state   = {}
action_group = {}
action_exec  = {}
queue        = {}
report       = {}

[logging.extra]

[plugins]
# Allows for defining shorthands
command        = { other-run = "doot.cmds.run_cmd:RunCmd", tasks = "doot.cmds.list_cmd:ListCmd" }
report-line    = {}
reporter       = {}
action         = {}
task           = {}

[commands]
run = { tracker = "default", runner = "default", reporter= "default", report-line = []}

[[locations]]
temp          = ".temp"
logs          = "{temp}/logs"
export        = "{temp}/export"
bib           = "main"
bookmarks     = {file="bookmarks/total.bookmarks"}
substitutions = "tags/substitutions"
