# -*- mode:conf-toml; -*-

[startup]
doot_version     = "0.13"
loaders          = { commands="default", task="default", parser="default"}
location_check   = { make_missing=true }
max_steps        = 100_000
sources          = {tasks=[".tasks", "/media/john/data/github/_templates/doot/android_tasks"], code=[]}
sleep            = { task=0.2, subtask=1, batch=1 }

[shutdown]
notify = { speak=false }

[settings.commands]
run = { tracker = "default", runner = "default", reporter= "default", report-line = []}

[plugins]
# Allows for defining shorthands
command        = { tasks = "doot.cmds.list_cmd:ListCmd" }

[logging]
stream  = { level="WARNING", filter=[],                 target="stdout", format="{levelname:<8} : {message}"  }
file    = { level="DEBUG",   filter=["tomlguard"],      target="rotate", format="{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filename_fmt="doot.log" }
printer = { level="NOTSET", colour=true,                target=["stdout", "rotate"], format="{message}", filename_fmt="doot_printed.log" }

[logging.subprinters]
default       = {level="WARNING"}
shutdown      = {level="WARNING",    format="Shutdown: {message}", target="stdout"}
cmd           = {level="INFO"}
task          = {level="INFO" }
header        = {level="INFO" }
task_header   = {level="INFO"}

[logging.extra]

[[locations]]
temp          = ".temp"
logs          = "{temp}/logs"
export        = "{temp}/export"
bib           = "main"
bookmarks     = "file::bookmarks/total.bookmarks"
substitutions = "tags/substitutions"
lib-root      = "/media/john/data/library/pdfs/"
