## tox.toml -*- mode: toml-mode -*-
# https://tox.wiki/en/4.28.4/user_guide.html
# https://github.com/tox-dev/tox-uv
# String substitution: "{[<table>]<key>}"
requires                   = ["tox>=4", "tox-uv>=1"]
env_list                   = ["docs"]
work_dir                   = ".temp/tox/work"
temp_dir                   = ".temp/tox/temp"
skip_missing_interpreters  = false

[env_run_base]
description          = "base_env"
runner               = "uv-venv-lock-runner"
allowlist_externals  = ["echo", "rsync"]
set_env              = {}

[env.docs]
description        = "build documentation"
uv_sync_locked     = false
uv_sync_flags      = ["--no-editable", "--no-sources"]
skip_install       = true
set_env            = [
    {replace="ref", of=["env_run_base", "set_env"]},
]
commands = [
  ["uv", "run", "--script", ".tasks/cargo-alldocs", { replace="posargs", default=[], extend=true }]
]

[env.bookmarks]
description = "update bookmarks"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/bookmarks.py", { replace="posargs", default=[], extend=true }]
]

[env.format]
description  = "format bibtex files"
set_env      = [
  {TARGET = {replace="env", name="TARGET",  default="./main"}},
]
commands = [
  ["uv", "run", "--script", ".tasks/scripts/bib_format.py", "{env:TARGET}", {replace="posargs", default=[], extend=true}],
]

[env.apply]
description = "apply entry metadata to files"
set_env = [
  {TARGET = {replace="env", name="TARGET",  default="./main"}},
]
commands = [
  ["uv", "run", "--script", ".tasks/scripts/apply_metadata.py", "{env:TARGET}", {replace="posargs", default=[], extend=true}],
]

[env.online]
description = "download online urls"
set_env = [
  {TARGET = {replace="env", name="TARGET", default="in_progress/online.bib"}},
]
commands = [
  ["uv", "run", "--script", ".tasks/scripts/bib_online.py", "{env:TARGET}", { replace="posargs", default=[], extend=true }],
]

[env.stub]
description = "collect and stub pdfs in dropbox and downloads"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/make_stubs.py", {replace="posargs", default=[], extend=true}],
]

[env.clean]
description = "Clean away refiled pdfs"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/clean_todos.py", { replace="posargs", default=[], extend=true }],
]

[env.tags]
description = "Update the lists of tags"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/update_tags.py", "{env:TARGET}", {replace="posargs", default=[], extend=true}],
]

[env.chunk]
description = "chunk files into smaller files"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/bib_chunk.py", {replace="posargs", default=[], extend=true}],
]

[env.backup] 
description = "Backup pdfs"
set_env = [
  {SOURCE = {replace="env", name="SOURCE", default="/media/john/data/library/pdfs"}},
  {TARGET = {replace="env", name="TARGET", default="/media/john/solid_ext4/library"}},  
]
commands = [
  ["rsync", "--archive", "--progress", "{env:SOURCE}", "{env:TARGET}"],
]

[env.report]
description = "generate an rst report on the repo"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/bib_report.py", {replace="posargs", default=[], extend=true}],
]

## 
# To Finish: --------------------------------------------------

[env.restruct]
description = "restructure library files"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/lib_restructure.py", {replace="posargs", default=[], extend=true}],
]

[env.android] # TODO
description = "Pushes pdflib to android"

[env.latex] # TODO
description = "Compiles all bibtex into a pdf file"
