## tox.toml -*- mode: toml-mode -*-
# https://tox.wiki/en/4.28.4/user_guide.html
# https://github.com/tox-dev/tox-uv
# String substitution: "{[<table>]<key>}"
requires                   = ["tox>=4", "tox-uv>=1"]
env_list                   = ["docs"]
work_dir                   = ".temp/tox/work"
temp_dir                   = ".temp/tox/temp"
skip_missing_interpreters  = false

[env_run_base]
description          = "base_env"
runner               = "uv-venv-lock-runner"
allowlist_externals  = ["echo"]
set_env              = {}

[env.docs]
description        = "build documentation"
uv_sync_locked     = false
uv_sync_flags      = ["--no-editable", "--no-sources"]
skip_install       = true
set_env            = [
    {replace="ref", of=["env_run_base", "set_env"]},
    {BUILDER  = {replace="env", name="BUILDER",  default="bibhtml"}},  
    {CONFDIR  = {replace="env", name="CONFDIR",  default="./"}},
    {OUTDIR   = {replace="env", name="OUTDIR",   default="./.temp/site/"}},
    {DOCTREE  = {replace="env", name="DOCTREE",  default="./.temp/docs/.doctrees/"}},
]
commands      = [
    ["echo", "Building Documentation to:", "{env:OUTDIR}"],
    ["echo", "Doctrees to:", "{env:DOCTREE}"],
    ["echo", "Config in:", "{env:CONFDIR}"],
    ["uv", "run", "--frozen", "sphinx-build",
    # "-q",
    # "--fresh-env",
    "--conf-dir", "{env:CONFDIR}",
    "--doctree-dir", "{env:DOCTREE}",
    "--warning-file", "./.temp/logs/sphinx.log",
    "--builder", "{env:BUILDER}",
     "./{env:PKGNAME}",
     "{env:OUTDIR}",
    {replace="posargs", default=[], extend=true}
    ]
]


[env.bookmarks]
description = "update bookmarks"
commands = [
  ["uv", "run", "--script", ".tasks/scripts/bookmarks.py"]
]

[env.format]
description = "format bibtex files"
set_env = [
  {TARGET = {replace="env", name="TARGET",  default="./main"}},
]
commands = [
  ["uv", "run", "--script", ".tasks/scripts/bib_format.py", "{env:TARGET}", {replace="posargs", default=[], extend=true}],
]

[env.backup]
description = "Backup pdfs"
set_env = [
  {TARGET = {replace="env", name="TARGET",  default="/media/john/solid_ext4/library/pdfs"}},  
]
commands = [
  ["rsync", "--archive", "--progress", "/media/john/data/library/pdfs", "{env:TARGET}"],
]

[env.apply]
description = "apply entry metadata to files"
set_env = [
  {TARGET = {replace="env", name="TARGET",  default="./main"}},
]
commands = [
  ["uv", "run", "--script", ".tasks/scripts/apply_metadata.py", "{env:TARGET}"],
]
