## _lib_files.toml -*- mode: toml -*-
# Summary:
#
# Tags:
#
doot-version = "1.1"

[[locations]]
orphans   = "{temp}/orphans"
structlib = "{data_drive}/library/pdfs_structured"

[[tasks.lib-files]]
disabled = true
name    = "+.refile"
doc     = [
    "refile each file in each bibtex entry",
    "retargets files into groups based on century"
]
cli              = [{ name="-fpath", type="str", default="", desc=""}]
must_inject      = ["fpath"]
roots            = ["{bib!p}"]
depends_on       = [
    # Check the fpath is a bibtex and in the library
    { do="ext?",      args=["{fpath!p}"], exts=[".bib"] },
    { do="relative?", args=["{fpath!p}"], bases_="roots"},
    { do="exists?", args=["{fpath!p}"],   fail=true},
    { task="bibtex::format", inject={from_spec=["fpath"]} },
]
setup            = [
    # build the parse and export stacks, and the db
    { do="path.elements", from_="fpath" },
    { do="dootle.bibtex:InitDb",      update_="bib_db"},
    { do="taskcode.io_stack:build_new_stack", update_="refile_stack", refile=true},
    { do="dootle.bibtex:BuildReader", update_="bib_reader", stack_="refile_stack"},
    { do="dootle.bibtex:BuildWriter", update_="bib_writer", stack_="refile_stack"},
]
actions          = [
    { do="log", msg="Refiling Entries in: {fpath}", level="WARN"},
    # Read the file
    { do="dootle.bibtex:DoRead", from_="fpath", update_="bib_db", reader_="bib_reader"},
    # TODO transform entries
    { do="dootle.bibtex:ToStr",  from_="bib_db",    update_="bib_text", writer_="bib_writer", to="{fpath!p}" },
    # Queue Entry Subtasks:
    { do="taskcode.metadata:GenBibEntryTask", template="lib-files::_.single.entry", from_="bib_db", update_="entry_tasks"},
    { do="job.queue", from_="entry_tasks" },
]

[[tasks.lib-files]]
name        = "_.single.entry"
doc         = ["Targets: pre20th, 20th_a, 20th_b, 21st_a, 21st_b"]
must_inject = ["entry"]
roots       = ["{pdf_source!p}"]
actions     = [
    {do="taskcode.bibtex:log_entry_name"},
    # --
    # Get files
    # calculate update
    # build dirs
    # hardlink
]

[[tasks.lib-files]]
disabled = true 
name     = "orphans"
