## _precommit.toml -*- mode: toml-mode -*-
# Summary:
#
# Tags:
#
doot-version = "1.1"

[[tasks.precommit]]
disabled = true
name       = "+.post"
cli        = [{name="-files", type="list", default=[]}, {name="-choose", type="int", default=1},]
roots      = ["{bib!p}"]
exts       = [".bib"]
sub_target = "bibtex::validate"
actions    = [
   {do="log", msg="Starting Post Commit Process : {files}"},
   # if No cache, so just process the head changes:
   {do="dootle.utils.:GetChangedFilesByCommit", update_="changed"},
   {do="log", msg="Available changed files: {changed}"},
   {do="job.limit", count_="choose", from_="changed"},
   # Queue metadata update
   {do="job.expand", from_="changed", inject={insert=["fpath"]}, template_="sub_target", update_="bib_files", prefix="git.cached"},
   {do="job.queue", from_=["bib_files"]},
]
cleanup = [
   "cleanup::+.refiled",
   "bookmarks::update",
   # TODO cache head commit hash
   {do="log", msg="Finished Post Commit Process"},
   {do="shell!", args=["notify-send", "--expire-time=1000", "--transient", "Finished Commit Post Hook"]},
]
