#!/usr/bin/env bash
#  biblio -*- mode: Bash -*-

set -o nounset

current_script_path="${BASH_SOURCE[0]}"
BIBLIO_SRC=$(realpath "$(dirname "$current_script_path")")

source "$BIBLIO_SRC/lib-util.bash"

#  output --------------------------------------------------

function do_android_push () {
    header "TODO: biblio android"
    if help_flag "$@"; then
        echo "help"
        exit 0
    fi
    # setup adb and push biblio_lib
    exit 1
}

function print_help () {
    header "biblio scripts"

    echo "
    -h | --help
    backup
    bookmarks
    build
    chunk
    cleanup
    format
    metadata
    move
    online
    post
    report
    stub
"
}

function parse_biblio_args () {
    if [[ "${1:-}" = "biblio" ]]; then
        shift
    fi
    if [[ "$#" -eq 0 ]] || help_flag "$@"; then
        print_help
        exit 0
    fi

    local cmd="$1"
    shift

    case "$cmd" in
        build)
            do_build "$@"
            ;;
        bookmarks)
            do_bookmarks "$@"
            ;;
        post)
            do_media_post "$@"
            ;;
        format)
            do_format "$@"
            ;;
        metadata)
            do_metadata "$@"
            ;;
        online)
            do_online "$@"
            ;;
        stub)
            do_stub "$@"
            ;;
        cleanup)
            do_cleanup "$@"
            ;;
        chunk)
            do_chunk "$@"
            ;;
        backup)
            do_backup "$@"
            ;;
        report)
            do_report "$@"
            ;;
        move)
            do_move "$@"
            ;;
        *) # Positional
            echo "Unknown arg: $cmd"
            exit 1
            ;;
    esac
}

parse_biblio_args "$@"
