## bookmark.toml -*- mode: toml -*-
doot-version = "0.13"

[[locations]]
firefox       = "~/snap/firefox/common/.mozilla/firefox"

[[tasks.bookmark]]
name                 = "update"
doc                  = ["Merge firefox bookmarks into bibliography repo"]
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
cli                  = [{ name="files", prefix=1,  type="list", default=[]}]
db_name              = "places.sqlite"
log_file             = "{temp!p}/logs/bookmark_update.log"
depends-on           = [
   { do="dootle.utils:skip_if_recent", target="{bookmarks!p}"},
   "bookmark::_.firefox",
   "bookmark::_.archived"
]
setup = [
   { do="doot.actions.state:AddNow", format="%Y-%m-%d : %H:%M", update_="_date"},
]
actions              = [
   { do="post.get", head_firefox_bkmks="bookmark::_.firefox..-", head_archived_bkmks="bookmark::_.archived..-" },
   { do="dootle.bookmarks:Merge", from_=["head_archived_bkmks", "head_firefox_bkmks"], update_="total_bkmks" },
   { do="dootle.bookmarks:RemoveDuplicates", from_="total_bkmks" },
   # TODO Clean Tags
   { do="dootle.bookmarks:ToStr", from_="total_bkmks", update_="bkmks_str" },
   { do="append!", args=["* {_date}", "{bkmks_str}"], to="{log_file!p}" },
   { do="write!", from_="bkmks_str", to="{temp!p}/merged.bookmarks" },
   { do="write!", from_="bkmks_str", to="{bookmarks!p}" },
]                                                                                                        # <list[Any]>

[[tasks.bookmark]]
name                 = "_.firefox"
doc                  = ["Copy and extract firefox bookmarks"]
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
db_name              = "places.sqlite"
cleanup = [
   { do="delete!", args=["{temp!p}/{db_name}", "{temp!p}/{db_name}-shm", "{temp!p}/{db_name}-wal"], lax=true },
]
setup                = [
   { do="doot.actions.io:SimpleFind", from="{firefox!p}", pattern_="db_name", rec=true, update_="db_locs"},
]
actions              = [
   { do="copy", from_="db_locs", to="{temp!p}/" }, # copy the db from {firefox}/../{db_name} -> {temp}
   { do="dootle.bookmarks:Extract", from="{temp!p}/{db_name}", update_="firefox_bkmks" }, # extract
   { do="post.put", args=["{firefox_bkmks}"] },
]

[[tasks.bookmark]]
name                 = "_.archived"
doc                  = ["Read existing bookmarks ready to merge new firefox bookmarks"]
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
depends_on           = ["file:>{bookmarks}"]                   # <list[DootTaskArtifact]>
actions              = [
   { do="dootle.bookmarks:Load", from="{bookmarks!p}", update_="total_bkmks" },
   { do="post.put", args=["{total_bkmks}"] },
]
