## bookmark.toml -*- mode: conf-toml -*-

[[locations]]
firefox       = "~/snap/firefox/common/.mozilla/firefox"

[[tasks.bookmark]]
name                 = "update"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
cli                  = [{ name="files",   type="list", default=[], positional=true }]
doc                  = ["Merge firefox bookmarks into bibliography repo"]
db_name              = "places.sqlite"
depends-on           = ["bookmark::_firefox", "bookmark::_archived"]
actions              = [
                     { do="pred?", pred="taskcode.bkmk:recency_test" },
                     { do="post.get", head_firefox_bkmks="bookmark::_firefox.-", head_archived_bkmks="bookmark::_archived.-" },
                     { do="dootle.bookmarks.actions:BookmarksMerge", from_=["head_archived_bkmks", "head_firefox_bkmks"], update_="total_bkmks" },
                     { do="dootle.bookmarks.actions:BookmarksRemoveDuplicates", from_="total_bkmks" },
                     { do="dootle.bookmarks.actions:BookmarksToStr", from_="total_bkmks", update_="bkmks_str" },
                     { do="doot.actions.state:AddNow", format="%Y-%m-%d : %H:%M", update_="_date"},
                     { do="doot.actions.io:AppendAction", args=["* {_date}", "{bkmks_str}"], to="{temp}/append.test" },
                     { do="write!", from_="bkmks_str", to="{temp}/merged.bookmarks" },
                     { do="write!", from_="bkmks_str", to="{bookmarks}" },
]                                                                                                        # <list[Any]>

[[tasks.bookmark]]
name                 = "_firefox"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
doc                  = [] # <list[str]>
db_name              = "places.sqlite"
actions              = [
                     { do="doot.actions.io:SimpleFind", from="{firefox}", pattern_="db_name", rec=true, update_="db_locs"},
                     { do="delete!", args=["{temp}/{db_name}", "{temp}/{db_name}-shm", "{temp}/{db_name}-wal"], lax=true },
                     { do="copy", from_="db_locs", to="{temp}/" }, # copy the db from {firefox}/../{db_name} -> {temp}
                     { do="dootle.bookmarks.actions:BookmarksPonyExtraction", from="{temp}/{db_name}", update_="firefox_bkmks" }, # extract
                     { do="post.put", args=["{firefox_bkmks}"] },
                     { do="delete!", args=["{temp}/{db_name}", "{temp}/{db_name}-shm", "{temp}/{db_name}-wal"], lax=true },
]

[[tasks.bookmark]]
name                 = "_archived"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
doc                  = []                   # <list[str]>
actions              = [
                     { do="dootle.bookmarks.actions:BookmarksLoad", from="{bookmarks}", update_="total_bkmks" },
                     { do="post.put", args=["total_bkmks"] },
]
