## cleanup.toml -*- mode: toml-mode -*-
# Summary:
#
# Tags:
#
doot-version = "1.1"

[[tasks.cleanup]]
name        = "+.refiled"
doc         = ["Cleanup refiled pdfs and epubs"]
accept_fn   = "taskcode.stubber:select_refiled"
roots       = ["{todo_pdfs!p}", "{todo_pdfs!p}/stubbed/", "{todo_pdfs!p}/online"]
recursive   = false
actions     = [
            {do="log", msg="Queuing Cleanup of old files"},
            {do="job.walk",   update_="files", fn_="accept_fn"}, # walk,
            {do="job.expand", from_="files", update_="tasks", inject={insert=["fpath"]}, template_="sub_actions"},
            {do="job.queue",  from_="tasks"}, # queue
]
sub_actions = [
    {do="delete!", args=["{fpath!p}"]}
]
