## collectors.toml -*- mode: toml-mode -*-
# Summary:
#
# Tags:
#
doot-version = "1.1"

[[locations]]

[[global]]

[[tasks.collect]]
name    = "+.target"
doc     = ["Format a number of bibtex files"]
cli     = [
        {name="-count", type="int", default=2},
        {name="-target", type="str", default="bibtex::format"},
]
roots   = ["{bib}"]
files = ["main/1924.bib", "main/1320.bib"]
actions = [
        # {do="job.walk", update_="files"},
        # {do="job.limit", from_="files"}, 
        {do="log", msg="{files}", prefix="Selected"},
        {do="job.expand", from_="files", update_="tasks", inject={literal=["fpath"]}, template_="target"},
        {do="job.queue", from_="tasks"},       
]
