

[[locations]]
tex_template = "~/github/_templates/tex-config/tex/export_template.tex"
tex_export   = "{export}/tex"
tex_fail     = "{export}/tex/failed"
pdf_export   = "{export}/pdfs"

# TODO: compile bibtex to pdfs
# TODO: compile to html with bibtex2html

[[tasks.bib]]
name                 = "full.compile"
version              = "0.1"                                    # <str>
doc                  = ["trigger a full export, and compile the results"]
ctor                 = "task"                                   # <str>
depends_on           = ["bib::export", "bib::export.$head$", "bib::compile", "bib::compile.$head"]

[[tasks.bib]]
name                 = "pdf.compile"
version              = "0.1"
doc                  = ["compile anything in {bib_export} to pdf"]
ctor                 = "job"
queue_behaviour      = "default"
exts                 = [".bib"]
roots                = ["{bib_export}"]
actions = [
        {do="job.walk", update_="files"}, # walk
        {do="job.expand", key="fpath", base_="sub_actions", update_="tasks"},
        {do="job.queue", from_="tasks"} # queue
]
sub_actions          = [
                     # Load template
                     # set title, bib file
                     # compile tex
                     # compile bib
                     # compile tex
                     # compile tex
]

[[tasks.bib]]
name                 = "html.compile"
version              = "0.1"
doc                  = ["compile anything in {bib_export} to html"]
ctor                 = "job"
queue_behaviour      = "default"                                       # <str>                default | auto | reactive
exts                 = [".bib"]                                        # <list[str]>
roots                = ["{bib_export}"]                                # <list[str|pl.Path]>  Places the Walker will start
actions = [
        {do="job.walk", update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject="fpath", base_="sub_actions"},
        {do="job.queue", from_="tasks"}, # queue
]
sub_actions          = [
                     # Run bibtex2html
]

[[tasks.bib]]
name                 = "pdf.fails"
version              = "0.1"                                    # <str>
doc                  = ["Anything that has a tex file, but not a pdf, has failed somehow"]
ctor                 = "job"                                   # <str>
inject               = []                                       # <list[str]>
queue_behaviour      = "default"                                # <str>                default | auto | reactive
exts                 = [".bib"]                                 # <list[str]>
roots                = ["{bib}"]                                # <list[str|pl.Path]>  Places the Walker will start
actions = [
        {do="job.walk", update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject="fpath", base_="sub_actions"},
        {do="job.queue", from_="tasks"}, # queue
]
sub_actions          = [
                     # if pdf exists in temp for bib, silent
                     # else complain
]
