## compile.toml -*- mode: conf-toml -*-

[[locations]]
tex_template = {file="~/github/_templates/tex-config/tex/export_template.tex"}
tex_export   = "{export}/tex"
tex_fail     = "{export}/tex/failed"
pdf_export   = "{export}/pdfs"

[[tasks.compile]]
name                 = "full"
version              = "0.1"                                    # <str>
doc                  = ["trigger a full export, and compile the results"]
ctor                 = "task"                                   # <str>
depends_on           = [
    "export::all", "export::all.$head$",
    "compile::pdf", "compile::html",
    "compile::pdf.$head$", "compile::html.$head$"
 ]

[[tasks.compile]]
name                 = "pdf"
version              = "0.1"
doc                  = ["compile anything in {bib_export} to pdf"]
ctor                 = "job"
queue_behaviour      = "default"
exts                 = [".bib"]
roots                = ["{bib_export}"]
actions = [
        {do="job.walk", update_="files"}, # walk
        {do="job.expand", key_="fpath", template_="sub_actions", update_="tasks"},
        {do="job.queue", from_="tasks"}, # queue
]
sub_actions          = [
                     # Load template
                     # set title, bib file
                     # compile tex
                     # compile bib
                     # compile tex
                     # compile tex
]

[[tasks.compile]]
name                 = "html"
version              = "0.1"
doc                  = ["compile anything in {bib_export} to html"]
ctor                 = "job"
queue_behaviour      = "default"                                       # <str>                default | auto | reactive
exts                 = [".bib"]                                        # <list[str]>
roots                = ["{bib_export}"]                                # <list[str|pl.Path]>  Places the Walker will start
actions = [
        {do="job.walk", update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject={replace=["fpath"]}, template_="sub_actions"},
        {do="job.queue", from_="tasks"}, # queue
]
sub_actions          = [
                     # Run bibtex1html
]

[[tasks.compile]]
name                 = "_fails"
version              = "0.1"                                    # <str>
doc                  = ["Anything that has a tex file, but not a pdf, has failed somehow"]
ctor                 = "job"                                   # <str>
queue_behaviour      = "default"                                # <str>                default | auto | reactive
exts                 = [".bib"]                                 # <list[str]>
roots                = ["{bib}"]                                # <list[str|pl.Path]>  Places the Walker will start
actions = [
        {do="job.walk", update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject={replace=["fpath"]}, template_="sub_actions"},
        {do="job.queue", from_="tasks"}, # queue
]
sub_actions          = [
                     # if pdf exists in temp for bib, silent
                     # else complain
]


[[tasks.compile]]
name    = "calendar"
version = "0.1"
ctor    = "job"
doc     = ["create a calendar of when entries were added to the db"]
