
[[locations]]
bib_export    = "{export}/bib"
cal_export    = "{export}/calendar"

[[tasks.export]]
name            = "_.one.bib"
doc = ["export a bibtex, with latex encoding"]
cli              = [{ name="fpath", type="str", prefix="-", default="", desc="", positional=false  }]
export_bases     = ["{bib}"]
depends_on = [
        { do="relative?", args=["{fpath}"], bases_="export_bases" },
        # TODO skip if the exported bib exists and is recent
]
setup           = [
        { do="path.elements", from_="fpath", roots=["."]},
        { do="dootle.bibtex:BibtexInitAction",   update_="bib_db"},
        { do="taskcode.bibtex:build_working_parse_stack",  update_="parse_stack"},
        { do="taskcode.export:build_export_write_stack",   update_="export_stack" },
]
actions = [
        { do="dootle.bibtex:BibtexLoadAction", from_="fpath", update_="bib_db", parse_stack_="parse_stack" },
        { do="dootle.bibtex:BibtexToStrAction",  from_="bib_db",    update_="bib_text", write_stack_="export_stack" },
        { do="write!", from_="bib_text", to="{bib_export}/{fname}"},
]
cleanup = [
        { do="touch", args=["{fpath}"] },
        { do="log", msg="Exported {fname} to {bib_export}"},
]
