## make_html.toml -*- mode: toml-mode -*-
# Summary:
#
# Tags:
#
doot-version = "1.1"

[[locations]]
doc_conf = "."
doc_src  = "."
doc_out  = ".site"

[[tasks.make]]
disabled = false
name        = "html.site"
doc         = ["build sphinx"]
cli         = [{name="warn", type="bool", default=true},]
must_inject = ["warn"]
doc_builder = "html"
env_name    = "default"
depends_on  = []
setup       = [
    { do="installed?", args=["sphinx-build"]},
    { do="exists?", args=["{doc_src!p}/conf.py"] },
]
actions = [
    # --conf-dir {!p} : directory for conf.py
    { do="dootle.actions.shell:ShellAction", args=[
    "sphinx-build",
    # "--define", "keep_warnings=1",
    # "--verbose",
    "--quiet",
    # "--silent",
    "--conf-dir", "{doc_conf!p}",
    # "--write-all",
    # "--fresh-env",
    # "--nitpicky",
    "--keep-going", "--show-traceback",
    "--warning-file", "{logs!p}/sphinx.log",
    "--builder", "{doc_builder}",
    "{doc_src!p}",
    "{doc_out!p}"], errlimit=0},
    
    # {do="taskcode.refresher:refresh_firefox"},
    {do="shell!", args=["notify-send", "--expire-time=1000", "--transient", "Finished Building Docs"]},
]
cleanup = []
