## metadata.toml -*- mode: conf-toml -*-

[[locations]]
meta_backup = {path="{logs}/meta_backup.jsonl", file=true}
fail_log    = {path="{logs}/meta_failures.txt", file=true}
meta_cache  = {path="{temp}/metadata.commit_cache", file=true}

[[tasks.meta]]
name             = "_.single.file"
doc              = ["update the file metadata for all entries in a single bib file"]
version          = "0.1"
ctor             = "task"
cli              = [{ name="fpath", type="str", prefix="-", default="", desc="", positional=false  }]
roots            = ["{pdf_source!p}", "{bib!p}"]
depends_on       = [
    { do="ext?",      args=["{fpath!p}"], exts=[".bib"] },
    { do="relative?", args=["{fpath!p}"], bases_="roots"},
]
setup            = [
    { do="path.elements", from_="fpath" },
    { do="dootle.bibtex:BibtexInitAction",   update_="bib_db"},
    { do="taskcode.parse_stacks:build_meta_stack",  update_="parse_stack"},
]
actions          = [
    { do="log", msg="Metadata Update For Year: {fpath}", level="WARN"},
    # Read
    { do="dootle.bibtex:BibtexLoadAction",   from_="fpath",     update_="bib_db",   parse_stack_="parse_stack" },
    # Apply (TODO: change this to queue subtasks tasks)
    { do="taskcode.metadata:ApplyMetadataToLibrary", from_="bib_db", backup_="meta_backup"},
    { do="append!", to_="fail_log", args=["{failures}"] },
]
cleanup = [
    { do="touch", args=["{fpath!p}"], soft=true },
]
