## metadata.toml -*- mode: conf-toml -*-

[[locations]]
meta_backup = {loc="{logs}/meta_backup.jsonl", file=true}
fail_log    = {file="{logs}/meta_failures.txt"}
meta_cache  = {file="{temp}/metadata.commit_cache"}

[[tasks.meta]]
name             = "_.by.year"
doc              = ["update the file metadata for all entries in a single bib file"]
version          = "0.1"
ctor             = "task"
cli              = [{ name="fpath", type="str", prefix="-", default="", desc="", positional=false  }]
roots            = ["{pdf_source}", "{bib}"]
depends_on       = [
    { do="ext?",      args=["{fpath}"], exts=[".bib"] },
    { do="relative?", args=["{fpath}"], bases_="roots"},
]
setup            = [
    { do="path.elements", from_="fpath" },
    { do="dootle.bibtex:BibtexInitAction",   update_="bib_db"},
    { do="taskcode.metadata:build_metadata_parse_stack",  update_="parse_stack"},
]
actions          = [
    { do="log", msg="Metadata by year: {fpath}", level="WARN"},
    # Read
    { do="dootle.bibtex:BibtexLoadAction",   from_="fpath",     update_="bib_db",   parse_stack_="parse_stack" },
    # Apply
    { do="taskcode.metadata:ApplyMetadata", from_="bib_db", backup_="meta_backup"},
    { do="append!", to="{fail_log}", args=["{failures}"] },
]
cleanup = [
    { do="touch", args=["{fpath}"] },
]
