## metadata.toml -*- mode: toml -*-
doot-version = "1.0"


[[locations]]
meta_backup = "file::>{logs}/meta_backup.jsonl"
fail_log    = "file::>{logs}/meta_failures.txt"
meta_cache  = "file::>{temp}/metadata.commit_cache"

[[tasks.meta]]
name             = "_.single.file"
doc              = ["update the file metadata for all entries in a single bib file"]
version          = "0.1"
ctor             = "task"
cli              = [{ name="-fpath", type="str", default="", desc=""}]
roots            = ["{pdf_source!p}", "{bib!p}"]
depends_on       = [
    { do="ext?",      args=["{fpath!p}"], exts=[".bib"] },
    { do="relative?", args=["{fpath!p}"], bases_="roots"},
]
setup            = [
    { do="path.elements",             from_="fpath" },
    { do="dootle.bibtex:InitDb",      update_="bib_db"},
    { do="dootle.bibtex:BuildLoader", update_="bib_reader", stack="taskcode.parse_stacks:build_meta_stack"},
]
actions          = [
    { do="log", msg="Metadata Update For Year: {fpath}", level="WARN"},
    # Read
    { do="dootle.bibtex:DoLoad", from_="fpath", update_="bib_db", reader="bib_reader"},
    # Apply (TODO: change this to queue subtasks tasks)
    { do="taskcode.metadata:ApplyMetadataToLibrary", from_="bib_db", backup_="meta_backup"},
    { do="append!", to_="fail_log", args=["{failures}"] },
]
cleanup = [
    { do="touch", args=["{fpath!p}"], soft=true },
]
