## metadata.toml -*- mode: conf-toml -*-

[[locations]]
meta_backup = {loc="{logs}/meta_backup.jsonl", file=true}
fail_log    = {file="{logs}/meta_failures.txt"}
meta_cache  = "{temp}/metadata.commit_cache"

[[tasks.meta]]
name             = "total"
doc              = ["Update the metadata for each file in the library"]
ctor             = "job"
version          = "0.1"
cli              = [{ name="target", type="str", prefix="-", default="{bib}", desc="", positional=false  }]
roots            = ["{target}"]
exts             = [".bib"]
recursive        = false
select_limit     = 10
actions          = [
        # walk
        {do="job.walk", update_="walked"},
        # expand
        {do="job.limit",       from_="walked", count_="select_limit", method="taskcode.selector:sort_oldest"},
        {do="job.expand",      from_="walked", update_="tasks", inject={replace=["fpath"]}, template="meta::_.by.year"},
        {do="taskcode.metadata:report_chosen_files"},
        {do="wait", count=5},
        # queue
        {do="job.queue",       from_="tasks"},
        # on complete, cache head commit
        { do="dootle.utils.commit_caching:CacheGitCommit", cache="{meta_cache}"}
]

[[tasks.meta]]
name             = "changed"
doc              = ["Update the metadata for files that have been changed since the last metadata update task was run"]
ctor             = "job"
version          = "0.1"
cli              = [{ name="target", type="str", prefix="-", default="{bib}", desc="", positional=false  }]
roots            = ["{target}"]
exts             = [".bib"]
actions          = [
        # get files changed since commit and head
        {do="dootle.utils.commit_caching:GetChangedFilesByCommit", cache="{meta_cache}" , update_="changed" },
        # expand
        {do="job.expand",      from_="changed", update_="tasks", inject={replace=["fpath"]}, template="meta::_.by.year"},
        {do="taskcode.metadata:report_chosen_files"},
        {do="wait", count=5},
        # queue
        {do="job.queue",       from_="tasks"},
        ]
cleanup = [
        # on complete, cache head commit
        { do="dootle.utils.commit_caching:CacheGitCommit", cache="{meta_cache}"}
]

[[tasks.meta]]
name             = "_.by.year"
doc              = ["update the file metadata for all entries in a single bib file"]
version          = "0.1"
ctor             = "task"
cli              = [{ name="fpath", type="str", prefix="-", default="", desc="", positional=false  }]
roots            = ["{pdf_source}", "{bib}"]
depends_on       = [
    { do="ext?",      args=["{fpath}"], exts=[".bib"] },
    { do="relative?", args=["{fpath}"], bases_="roots"},
]
setup            = [
    { do="path.elements", from_="fpath" },
    { do="dootle.bibtex:BibtexInitAction",   update_="bib_db"},
    { do="taskcode.metadata:build_metadata_parse_stack",  update_="parse_stack"},
]
actions          = [
    { do="log", msg="Metadata by year: {fpath}", level="WARN"},
    # Read
    { do="dootle.bibtex:BibtexLoadAction",   from_="fpath",     update_="bib_db",   parse_stack_="parse_stack" },
    # Apply
    { do="taskcode.metadata:ApplyMetadata", from_="bib_db", backup_="meta_backup"},
    { do="append!", to="{fail_log}", args=["{failures}"] },
    { do="touch", args=["{fpath}"] },
]
