## online.toml -*- mode: toml -*-
doot-version = "1.0"


[[locations]]
online_todo   = "file::>{home_repo}/submodules_/bibliography/in_progress/online.bib"
online_saves  = "/media/john/data/todo/pdfs/online"

[[tasks.online]]
name             = "download.entries"
doc              = ["save todo online entries as pdfs"]
fpath            = "{online_todo!p}"
depends_on       = [
    { do="dir!", args=["{online_saves!p}"]},
    { do="ext?", args=["{fpath!p}"], exts=[".bib"] },
]
setup            = [
      { do="path.elements",             from_="fpath" },
      { do="dootle.bibtex:InitDb",      update_="bib_db"},
      { do="taskcode.io_stack:build_new_stack", update_="download_stack", online=true},
      { do="dootle.bibtex:BuildReader", update_="bib_reader", stack_="download_stack"},
      { do="dootle.bibtex:BuildWriter", update_="bib_writer", stack_="download_stack" },
]
actions          = [
    { do="log", msg="Downloading Entries" },
    { do="dootle.bibtex:DoRead", from_="fpath", update_="bib_db", reader_="bib_reader"},
    { do="dootle.bibtex:ToStr", from_="bib_db",  update_="bib_text", writer_="bib_writer"},
    { do="write!", from_="bib_text", to="{temp!p}/{fstem}_saved.bib"},
]
cleanup          = [
    { do="fn::taskcode.online:shutdown_firefox" },
    # TODO write failed blocks
]

