
[[locations]]
online_todo   = {file="~/github/bibliography/in_progress/online.bib"}
online_saves  = "/media/john/data/todo/pdfs/online"

[[tasks.online]]
name             = "download.entries"
version          = "0.1"
ctor             = "task"
doc              = ["save todo online entries as pdfs"]
fpath            = "{online_todo}"
depends_on       = [
    { do="dir!", args=["{online_saves}"]},
    { do="ext?", args=["{fpath}"], exts=[".bib"] },
]
setup            = [
      { do="path.elements", from_="fpath" },
      { do="dootle.bibtex:BibtexInitAction",   update_="bib_db"},
      { do="taskcode.online:build_online_downloader_parse_stack",  update_="parse_stack"},
      { do="taskcode.online:build_online_downloader_write_stack",  update_="write_stack" },
]
actions          = [
    # Load
    { do="dootle.bibtex:BibtexLoadAction",   from_="fpath",     update_="bib_db",   parse_stack_="parse_stack" },
    # Write
    # TODO: add a transform action here instead of middleware transform?
    { do="dootle.bibtex:BibtexToStrAction",  from_="bib_db",    update_="bib_text", write_stack_="write_stack" },
    { do="write!", from_="bib_text", to="{temp}/{fstem}_saved.bib"},

]
cleanup          = [
    { do="taskcode.online:shutdown_firefox" },
    { do="dootle.bibtex:BibtexFailedBlocksWriteAction", target="{temp}/failed_{fstem}.bib" },
]
