## orphans.toml -*- mode: conf-toml -*-

[[locations]]
orphans = "{temp}/orphans"

[[tasks.orphans]]
name       = "total"
depends_on = ["file:>{orphans}/bib.files", "file:>{orphans}/fs.files"]
actions = [
        # read file lists
        {do="read", from="{orphans}/bib.files", type="lines", update_="bib"},
        {do="read", from="{orphans}/fs.files", type="lines",  update_="fs"},
        # diff them
        {do="taskcode.orphans:diff_filelists"},
        # write results:
        {do="write!", from_="only_mentioned", to="{orphans}/only_mentioned.files"},
        {do="write!", from_="only_exists",    to="{orphans}/only_exists.files"},
]

[[tasks.orphans]]
name             = "_.bib"
doc              = ["walk all bibfiles, summarise entry files"]
ctor             = "job"
version          = "0.1"
required_for     = [{loc="{orphans}/bib.files", file=true}]
roots            = ["{bib}"]
exts             = [".bib"]
actions          = [
    {do="delete!", args=["{orphans}/bib.files"]},
    {do="job.walk", update_="walked"},
    {do="job.expand",      from_="walked", update_="tasks", inject={replace=["fpath"]}, template_="sub_actions"},
    {do="job.queue",       from_="tasks"},
]
sub_actions = [
    { do="ext?", args=["{fpath}"], exts=[".bib"] },
    { do="path.elements", from_="fpath" },
    { do="dootle.bibtex:BibtexInitAction",   update_="bib_db"},
    { do="taskcode.bibtex:build_working_parse_stack",  update_="parse_stack"},
    { do="dootle.bibtex:BibtexLoadAction",   from_="fpath",     update_="bib_db",   parse_stack_="parse_stack" },
    { do="taskcode.orphans:get_db_files", from_="bib_db" , update_="filelist"},
    { do="append!", args=["{filelist}"], to="{orphans}/bib.files"},
]

[[tasks.orphans]]
name             = "_.filesystem"
doc              = ["walk the library filesystem, summarising all existing files"]
ctor             = "job"
version          = "0.1"
required_for     = [{loc="{orphans}/fs.files", file=true}]
roots            = ["{lib-root}"]
exts             = [".pdf", ".epub"]
actions          = [
    {do="delete!", args=["{orphans}/fs.files"]},
    {do="job.walk", update_="walked"}, # TODO: or use fdfind
    {do="write!", from_="walked", to="{orphans}/fs.files" }
]
