## precommit.toml -*- mode: conf-toml -*-

[[locations]]
changed_file = {file="{temp}/.changed"}

[[tasks.precommit]]
name     = "validate"
version  = "0.1"                # <str>
doc      = ["Validate a commit message"]
cli      = [{ name="msgfile",   default="", type="str", positional=true }]
ctor     = "task"               # <str>
actions  = [
         {do="read", from_="msgfile", update_="text"},
         {do="taskcode.precommit:validate", from_="text"}
]

[[tasks.precommit]]
name          = "top"
ctor          = "job"
cli           = [{ name="files",   type="list", default=[], positional=true }]
actions       = [
            # todo append changed file list to {changed_file}
            {do="job.expand", from_="files", update_="format_tasks", inject={replace=["fpath"]}, base="format::_individual"},
            {do="job.expand", from_="files", update_="tag_tasks",    inject={replace=["fpath"]}, base="tags::_extract.bib"},
            # todo {do="job.expand", from_="file", update_="meta_tasks", inject={replace=["fpath"]}, base="meta::_by.year"},
            # todo {do="job.expand", from_="files", update_="tag_tasks", inject={replace=["fpath"]}, base="summary::top"},
            # todo {do="job.expand", from_="files", update_"backup_tasks", inject={replace=["fpath"]}, base="backup::_by.year"},
            {do="job.queue", from_multi_=["format_tasks", "tag_tasks"]}, # queue
            {do="job.queue.head", base_="head_actions"}, # head actions clear changed file
            # alt head: {do="job.queue.head", base="precommit::_simple"},
]
head_actions = [
             {do="log", msg="Finished"}
             # todo clear changed file
]

[[tasks.precommit]]
name            = "_simple"
ctor            = "task"
actions         = [
             {do="log", msg="Finished"}
             # todo clear changed filej
]
