## precommit.toml -*- mode: conf-toml -*-

[[locations]]
changed_file = {loc="{temp}/.changed", file=true}

[[tasks.precommit]]
name     = "validate"
version  = "0.1"                # <str>
doc      = ["Validate a commit message"]
cli      = [{ name="msgfile",   default="", type="str", positional=true }]
ctor     = "task"               # <str>
actions  = [
         {do="read", from_="msgfile", update_="text"},
         {do="taskcode.precommit:validate", from_="text"}
]

[[tasks.precommit]]
name          = "pre"
doc           = ["Is passed a cli list of files changed, which are used to queue subtasks"]
ctor          = "job"
cli           = [{ name="files",   type="list", default=[], positional=true }]
print_levels  = { head="INFO", build="WARN", action="WARN", sleep="WARN", execute="WARN" }
depends_on    = ["bookmark::update"]
cleanup       = [
   {do="log", msg="Finished"}
   # todo clear changed file
]
actions       = [
   # TODO append changed file list to {changed_file}
   {do="log", msg="Formatting/Meta/Backup for : {files}"},
   {do="job.expand", prefix="format", from_="files", update_="format_tasks", inject={replace=["fpath"]}, template="format::_.by.year"},
   # TODO move these to a postcommit hook
   # {do="job.expand", prefix="meta",   from_="files", update_="meta_tasks",   inject={replace=["fpath"]}, template="meta::_.by.year"},
   # {do="job.expand", prefix="backup", from_="files", update_="backup_tasks", inject={replace=["fpath"]}, template="backup::_.by.year"},
   {do="job.queue", from_multi_=["format_tasks", "meta_tasks", "backup_tasks"]},
]

[[tasks.precommit]]
name       = "post"
doc        = []
ctor       = "job"
depends_on = ["bib::cleanup"]
actions    = [
           # TODO queue latex export of changed bibs
           # TODO queue build of changed exported bibs
]
