
[[tasks.precommit]]
name                 = "validate"
version              = "0.1"                # <str>
doc                  = ["Validate a commit message"]
cli                  = [
{ name="msgfile",   default="", type="str", positional=true },
# { name="changed",   default=[], type="list", positional=true }
]
ctor                 = "task"               # <str>
actions              = [
                     {do="read", from_="msgfile", update_="text"},
                     {do="taskcode.precommit:validate", from_="text"}
]
