## precommit.toml -*- mode: conf-toml -*-

[[locations]]
changed_file = {file="{temp}/.changed"}

[[tasks.precommit]]
name     = "validate"
version  = "0.1"                # <str>
doc      = ["Validate a commit message"]
cli      = [{ name="msgfile",   default="", type="str", positional=true }]
ctor     = "task"               # <str>
actions  = [
         {do="read", from_="msgfile", update_="text"},
         {do="taskcode.precommit:validate", from_="text"}
]

[[tasks.precommit]]
name          = "top"
doc           = ["Is passed a cli list of files changed, which are used to queue subtasks"]
ctor          = "job"
cli           = [{ name="files",   type="list", default=[], positional=true }]
print_levels  = { head="INFO", build="WARN", action="WARN", sleep="WARN", execute="WARN" }
depends_on    = ["bookmark::update"]
actions       = [
            # todo append changed file list to {changed_file}
            {do="job.expand", prefix="format", from_="files", update_="format_tasks", inject={replace=["fpath"]}, base="format::_by.year"},
            {do="job.expand", prefix="meta",   from_="files", update_="meta_tasks",   inject={replace=["fpath"]}, base="meta::_by.year"},
            {do="job.expand", prefix="backup", from_="files", update_="backup_tasks", inject={replace=["fpath"]}, base="backup::_by.year"},
            {do="job.queue", from_multi_=["format_tasks", "tag_tasks", "meta_tasks", "backup_tasks"]}, # queue
            {do="job.queue.head", base_="head_actions"}, # head actions clear changed file
]
head_actions = [
             {do="log", msg="Finished"}
             # todo clear changed file
]
