[[locations]]
todo_bib   = "~/github/bibliography/in_progress/todo.bib"
dropbox    = "~/Dropbox/docs"
downloads  = "~/Downloads"
todo_pdfs  = "/media/john/data/todo/pdfs"

[[tasks.bib]]
name                 = "stubber"
version              = "0.1"                                 # <str>
doc                  = []                                    # <list[str]>
ctor                 = "job"                                # <str>
mixins               = ["job:walker", "job:terse"]                   # <list>               mix in additional capabilities
queue_behaviour      = "default"                             # <str>                default | auto | reactive
exts                 = [".pdf", ".epub"]                     # <list[str]>
roots                = ["{dropbox}"]                         # <list[str|pl.Path]>  Places the Walker will start
recursive            = false                                 # <bool>
print_levels         = {execute="INFO", action="INFO"}
target               = "{todo_pdfs}/{fname}"
inject               = ["target"]
accept_fn            = "task_code.stubber:not_copied"
sub_actions          = [
                     {do="skipIfFile", args=["{target}"]},
                     {do="copy", from_="fpath", to="{target}"},
                     {do="task_code.stubber:gen_stub", update_="stubtext", to="{target}"},
                     {do="putPost", args=["{stubtext}"]},
                     {do="delete!", args=["{fpath}"]},
]
head_actions         = [
                     {do="getPost", stubs="-"},
                     {do="task_code.stubber:join_stubs", from_="stubs", update_="text"},
                     {do="doot.actions.io:AppendAction", args=["{text}"], sep="\n", to="{todo_bib}" },
]

[[tasks.bib]]
name        = "cleanup"
version     = "0.1"
ctor        = "job"
mixins      = ["job:walker", "job:terse"]
accept_fn   = "task_code.stubber:select_refiled"
roots       = ["{todo_pdfs}"]
sub_actions = [{do="delete!", args=["{fpath}"]}]
