

[[locations]]
count_out = "{temp}/counts"

[[tasks.summary]]
name        = "manual.top"
doc         = ["Summarise main"]
ctor        = "job"
mixins      = ["job:match", "job:walker"]
exts        = [".bib", ".bookmarks"]
roots       = ["{bib}"]
match_fn    = "ext"
match_field = "fpath"
match_map   = { ".bib"="summary::_bibs", ".bookmarks"="summary::_bookmarks"}
head_task   = "summary::_fin"

[[tasks.summary]]
name = "_bibs"
actions = []

[[tasks.summary]]
name    = "_bookmarks"
actions = []

[[tasks.summary]]
name    = "_fin"
actions = []
