

[[locations]]
count_out = "{temp}/counts"

[[tasks.summary]]
name        = "manual.top"
doc         = ["Summarise main"]
ctor        = "job"
exts        = [".bib", ".bookmarks"]
roots       = ["{bib}"]
match_fn    = "ext"
match_map   = { ".bib"="summary::_bibs", ".bookmarks"="summary::_bookmarks"}
actions     = [
        {do="job.walk",   update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject={replace=["fpath"]}},
        {do="job.match",  onto_="tasks", mapping_="match_map"},
        {do="job.queue",  from_="tasks"}, # queue
        {do="job.queue.head", base="summary::_fin"}
]

[[tasks.summary]]
name = "_bibs"
actions = []

[[tasks.summary]]
name    = "_bookmarks"
actions = []

[[tasks.summary]]
name    = "_fin"
actions = []
