## summary.toml -*- mode: conf-toml -*-

[[locations]]
count_out = "{temp}/counts"

[[tasks.summary]]
name    = "_.bibs"
doc     = ["TODO Summarise bib files"]
actions = []

[[tasks.summary]]
name    = "_.bookmarks"
doc     = ["TODO"]
actions = []
