## summary.toml -*- mode: conf-toml -*-

[[locations]]
count_out = "{temp}/counts"

[[tasks.summary]]
name    = "_.all.bibs"
doc     = ["TODO Summarise bib files"]
actions = [
        # all files
        # all entries
        # entry type distribution
        # entries with no file
        # entries with no tags
]

[[tasks.summary]]
name    = "_.all.bookmarks"
doc     = ["TODO"]
actions = []

[[tasks.summary]]
name = "_.one.file"

[[tasks.summary]]
name = "_.file.count"

[[tasks.summary]]
name = "_.authors"

[[tasks.summary]]
name = "_.tagging"

[[tasks.summary]]
name = "_.important"

[[tasks.summary]]
name = "_.come.back.to"

[[tasks.summary]]
name = "tag.timeline"

[[tasks.summary]]
name = "top.level.domains"

[[tasks.summary]]
name = "proceedings"
