
# TODO: merge
# TODO: diff
# TODO: substitutions

[[tasks.tags]]
disable = true
name                 = "cleaner"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
doc                  = ["todo"]                   # <list[str]>
depends_on           = ["file:>{temp}/tags/totals.tags"]                   # <list[DootTaskArtifact]>
actions              = [
                     { do="task_code.tags:read_tags", from="{temp}/tags/totals.tags", update_="tags" }
]                   # <list[Any]>


[[tasks.tags]]
name                     = "totals"
version                  = "0.1"                                                                  # <str>
ctor                     = "job"
mixins                   = ["job:walker", "job:terse"]
docs                     = ["extract known and new tags"]
roots                    = ["{substitutions}/general"]                                            # <list[str|pl.Path]>  Places the walker will start
exts                     = [".sub"]                                                               # <list[str]>
recursive                = false                                                                  # <bool>
# accept_fn              = ""                                                                     # <callable>
sub_actions              = [{ do="task_code.tags:ReadSubs", from="{fpath}", update_="subs" }]     # <list[Any]>
head_actions             = [
                     { do="task_code.tags:write_known", to="{temp}/tags/known.tags"},
                     { do="task_code.tags:ReadSubs",  from="{substitutions}/people.sub", update_="tags" },
                     { do="task_code.tags:read_tags", from="{temp}/tags/totals.tags", update_="tags" },
                     { do="task_code.tags:write_new", from_="tags", to="{temp}/tags/new.tags" },
]

[[tasks.bib]]
name                 = "names.and.tags"
version              = "0.1"                                                                # <str>
ctor                 = "job"                                                             # <type>
mixins               = ["job:walker", "job:terse"]
doc                  = ["extract names and tags from bibtex files"]                         # <list[str]>
print_levels         = {action="WARN", execute="WARN"}                                      # <Dict: {'action', 'execute', 'build', 'sleep', 'head'}>
inject               = ["fpath", "fstem", "fname", "lpath"]                                 # <('list',)>
roots                = ["{bib}"]                                                            # <list[str|pl.Path]>  Places the job:walker will start
exts                 = [".bib"]                                                             # <list[str]>
sub_actions          = [
                     { do="dootle.bibtex.v2:BibtexInitAction",   update_="bib_db"},
                     { do="task_code.bibtex:build_parse_stack",  update_="parse_stack"},
                     { do="task_code.bibtex:build_write_stack",  update_="write_stack" },
                     { do="type!", bib_db="bibtexparser.library:Library"},
                     { do="dootle.bibtex.v2:BibtexLoadAction",  from_="fpath",     update_="bib_db",   parse_stack_="parse_stack"},
                     { do="dootle.bibtex.v2:BibtexToStrAction", from_="bib_db",    update_="bib_text", write_stack_="write_stack" },
]                                                                                                                         # <str>
head_actions = [
             { do="task_code.bibtex:write_tag_set", update_="tags" },
             { do="write!", from_="tags", to="{temp}/tags/bib.tags"},
             { do="task_code.bibtex:write_name_set", update_="names" },
             { do="write!", from_="names", to="{temp}/tags/bib.names" }
]

[[tasks.bookmark]]
name                 = "tags"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
doc                  = ["Create a Tags file of the main bookmark's tags"] # <list[str]>
depends_on           = ["file:>{bookmarks}"]                   # <list[DootTaskArtifact]>
actions              = [
                     { do="dootle.bookmarks.actions:BookmarksLoad", from="{bookmarks}", update_="total_bkmks" },
                     { do="task_code.bkmk:collect_tags", from_="total_bkmks", update_="tags" },
                     { do="write!", from_="tags", to="{temp}/tags/bkmks.tags" },
]
