## tags.toml -*- mode: conf-toml -*-

[[locations]]
known_tag_file   = {path="{temp}/tags/known.tags", file=true}
canon_tag_file   = {path="{temp}/tags/canon.tags", file=true}
bkmk_tag_file    = {path="{temp}/tags/bkmks.tags", file=true}
total_subs_file  = {path="{temp}/tags/total.subs", file=true}

[[tasks.tags]]
name         = "_.build.total"
doc          = ["build the totals.tags file from individual tag substitution files"]
ctor         = "job"
roots        = ["{substitutions!p}/general"]
exts         = [".sub"]
recursive    = false
required_for = [{path="{known_tag_file}"}, {path="{canon_tag_file}"}]
depends_on   = [
    "tags::_.build.bkmk.tags",
    # Skip if totals.tags was modified today
    {do="dootle.utils.recency_test:recency_test", target="{canon_tag_file!p}"},
]
actions   = [
    # walk and read all sub files
    {do="job.walk",   update_="files"}, # walk,
    {do="job.expand", from_="files", update_="tasks", inject={insert=["fpath"]}, template_="read_sub_actions"},
    {do="job.queue",  from_="tasks"}, # queue
]
read_sub_actions              = [
    { do="taskcode.tags:read_subs", from="{fpath!p}", update_="subs" },
    { do="post.put", "tags::read..allsubs"=["{subs}"] },
]
head_actions = [
    { do="log", msg="Building Canon Tags"},
    { do="post.get", sub_objs="tags::read..allsubs" },
    { do="taskcode.tags:read_tags", from="{bkmk_tag_file!p}", update_="bkmk_tags" },
    { do="taskcode.tags:merge_subfiles_to_known_and_canon", args=["sub_objs", "bkmk_tags"] },
    # Write out to temp files
    { do="write!",  from_="known_tags", to="{known_tag_file!p}" },
    { do="write!",  from_="canon_tags", to="{canon_tag_file!p}" },
    { do="write!",  from_="total_subs", to="{total_subs_file!p}" }
]

[[tasks.tags]]
name    = "_.build.bkmk.tags"
docs    = ["Read the boomarks file, extract tags from it, write to bkmk_tag_file"]
ctor    = "task"
depends_on = [
           # skip if bkmk.tags was touched today
           {do="dootle.utils.recency_test:stale_test", source="{bookmarks!p}", dest="{bkmk_tag_file!p}"},
]
actions = [
        {do="log", msg="Building Tags Summary from Bookmarks"},
        # read {bookmarks}
        { do="dootle.bookmarks.actions:BookmarksLoad", from="{bookmarks!p}", update_="total_bkmks" },
        # extract tags
        { do="taskcode.bkmk:collect_tags", from_="total_bkmks", update_="tags" },
        # write
        {do="write!", from_="tags", to="{bkmk_tag_file!p}"}
]

[[tasks.tags]]
name           = "_.calculate.update"
doc            = ["Calculate the difference between known tags and new tags"]
must_inject    = ["fpath"]
ctor           = "task"
roots          = ["{substitutions!p}/general"]
exts           = [".sub"]
recursive      = false
depends_on     = ["tags::_.build.total"]
actions        = [
    { do="log", msg="Calculating Tags Update" },
    # Get existing totals
    { do="taskcode.tags:read_tags",      from="{canon_tag_file!p}", update_="total_tags" },
    # Get tags from accumulator
    { do="taskcode.tags:TagAccumulator", update_="file_tags"},
    # Calc update
    { do="taskcode.tags:TagCalculator",  raw_="file_tags", totals_="total_tags"},
    # Then write them
    { do="path.elements", from_="fpath", roots=["{bib!p}"] },
    { do="write!",        from_="new_tags", to="{temp!p}/tags/{fstem}_new.tags"},
    # Clear the tag record
    { do="taskcode.tags:TagAccumulator", clear=true},
]
