
# TODO: merge
# TODO: diff
# TODO: substitutions

[[tasks.tags]]
disable = true
name                 = "cleaner"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
doc                  = ["TODO"]                   # <list[str]>
depends_on           = ["file:>{temp}/tags/totals.tags"]                   # <list[DootTaskArtifact]>
actions              = [
                     { do="taskcode.tags:read_tags", from="{temp}/tags/totals.tags", update_="tags" }
]

[[tasks.tags]]
name                     = "totals"
version                  = "0.1"                                                                  # <str>
ctor                     = "job"
docs                     = ["extract known and new tags"]
roots                    = ["{substitutions}/general"]                                            # <list[str|pl.Path]>  Places the walker will start
exts                     = [".sub"]                                                               # <list[str]>
recursive                = false                                                                  # <bool>
actions                  = [
        {do="job.walk", update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject="fpath", base_="sub_actions"},
        {do="job.queue", from_="tasks"}, # queue
        {do="job.queue.head", base_="head_actions"}

]
sub_actions              = [{ do="taskcode.tags:ReadSubs", from="{fpath}", update_="subs" }]     # <list[Any]>
head_actions             = [
                            { do="taskcode.tags:write_known", to="{temp}/tags/known.tags"},
                            { do="taskcode.tags:ReadSubs",  from="{substitutions}/people.sub", update_="tags" },
                            { do="taskcode.tags:read_tags", from="{temp}/tags/totals.tags",    update_="tags" },
                            { do="taskcode.tags:write_new", from_="tags", to="{temp}/tags/new.tags" },
]

[[tasks.tags]]
name                 = "extract"
version              = "0.1"                                                                # <str>
ctor                 = "job"                                                             # <type>
doc                  = ["extract names and tags from bibtex files"]                         # <list[str]>
print_levels         = {action="WARN", execute="WARN"}                                      # <Dict: {'action', 'execute', 'build', 'sleep', 'head'}>
inject               = ["fpath", "fstem", "fname"]                                 # <('list',)>
roots                = ["{bib}"]                                                            # <list[str|pl.Path]>  Places the job:walker will start
exts                 = [".bib"]                                                             # <list[str]>
actions = [
        {do="job.walk", update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject="fpath", base="tags::_extract.bib"},
        {do="job.queue", from_="tasks"}, # queue
        {do="job.queue.head", base="tags::_extract.bib.finish"},
]

[[tasks.tags]]
name             = "_extract.bib"
ctor             = "task"
actions          = [
                     { do="dootle.bibtex.v2:BibtexInitAction",   update_="bib_db"},
                     { do="taskcode.bibtex:build_working_parse_stack",  update_="parse_stack"},
                     { do="taskcode.bibtex:build_working_write_stack",  update_="write_stack" },
                     { do="type!", bib_db="bibtexparser.library:Library"},
                     { do="dootle.bibtex.v2:BibtexLoadAction",  from_="fpath",     update_="bib_db",   parse_stack_="parse_stack"},
                     { do="dootle.bibtex.v2:BibtexToStrAction", from_="bib_db",    update_="bib_text", write_stack_="write_stack" },
]                                                                                                                         # <str>

[[tasks.tags]]
name     = "_extract.bib.finish"
ctor     = "task"
actions  = [
             { do="taskcode.tags:write_tag_set", update_="tags" },
             { do="write!", from_="tags", to="{temp}/tags/bib.tags"},
             { do="taskcode.tags:write_name_set", update_="names" },
             { do="write!", from_="names", to="{temp}/tags/bib.names" }
]

[[tasks.tags]]
name                 = "extract.bkmk"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
doc                  = ["Create a Tags file of the main bookmark's tags"] # <list[str]>
depends_on           = ["file:>{bookmarks}"]                   # <list[DootTaskArtifact]>
actions              = [
                     { do="dootle.bookmarks.actions:BookmarksLoad", from="{bookmarks}", update_="total_bkmks" },
                     { do="taskcode.bkmk:collect_tags", from_="total_bkmks", update_="tags" },
                     { do="write!", from_="tags", to="{temp}/tags/bkmks.tags" },
]
