5G                                                    : 1
AA4MM                                                 : 1
AAA                                                   : 2
AAAI                                                  : 21
AAF                                                   : 1
AAIDE                                                 : 1
AAIHS                                                 : 2
AALAADIN                                              : 1
AAP                                                   : 1
AARON                                                 : 1
AASPIRE                                               : 1
AATS                                                  : 1
AAVE                                                  : 1
ABA                                                   : 1   : 1ABC
ABL                                                   : 14
ABM                                                   : 95
ABMS                                                  : 2
ABODE                                                 : 2
ABT                                                   : 1
ACA                                                   : 19
ACAB                                                  : 1
ACL                                                   : 18
ACLED                                                 : 1
ACLU                                                  : 12
ACM                                                   : 3
ACME                                                  : 1
ACORN                                                 : 2
ACRE                                                  : 1
ACRES                                                 : 1
ACT                                                   : 2
ACTA                                                  : 2
ACT_IF                                                : 2
ACT_R                                                 : 5
ACT_RPM                                               : 1
ADA                                                   : 3
ADELFE                                                : 1
ADHD                                                  : 1
ADICO                                                 : 4
ADL                                                   : 1
ADM                                                   : 1
ADMS                                                  : 1
ADOS                                                  : 6
ADT                                                   : 1
AEI                                                   : 1
AEIO                                                  : 1
AER                                                   : 1
AESOP                                                 : 1
AFAPL2                                                : 1
AFM                                                   : 1
AF_APL                                                : 1
AGAVE                                                 : 1
AGENT                                                 : 1
AGENT_0                                               : 1
AGI                                                   : 5
AGORA                                                 : 1
AGR                                                   : 2
AGRE                                                  : 1
AHA19                                                 : 1
AHF                                                   : 1
AHP                                                   : 1
AI                                                    : 2
AI4SG                                                 : 1
AIDS                                                  : 11
AIED                                                  : 1
AIES                                                  : 1
AIES2020                                              : 1
AIIDE                                                 : 3
AIKR                                                  : 1
AINRM                                                 : 1
AIPAC                                                 : 1
AIPS                                                  : 1
AIRR                                                  : 1
AISB                                                  : 3
AITA                                                  : 2
AKIRA                                                 : 1
ALC                                                   : 1
ALEC                                                  : 1
ALIGN                                                 : 1
ALIVE                                                 : 1
ALLIANCE                                              : 1
ALM                                                   : 1
ALSTOM                                                : 1
AMA                                                   : 1
AMAS                                                  : 1
AMELI                                                 : 3
AMIRIS                                                : 1
AMT                                                   : 1
AMTs                                                  : 1
ANFIS                                                 : 1
ANMA                                                  : 1
ANT                                                   : 1
ANTE                                                  : 1
ANTHEM                                                : 1
ANTLR                                                 : 6   : antlr
ANTS                                                  : 1
AO*                                                   : 1
AOP                                                   : 21
AORML                                                 : 1
AORTA                                                 : 1
AOSE                                                  : 3
AOSF                                                  : 1
APALACHE                                              : 1
API                                                   : 11
APL                                                   : 1
ARCHON                                                : 1
ARG                                                   : 2
ARGO                                                  : 1
ARM                                                   : 1
ARPANET                                               : 1
ARTIMIS                                               : 1
ART_SHTA                                              : 1
ARV                                                   : 1
AR_15                                                 : 1
ASAP                                                  : 1
ASCS                                                  : 1
ASC_inclusion                                         : 1
ASD                                                   : 1
ASEAN                                                 : 1
ASP                                                   : 24
ASPAL                                                 : 1
ASP_                                                  : 1
ASSA                                                  : 1
AST                                                   : 1
ASTRA                                                 : 2
ATC21S                                                : 1
ATCO                                                  : 1
ATF                                                   : 1
ATL                                                   : 5
ATLANTIS                                              : 1
ATLEA                                                 : 1
ATM                                                   : 1
ATOMIC                                                : 3
ATTL                                                  : 1
ATUS                                                  : 1
AThOS                                                 : 1
AUML                                                  : 1
AVICENA                                               : 1
AVIE                                                  : 1
AWIC                                                  : 1
AWK                                                   : 1
AWS                                                   : 2
AfD                                                   : 1
BACON                                                 : 1
BART                                                  : 2
BASIC                                                 : 1
BBC                                                   : 123
BBC_                                                  : 7
BBI                                                   : 1
BBQ                                                   : 1
BC                                                    : 1
BDDSampler                                            : 1
BDI                                                   : 43
BDI4JADE                                              : 1
BDL                                                   : 1
BDS                                                   : 1
BDSM                                                  : 4
BEHAVEngine                                           : 2
BEN                                                   : 1
BERT                                                  : 1
BET                                                   : 1
BFA                                                   : 1
BIC                                                   : 2
BIM                                                   : 1
BIPOC                                                 : 1
BIT_CARE                                              : 1
BJS                                                   : 4
BLEU                                                  : 1
BLM                                                   : 3
BME                                                   : 1
BMI                                                   : 1
BMJ                                                   : 4
BOD                                                   : 8
BOID                                                  : 4
BORG                                                  : 1
BPL                                                   : 1
BPS                                                   : 1
BRIDGE                                                : 2
BRMS                                                  : 1
BSPL                                                  : 1
BTL                                                   : 1
BUGGY                                                 : 1
BUILD_IT                                              : 1
BURIDAN                                               : 1
BWCs                                                  : 1
BYU                                                   : 1
BiLAT                                                 : 1
BotW                                                  : 1
C                                                     : 2   : c_lang
CABINS                                                : 1
CAD                                                   : 4
CADET                                                 : 1
CADIA                                                 : 1
CAFnE                                                 : 1
CAH                                                   : 1
CALM                                                  : 1
CAMP_BDI                                              : 1
CAN                                                   : 1
CAR                                                   : 1
CART                                                  : 1
CASE                                                  : 1
CASNET                                                : 3
CAT                                                   : 1
CA_PCG                                                : 1
CArtAgO                                               : 4
CBAC                                                  : 1
CBMS                                                  : 1
CBO                                                   : 1
CBP                                                   : 14
CBR                                                   : 6
CBS                                                   : 1
CBT                                                   : 1
CCA                                                   : 1
CCAL                                                  : 1
CCE                                                   : 1
CCG                                                   : 1
CCL                                                   : 1
CCO                                                   : 1
CCP                                                   : 1
CCPA                                                  : 1
CCRU                                                  : 1
CCRY                                                  : 1
CCTV                                                  : 2
CCalc                                                 : 1   : ccalc
CDC                                                   : 5
CDE                                                   : 1
CEM                                                   : 1
CENTAUR                                               : 3
CEO                                                   : 2
CETI                                                  : 1
CFA                                                   : 1
CFAA                                                  : 4
CFG                                                   : 1
CFGConf                                               : 1
CFGExplorer                                           : 1
CFL                                                   : 1
CFPB                                                  : 1
CGUL                                                  : 1
CHAM                                                  : 1
CHAP                                                  : 1
CHARMS                                                : 1
CHARON                                                : 1
CHAZ                                                  : 1
CHE                                                   : 1
CHI                                                   : 8
CHI2019                                               : 2
CHI2020                                               : 1
CHOP                                                  : 1
CIA                                                   : 6
CIGAR                                                 : 1
CISPA                                                 : 1
CK2                                                   : 1
CL                                                    : 1
CLAIM                                                 : 1
CLARION                                               : 3
CLASP                                                 : 1
CLE                                                   : 1
CLI                                                   : 1   : cli
CLIMB                                                 : 1
CLIPS                                                 : 13
CLOS                                                  : 1
CMA_ES                                                : 1
CMC                                                   : 4
CMOEA                                                 : 1
CMPS                                                  : 1
CMRadar                                               : 1
CMattie                                               : 1
CNBC                                                  : 1
CNC                                                   : 1
CNN                                                   : 1
CO2                                                   : 3
CO2_emmissions                                        : 1
CO3L                                                  : 1
COCO                                                  : 1
COD                                                   : 2
CODA_O                                                : 3
CODE                                                  : 1
COIN                                                  : 7
COINVENT                                              : 1
COM                                                   : 1
COMETA                                                : 1
COMSOC                                                : 1
CONFIG                                                : 1
COOL                                                  : 1
COP26                                                 : 2
COVID-19                                              : 1   : covid_19
CPH                                                   : 1
CPM-GOMS                                              : 1   : CPM_GOMS
CPM_GOMS                                              : 1
CPOCL                                                 : 1
CPPN2GAN                                              : 1
CPR                                                   : 2
CPS                                                   : 1
CPSR                                                  : 1
CPU                                                   : 1
CRDT                                                  : 1
CREW                                                  : 1
CRISPR                                                : 2
CRL                                                   : 1
CRS                                                   : 3
CRT                                                   : 12
CRYSALIS                                              : 1
CRYSTAL_ISLAND                                        : 1   : crystal_island
CS                                                    : 1
CSA                                                   : 1
CSCL                                                  : 2
CSCW                                                  : 43
CSIS                                                  : 2
CSMET                                                 : 1
CSOS                                                  : 1
CSP                                                   : 4
CSPAN                                                 : 1
CSR                                                   : 2
CSS                                                   : 2
CST                                                   : 1
CSWEP                                                 : 1
CTF                                                   : 1
CTL                                                   : 1
CTLK                                                  : 1
CTS                                                   : 1
CURIOUS                                               : 1
CVS                                                   : 2
CYOA                                                  : 2
C_SPAN                                                : 1
CaFe                                                  : 2
CatSAT                                                : 1
CcNav                                                 : 1
Censys                                                : 1
CiF                                                   : 1
Cif_RPG                                               : 1
Cim                                                   : 1
CoAX                                                  : 1
CoCites                                               : 2
CoFi                                                  : 1
CoSMoS                                                : 1
Conv-LSTM                                             : 1   : conv_lstm
Coo-BDI                                               : 1   : Coo_BDI
Coo_BDI                                               : 1
DACA                                                  : 4
DACS                                                  : 2
DAG                                                   : 1
DAGS                                                  : 1   : DAGs
DAGs                                                  : 2
DAI                                                   : 1
DALI                                                  : 3
DALL_E                                                : 1
DAML                                                  : 1
DAMSL                                                 : 3
DAPL                                                  : 1
DAR                                                   : 1
DARPA                                                 : 4
DART                                                  : 1
DARVO                                                 : 2
DASSIE                                                : 1
DAW                                                   : 1
DBMS                                                  : 1
DBR                                                   : 1
DC                                                    : 3
DCGAN                                                 : 1
DDA                                                   : 3
DDE                                                   : 1
DDLA                                                  : 1
DDOS                                                  : 1
DDoS                                                  : 2   : DDOS
DEA                                                   : 9
DECERNS                                               : 1
DEDALUS                                               : 1
DEF                                                   : 1
DEFCON                                                : 2
DEI                                                   : 8
DEIOS                                                 : 1
DEL                                                   : 1
DEMAIS                                                : 1
DEMRAL                                                : 1
DENDRAL                                               : 12
DER                                                   : 1
DERRIC                                                : 1
DESC0004031                                           : 2
DESIRE                                                : 1
DESMON                                                : 1
DETT                                                  : 1
DF_9                                                  : 1
DHS                                                   : 4
DICE                                                  : 1
DIGITEL                                               : 1
DIGMA                                                 : 1
DIGRA                                                 : 1
DINA                                                  : 1
DINO                                                  : 1
DIPMETER_ADVISOR                                      : 1
DIPPER                                                : 1
DIS                                                   : 1
DIY                                                   : 4
DJIA                                                  : 1
DLA                                                   : 1
DLC                                                   : 2
DMCA                                                  : 16
DMV                                                   : 4
DNA                                                   : 14
DND                                                   : 3
DOC                                                   : 1
DODM                                                  : 1
DOI                                                   : 1
DOJ                                                   : 13
DOMA                                                  : 2
DOMAP                                                 : 1
DOME                                                  : 1
DOSS                                                  : 1
DOTA                                                  : 1
DOW                                                   : 1
DPL2019                                               : 1
DPLL                                                  : 1
DPRK                                                  : 1
DQN                                                   : 2
DRC                                                   : 2
DREAM_act                                             : 1
DRM                                                   : 43
DROOLS                                                : 1
DRT                                                   : 1
DReAM                                                 : 1
DS9                                                   : 3
DSL                                                   : 48
DSLR                                                  : 1
DSLs                                                  : 3   : DSL
DSM                                                   : 2
DSML                                                  : 1
DSMLs                                                 : 1
DSMV                                                  : 2
DSP                                                   : 1
DSS                                                   : 1
DTA                                                   : 1
DTMC                                                  : 1
DUP                                                   : 2
DVD                                                   : 1
DWP                                                   : 12
DeLeNoX                                               : 1
DiGRA                                                 : 1
DiPRA                                                 : 1
DiSTiL                                                : 1
DoD                                                   : 1
DvD                                                   : 1
EA                                                    : 1
EAGLE                                                 : 1
EAT                                                   : 1
ECSEST                                                : 1
ECTL                                                  : 1
ED                                                    : 4   : eating_disorders
EDM                                                   : 1
EFF                                                   : 1
EFIGE                                                 : 1
EHA2018                                               : 1
EHCR                                                  : 2
EHRC                                                  : 7
EIDE                                                  : 1
EIS                                                   : 1
EL                                                    : 1
ELAN                                                  : 1
ELECTRE                                               : 2
ELEKTRA                                               : 1
ELI5                                                  : 4
ELIZA                                                 : 2
ELMS                                                  : 2
EMA                                                   : 2
EMAPi                                                 : 1
EMASL                                                 : 1
EMDR                                                  : 1
EMERALD                                               : 1
EMF                                                   : 1
EMI                                                   : 2
EMIL                                                  : 1
EMPath                                                : 2
EMYCIN                                                : 2
ENABL                                                 : 1
ENGO                                                  : 1
ENIAC                                                 : 1
EOP                                                   : 2
EO_9066                                               : 1
EO_9645                                               : 1
EP                                                    : 1
EPA                                                   : 4
EPAM                                                  : 1
EPI                                                   : 1
EP_MAS                                                : 1
ERCOT                                                 : 1
ERGo                                                  : 1
ERISA                                                 : 1
ESA                                                   : 1
ESCHER                                                : 1
ESG                                                   : 1
ESI                                                   : 1
ES_and_S                                              : 2
EShadow                                               : 1
ETH                                                   : 1
EU                                                    : 30
EUCRT                                                 : 1
EXCHECK                                               : 1
EXMAR                                                 : 1
EXPERT                                                : 2
EmiL                                                  : 1   : EMIL
ErgoAI                                                : 2
Expressivator                                         : 1
FAA                                                   : 1
FAIR                                                  : 1
FANs                                                  : 1
FAS                                                   : 1
FAccT                                                 : 1
FAtiMA                                                : 3
FBI                                                   : 12
FCC                                                   : 2
FCM                                                   : 1
FCP                                                   : 1
FDA                                                   : 1
FDG                                                   : 6
FEC                                                   : 2
FEM                                                   : 1
FEMA                                                  : 2
FERC                                                  : 1
FF                                                    : 1
FFI                                                   : 1
FFIPS                                                 : 1
FFREADA                                               : 1
FFT                                                   : 1
FGM                                                   : 1
FHIR                                                  : 2
FICO                                                  : 1
FIPA                                                  : 4
FISA                                                  : 3
FLOW_MATIC                                            : 1
FLUX                                                  : 1
FML                                                   : 1
FOAI                                                  : 1
FODMAP                                                : 1
FOIA                                                  : 13
FORMULA                                               : 1
FORMULA_2                                             : 2
FORTH                                                 : 1
FPS                                                   : 13
FRP                                                   : 2
FSM                                                   : 25  : FSMs
FSMs                                                  : 11
FTA                                                   : 2
FTC                                                   : 1
FatiMA                                                : 1   : FAtiMA
FearNot                                               : 3
FinCEN                                                : 1
FloWr                                                 : 1
G3PARM                                                : 1
GADIN                                                 : 1
GADTs                                                 : 2
GAIA                                                  : 1
GAMA                                                  : 1
GAMBIT                                                : 1
GAME_FORGE                                            : 1   : game_forge
GAMUT                                                 : 1
GAN                                                   : 8
GANSynth                                              : 1
GANs                                                  : 1   : GAN
GAO                                                   : 1
GAR                                                   : 3
GARCH                                                 : 1
GASOL                                                 : 1
GASP                                                  : 2
GC                                                    : 1
GCHMM                                                 : 1
GCM                                                   : 1
GDA                                                   : 2
GDC                                                   : 1
GDC18                                                 : 3
GDC19                                                 : 6
GDP                                                   : 5
GDPR                                                  : 5
GDT4MAS                                               : 1
GEMA                                                  : 1
GESTER                                                : 1
GFSS                                                  : 1
GIMP                                                  : 1
GIS                                                   : 5
GLAAD                                                 : 1
GLIM                                                  : 1
GLIMPSE                                               : 1
GLR                                                   : 1
GLSL                                                  : 2
GLTF                                                  : 1
GM                                                    : 1
GME                                                   : 1
GMM                                                   : 1
GMO                                                   : 2
GM_crops                                              : 1
GNU                                                   : 1
GOAL                                                  : 2
GOAP                                                  : 4
GOFAI                                                 : 1
GOGAR                                                 : 2
GOLEM                                                 : 1
GOLOG                                                 : 1
GOMS                                                  : 7
GOP                                                   : 92
GORMAS                                                : 3
GOSP-MAS                                              : 1   : GOSP_MAS
GOSP_MAS                                              : 1
GPL                                                   : 1
GPS                                                   : 2
GPT_3                                                 : 4
GPU                                                   : 3
GRA                                                   : 1
GRAKN                                                 : 1
GRASP                                                 : 1
GRE                                                   : 2
GRIOT                                                 : 1
GRL                                                   : 2
GReAT                                                 : 1
GSS                                                   : 1
GSTD                                                  : 1
GTA                                                   : 1
GTD                                                   : 1
GTI                                                   : 1
GTP_2                                                 : 1
GUI                                                   : 8
GUIDON                                                : 1
GURPS                                                 : 1
GVGAI                                                 : 1
GWAP                                                  : 1
GaaS                                                  : 1
Gaia                                                  : 3   : GAIA
GrACE                                                 : 1
GrailGM                                               : 2
GraphQL                                               : 1
HACKER                                                : 1
HAI                                                   : 1
HALEF                                                 : 1
HAM                                                   : 1
HAPN                                                  : 1
HARMONIA                                              : 1
HARP                                                  : 1
HBCU                                                  : 1
HBCs                                                  : 2
HCI                                                   : 362
HCI_                                                  : 2
HERA                                                  : 2
HFSM                                                  : 1
HHCR741                                               : 1
HHS                                                   : 4
HIPAA                                                 : 5   : HIPPA
HIPPA                                                 : 1
HIV                                                   : 17
HKB                                                   : 1
HKBS                                                  : 1
HLAI                                                  : 1
HLBL                                                  : 1
HLSL                                                  : 1
HMV                                                   : 1
HMX                                                   : 1
HOL                                                   : 2
HOMAM                                                 : 2
HOOD                                                  : 1
HPV                                                   : 1
HR                                                    : 4
HRA_office                                            : 1
HRT                                                   : 2
HRW                                                   : 1
HSFM                                                  : 1
HSL                                                   : 2
HSLDA                                                 : 1
HSP                                                   : 1
HSPS                                                  : 1
HSV                                                   : 1
HTN                                                   : 4
HTN_planning                                          : 1
HTNs                                                  : 1   : HTN
HUAC                                                  : 1
HUMINT                                                : 1
HactarV2                                              : 1
HearSay_II                                            : 1
HyDICE                                                : 2
HyPED                                                 : 1
IAB                                                   : 2
IABM                                                  : 1   : I_ABM
IAC                                                   : 1
IAD                                                   : 10
IAI                                                   : 1
IBA                                                   : 1
IBM                                                   : 9
IBS                                                   : 1
ICANN                                                 : 2
ICARUS                                                : 1
ICC                                                   : 1
ICCJ                                                  : 1
ICE                                                   : 95
ICIDS                                                 : 1
ICJ                                                   : 1
ICO                                                   : 1
ICRAF                                                 : 1
ICT                                                   : 1
ICU                                                   : 5
ICU_readings                                          : 1
ICUreadingsinterns                                    : 1   : ICU_readings
ICWSM                                                 : 1
IDA                                                   : 1
IDE                                                   : 20
IDEs                                                  : 2   : IDE
IDGEI                                                 : 1
IDL                                                   : 1
IDS                                                   : 1
ID_cards                                              : 1
IDs                                                   : 1   : ID_cards
IDtension                                             : 1
IDtensions                                            : 1   : IDtension
IED                                                   : 1
IEEE                                                  : 3
IEL                                                   : 1
IF                                                    : 4
IFRI                                                  : 1
IGF2017                                               : 1
IGGI18                                                : 1
IGN                                                   : 1
IGU                                                   : 2
IHE                                                   : 1
III_percent_movement                                  : 1
IJCAI                                                 : 1
IK                                                    : 1
ILP                                                   : 2
IMDB                                                  : 2
IMF                                                   : 3
IMMERSE                                               : 3
IMPACT                                                : 1
INGENIAS                                              : 3
INScore                                               : 1
INTERNIST                                             : 4
INTERRAPP                                             : 1
IN_TALE                                               : 1
IOC                                                   : 1
IOSE                                                  : 1
IOT                                                   : 1   : IoT
IO_logic                                              : 5   : input_output_logics
IPA                                                   : 1
IPCC                                                  : 2
IPD                                                   : 4
IPOCL                                                 : 2
IQ                                                    : 1
IQ_tests                                              : 1   : IQ
IRA                                                   : 1
IRB                                                   : 2
IRBs                                                  : 1   : IRB
IRCAM                                                 : 1
IRIS                                                  : 1
IRMA                                                  : 1
IRON                                                  : 1
IRS                                                   : 4
IR_theory                                             : 1
ISA                                                   : 1
ISAAR                                                 : 1
ISADG                                                 : 1
ISIL                                                  : 1   : ISIS
ISIS                                                  : 21
ISLANDER                                              : 8
ISNA                                                  : 1
ISO                                                   : 1
ISP                                                   : 1
ISPAR                                                 : 1
ISS                                                   : 1
IT                                                    : 1
ITS                                                   : 3
ITU                                                   : 3
IVA                                                   : 4
IVF                                                   : 1
I_ABM                                                 : 2
ImGui                                                 : 1   : imgui
InSight                                               : 1
InStaL                                                : 1   : InstaL
InstAL                                                : 7   : InstaL
InstQL                                                : 1
InstaL                                                : 8
IoT                                                   : 2
JACAMO                                                : 1
JACK                                                  : 1
JADE                                                  : 2
JADEX                                                 : 1
JAM                                                   : 1
JAMES                                                 : 1
JANUS                                                 : 1
JASDL                                                 : 1
JASON                                                 : 5
JASSS                                                 : 8
JESS                                                  : 1
JIAC                                                  : 1
JOLENE                                                : 1
JPL                                                   : 1
JRPG                                                  : 3
JSettlers                                             : 1
JaCaMo                                                : 1
Jamocha                                               : 1
Janus                                                 : 1
Jason                                                 : 1
K-IA                                                  : 1
KABUL                                                 : 1
KAOS                                                  : 1
KARMA                                                 : 1
KARO                                                  : 2
KAoS                                                  : 1
KB                                                    : 1
KBS                                                   : 1
KCXL                                                  : 1
KD                                                    : 1
KD45                                                  : 2
KEKADA                                                : 1
KE_system                                             : 2
KGB                                                   : 2
KGP                                                   : 1
KIDS                                                  : 1
KIF                                                   : 1
KILT                                                  : 1
KISS                                                  : 1
KKK                                                   : 20
KL3                                                   : 1
KLEE                                                  : 1
KLMLean                                               : 1
KLMTS_decomposition                                   : 1
KLM_logic                                             : 1
KMP                                                   : 1
KNN                                                   : 1   : kNN
KONRS                                                 : 1
KONT                                                  : 1
KQML                                                  : 1
KT                                                    : 1
Kaboom                                                : 2
KnoRBA                                                : 1
Kodu                                                  : 1
Kongo                                                 : 1
Kyudo                                                 : 1
LA                                                    : 7
LAION-400M                                            : 1
LAN                                                   : 2
LAO                                                   : 2
LAPD                                                  : 3
LARA                                                  : 1
LARP                                                  : 2
LASD                                                  : 1
LA_county                                             : 1
LA_noire                                              : 1
LA_review_of_books                                    : 6
LA_riots                                              : 3
LA_times                                              : 14
LCF                                                   : 1
LDA                                                   : 3
LDFI                                                  : 1
LDS                                                   : 1
LEAP                                                  : 1
LEGIS                                                 : 1
LEGO                                                  : 2
LEGOL                                                 : 1
LF                                                    : 2
LFG                                                   : 1
LGBAlliance                                           : 1
LGBTQ                                                 : 94
LGBTQ_                                                : 1
LGB_Alliance                                          : 1
LGTBQ                                                 : 2
LIAR                                                  : 1
LIBRA                                                 : 1
LIDA                                                  : 1
LIFER                                                 : 1
LIKELIKE                                              : 1   : likelike
LINQ                                                  : 1
LINUS                                                 : 1
LISSA                                                 : 1
LIWC                                                  : 1
LLMs                                                  : 1
LLT                                                   : 1
LL_star                                               : 1
LO                                                    : 1
LOD                                                   : 1
LOD_Trader                                            : 1
LOTR                                                  : 4
LPDModel                                              : 1
LRA                                                   : 1
LSA                                                   : 1
LSD                                                   : 2
LSE                                                   : 4
LSP                                                   : 2
LSTM                                                  : 5
LTBTQ                                                 : 2
LTI_systems                                           : 1
LTL                                                   : 1
LUA                                                   : 1
LULU                                                  : 1
LUNAR                                                 : 1
LVE                                                   : 1
LabVIEW                                               : 1
LinLog                                                : 1
Lyntax                                                : 1
MAAD                                                  : 1
MACBETH                                               : 1
MACNET                                                : 1
MACSDE                                                : 1
MACSYMA                                               : 1
MAD                                                   : 1
MADE                                                  : 1
MADM                                                  : 3
MAGA                                                  : 2
MAGAbomber                                            : 1
MAGMA                                                 : 1
MAGUS                                                 : 1
MAIA                                                  : 3
MAID                                                  : 1
MAJ                                                   : 1
MALM                                                  : 1
MAMID                                                 : 1
MANTA                                                 : 1
MAOP                                                  : 1
MAPC                                                  : 1
MAPL                                                  : 1
MAPSIM                                                : 1
MAP_Elites                                            : 8
MARC21                                                : 1
MARGIE                                                : 1
MARS                                                  : 1
MAS                                                   : 264
MASELTOV                                              : 1
MASFMMS                                               : 1
MASL                                                  : 1
MASON                                                 : 4
MASQ                                                  : 1
MATLAB                                                : 1
MAUDE                                                 : 1
MAUS                                                  : 1
MAUT                                                  : 1
MAXQDA                                                : 1
MBSE                                                  : 1
MCAT                                                  : 1
MCDA                                                  : 4
MCDM                                                  : 9
MCMC                                                  : 1
MCRDR                                                 : 1
MCTS                                                  : 3
MCU                                                   : 1
MD5                                                   : 2
MDA                                                   : 3
MDA. framework                                        : 1   : MDA
MDD                                                   : 1
MDE                                                   : 15
MDLP                                                  : 1
MDMP                                                  : 1
MDN                                                   : 1
MDP                                                   : 1
MDPI                                                  : 1
MDPs                                                  : 1   : MDP
MDSO                                                  : 1
MEDLINE                                               : 1
MENA                                                  : 1
MEP                                                   : 1
METATEM                                               : 1
MFLC                                                  : 1
MGS                                                   : 1
MH17                                                  : 1
MHP                                                   : 3
MI5                                                   : 1
MI6                                                   : 2
MIDI                                                  : 1
MILL1                                                 : 1
MINERVA                                               : 1
MINSTREL                                              : 1
MIPS                                                  : 1
MIRO                                                  : 1
MIRV                                                  : 1
MIT                                                   : 6
MIT_press                                             : 1
MIXTAPE                                               : 1
MI_CC                                                 : 1
MKULTRA                                               : 1
ML                                                    : 2
MLEI                                                  : 1
MMO                                                   : 5
MMOGs                                                 : 1   : MMO
MMORPG                                                : 12
MMORPGS                                               : 1   : MMORPG
MMORPGs                                               : 12  : MMORPG
MMOs                                                  : 10  : MMO
MMR                                                   : 1
MOBA                                                  : 2
MOChA                                                 : 1
MODM                                                  : 1
MODP                                                  : 1
MOISE                                                 : 10
MONAD                                                 : 1
MOO                                                   : 2
MOOCs                                                 : 1
MOSCA                                                 : 1
MOSF                                                  : 1
MOVE9                                                 : 1
MOVE_bombing                                          : 2
MPAA                                                  : 14
MPLP                                                  : 3
MPP                                                   : 1
MPS                                                   : 2   : member_of_parliament
MPs                                                   : 1   : member_of_parliament
MRAs                                                  : 1
MRI                                                   : 1
MRS                                                   : 2
MSC                                                   : 1
MSC2019                                               : 2
MSDO                                                  : 1
MSG                                                   : 1
MSNBC                                                 : 13
MSOS                                                  : 1
MSS                                                   : 1
MTA                                                   : 1
MTBD                                                  : 1
MTCS                                                  : 1
MTG                                                   : 2
MTL                                                   : 1
MTV                                                   : 1
MTurk                                                 : 1
MUC_4                                                 : 1
MUD                                                   : 7
MUDs                                                  : 1   : MUD
MULTIS                                                : 1
MUSA                                                  : 1
MXC                                                   : 1
MYCIN                                                 : 2
M_system                                              : 1
MaNEA                                                 : 2
MaSE                                                  : 1
MetaPRL                                               : 1
Meta_APL                                              : 1
MiMaze                                                : 1
Mimesis                                               : 4   : mimesis
Moise                                                 : 1   : MOISE
MoralDM                                               : 1
MorpheuS                                              : 1
MovMote                                               : 1
MusInk                                                : 1
N3                                                    : 1
NAACP                                                 : 3
NAGPRA                                                : 1
NAISA_effect                                          : 1
NAMS                                                  : 1
NARS                                                  : 1
NASA                                                  : 13
NAT                                                   : 1
NATO                                                  : 1
NATYASASTRA                                           : 1
NAWSA                                                 : 1
NBC                                                   : 15
NBER                                                  : 1
NCII                                                  : 1
NCLB                                                  : 1
NCOBRA                                                : 1
NEA                                                   : 1
NEAT                                                  : 1
NER                                                   : 2
NERO                                                  : 1
NES                                                   : 4
NFL                                                   : 2
NFT                                                   : 8
NFTs                                                  : 17
NGO                                                   : 1
NGOMSL                                                : 1
NGOs                                                  : 1
NHL                                                   : 2
NHS                                                   : 7
NIF                                                   : 1
NIH                                                   : 2
NIMBY                                                 : 6
NIN                                                   : 3
NIPS                                                  : 3
NIST                                                  : 1
NLP                                                   : 141
NLPQ                                                  : 1
NLP_                                                  : 1
NLSY                                                  : 1
NLTK                                                  : 6
NMFD                                                  : 1
NOAA                                                  : 2
NOAH                                                  : 1
NOMAD_200                                             : 1
NOPL                                                  : 1
NORCO                                                 : 3
NPA                                                   : 1
NPC                                                   : 7
NPC_design                                            : 1
NPCs                                                  : 49  : NPC
NPL                                                   : 1
NPM                                                   : 2
NPR                                                   : 24
NP_complete                                           : 1
NP_hard                                               : 1   : np_hard
NRA                                                   : 5
NRCSA                                                 : 1
NRM                                                   : 1
NROL_39                                               : 2
NSA                                                   : 6
NSC                                                   : 1
NSDA                                                  : 1
NSE                                                   : 1
NSF                                                   : 1
NSGA_II                                               : 1
NSM                                                   : 1
NUDGE                                                 : 1
NYC                                                   : 3   : new_york_city
NYPD                                                  : 17
NYT                                                   : 2   : new_york_times
NYU                                                   : 2
NautiLOD                                              : 1
Neo4j                                                 : 1
NeurIPS                                               : 1
NoA                                                   : 1
NoHR                                                  : 1
NoMoDEI                                               : 1
NoSQL                                                 : 1
NorMAS                                                : 1
NuPRL                                                 : 1
O-MaSE                                                : 2   : o_MaSE
O3F                                                   : 1
OAN                                                   : 1
OBDA                                                  : 1
OBELIX                                                : 1
OBJ                                                   : 2
OCR                                                   : 2
OCeAN                                                 : 2
ODD                                                   : 3
ODD_protocol                                          : 2
ODE                                                   : 1
ODIS                                                  : 1
ODMAS                                                 : 1
OIG                                                   : 5
OLAP                                                  : 1
OMACS                                                 : 1
OMI                                                   : 1
OMIA                                                  : 1
OML                                                   : 1
OMNI                                                  : 1
OMeta                                                 : 1
ONS                                                   : 1
OODA                                                  : 1
OOP                                                   : 4
OO_logic                                              : 2
OOjDREW                                               : 1
OPS                                                   : 1
OPS5                                                  : 1
ORA4MAS                                               : 4
ORIENT                                                : 2
OSC                                                   : 1   : osc
OSCAR                                                 : 1
OSEMN                                                 : 1
OSGi                                                  : 1
OSHA                                                  : 1
OSS                                                   : 1
OSX                                                   : 23
OSX_                                                  : 1
OTP                                                   : 1
OWL                                                   : 6
OntoMorph                                             : 1
OperA                                                 : 2
OperettA                                              : 2
OptiML                                                : 1
Osiris                                                : 1
Otello                                                : 1
Oz                                                    : 3
PAC                                                   : 1
PACs                                                  : 1
PAL                                                   : 1
PAM                                                   : 1
PAR                                                   : 2
PARAGon                                               : 1
PARC                                                  : 1
PASHAMAMA                                             : 1
PBS                                                   : 3
PBS_                                                  : 3
PBT                                                   : 1
PCA                                                   : 3
PCB                                                   : 2
PCF                                                   : 1
PCM                                                   : 1
PCMAT                                                 : 1
PDDL                                                  : 3
PDI                                                   : 1
PDL                                                   : 3
PDP                                                   : 1
PDPs                                                  : 1
PDT                                                   : 1
PE                                                    : 1
PECOS                                                 : 1
PECS                                                  : 1
PEG                                                   : 1
PEGI                                                  : 1
PERSONAGE                                             : 1
PES                                                   : 3
PESTLE                                                : 1
PET                                                   : 4
PFAS                                                  : 1
PFLP                                                  : 1
PGH                                                   : 1
PGP                                                   : 1
PHANtom                                               : 1
PIL                                                   : 1
PILOps                                                : 1
PIM                                                   : 13
PIMM                                                  : 1
PIP                                                   : 1
PLANNER                                               : 1
PLASMA                                                : 1
PLATO                                                 : 2
PLL                                                   : 1
PLM                                                   : 1
PLOrk                                                 : 1
POC                                                   : 16
POMDP                                                 : 3
POPL                                                  : 1
POSG                                                  : 1
POSH                                                  : 8
POSH_SHARP                                            : 2
POSL                                                  : 1
PPC                                                   : 1
PPD                                                   : 1
PPE                                                   : 2
PPIG                                                  : 1
PPP_loans                                             : 1
PR                                                    : 1
PREFORMA                                              : 1
PRESTO                                                : 1
PREVENT                                               : 3
PRG                                                   : 1
PRIMER                                                : 1
PRL                                                   : 1
PRM                                                   : 1
PRODIGY                                               : 1
PROMETHEE                                             : 2
PROMETHEUS                                            : 1
PROPEL                                                : 1
PROSE                                                 : 1
PROSPECTOR                                            : 2
PROVA                                                 : 1
PRS                                                   : 5
PSA                                                   : 1
PSI                                                   : 1
PSOA                                                  : 1
PSP                                                   : 1
PSTN                                                  : 1
PTSD                                                  : 10
PUFF                                                  : 2
PaSSAGE                                               : 1
PaaS                                                  : 1
PreSage                                               : 1
Presage2                                              : 1
Prometheus                                            : 4   : PROMETHEUS
Protege                                               : 1   : protege
PsyOps                                                : 1
QA                                                    : 4
QAD                                                   : 1
QAnon                                                 : 3
QCA                                                   : 1
QCL                                                   : 1
QED                                                   : 1
QList                                                 : 1
QOC                                                   : 2
QRCodes                                               : 1
QT                                                    : 3
QUEST                                                 : 1
R                                                     : 1
R1                                                    : 1
RAINN                                                 : 2
RAND                                                  : 1
RASC                                                  : 1
RASCAL                                                : 2
RASE                                                  : 1
RASF                                                  : 1
RASP                                                  : 1
RAST                                                  : 1
RAT                                                   : 1
RBS                                                   : 1
RBox                                                  : 1
RCMP                                                  : 1
RCT                                                   : 1
RCTs                                                  : 1   : RCT
RDA                                                   : 1
RDF                                                   : 1
RDoC                                                  : 1
REACT                                                 : 1
REBECCA                                               : 1
RECALL                                                : 1
REDD                                                  : 1
REINFORCE                                             : 1
REPAGE                                                : 1
REPL                                                  : 1
REST                                                  : 2
RESTORE                                               : 1
RETE                                                  : 1
RETORCH                                               : 1
REVOLT                                                : 1
REWE                                                  : 1
RFC_1                                                 : 1
RFID                                                  : 3
RHO_calculus                                          : 1
RIAA                                                  : 10
RICO                                                  : 1
RIFTS                                                 : 1
RIF_RPD                                               : 1
RISC                                                  : 1
RISLA                                                 : 1
RITA                                                  : 1
RK                                                    : 1
RM3                                                   : 1
ROA                                                   : 1
ROADMAP                                               : 1
ROCIC                                                 : 1
ROS                                                   : 1
ROSI                                                  : 1
RPB                                                   : 1
RPG                                                   : 166
RPGs                                                  : 2   : RPG
RSA                                                   : 1
RSPCA                                                 : 2
RSS                                                   : 1
RSSI                                                  : 1
RST                                                   : 1
RTEC                                                  : 1
RTS                                                   : 9
RUM                                                   : 1
RVML                                                  : 1
Raft                                                  : 1   : raft
Rascal                                                : 2   : RASCAL
ReSkii                                                : 1
ReSpecT                                               : 1
ReTAX                                                 : 1
Reo                                                   : 2   : reo
RofASSS                                               : 1
RuleML                                                : 3
S5                                                    : 2
SAAS                                                  : 1   : SaaS
SACON                                                 : 1
SAFE                                                  : 1
SAFs                                                  : 1
SAGE                                                  : 2
SAI                                                   : 1
SAIBA                                                 : 1
SAIL                                                  : 1
SAIMR                                                 : 1
SALT                                                  : 1
SAM                                                   : 1
SAR                                                   : 1
SARL                                                  : 1
SARSA                                                 : 1
SAT                                                   : 3
SB8                                                   : 2
SBVR                                                  : 1
SCAM                                                  : 1
SCHEHERAZADE                                          : 1
SCHOLAR                                               : 1
SCIFF                                                 : 1
SCOTUS                                                : 56
SCP                                                   : 1
SCPR                                                  : 1
SCXML                                                 : 1
SDK                                                   : 1
SDL                                                   : 1
SDO                                                   : 1
SDS                                                   : 1
SE4AI                                                 : 1
SEC                                                   : 2
SEEDS                                                 : 1
SEIR_model                                            : 1
SEPTA                                                 : 3
SES                                                   : 2
SETI                                                  : 1
SETL                                                  : 1
SF                                                    : 1
SFF                                                   : 1
SFPD                                                  : 1
SF_chronicle                                          : 1
SF_gate                                               : 10
SHACL                                                 : 1
SHARK                                                 : 1
SHINE                                                 : 1
SHRDLU                                                : 2
SHriMP                                                : 1
SIDS                                                  : 1
SIMD                                                  : 1
SIMDEI                                                : 1
SIMON                                                 : 1
SIMPLE                                                : 4
SIP                                                   : 1
SIP agents                                            : 1   : SIP : agents
SISCONFLUX                                            : 1
SIT                                                   : 1
SIXTH                                                 : 1
SJW                                                   : 2
SKAD                                                  : 1
SLAPP                                                 : 1
SLD_resolution                                        : 1
SLO_county                                            : 1
SLR                                                   : 1
SMARTedit                                             : 1
SMDE                                                  : 1
SMT                                                   : 1
SMT_LIB                                               : 3
SMart                                                 : 1
SNAP                                                  : 8
SNES                                                  : 8
SNIF_ACT                                              : 1
SNL                                                   : 1
SNSAT                                                 : 1
SNePS                                                 : 1
SOA                                                   : 1
SOAR                                                  : 10
SOARS                                                 : 1   : SOAR
SOCI                                                  : 1
SOCIONICAL                                            : 1
SOCRATE                                               : 1
SODA                                                  : 1   : SoDA
SOLID                                                 : 1
SOPA                                                  : 1
SOPHIE                                                : 1
SORNA                                                 : 1
SOS                                                   : 1
SOTA                                                  : 1   : state_of_the_art
SOTU                                                  : 1
SPARC                                                 : 1
SPARQL                                                : 1
SPHINX                                                : 1
SPIM                                                  : 1
SPLC                                                  : 2
SPOSH                                                 : 1
SPO_rewriting                                         : 1
SPRING                                                : 1
SPSS                                                  : 1
SQL                                                   : 2
SQUEGE                                                : 1
SRAT                                                  : 1
SRE                                                   : 1
SRI                                                   : 1
SRN_SIC                                               : 1
SRO                                                   : 1
SSA                                                   : 1
SSE                                                   : 1
SSI                                                   : 2
SSL                                                   : 1
SSRI                                                  : 1
STALKER                                               : 1
STATA                                                 : 1
STD                                                   : 3
STEAM                                                 : 1
STEM                                                  : 7
STIT                                                  : 6
STIT_logic                                            : 5
STL                                                   : 1
STRIPS                                                : 5
STS                                                   : 32
STUDENT                                               : 1
SUGILITE                                              : 1
SU_P                                                  : 1
SU_X                                                  : 1
SVD                                                   : 1
SVG                                                   : 1
SVM                                                   : 8
SVR                                                   : 1
SWAT                                                  : 4
SWRL                                                  : 1
SWSD                                                  : 1
SYNAI                                                 : 1
SYNVIEW                                               : 1
SaaS                                                  : 2
SeMoA                                                 : 1
Siren                                                 : 2
Six4Three                                             : 1
SmartRL                                               : 1
SoDA                                                  : 1
SoS                                                   : 1
SocArg                                                : 1
SocLab                                                : 1
TABA                                                  : 1
TABDUAL                                               : 1
TACT                                                  : 1
TAG                                                   : 1   : tree_adjoining_grammar
TAGinator                                             : 1
TAGs                                                  : 1
TAMP                                                  : 1
TANAGRA                                               : 1
TANF                                                  : 1
TARDIS                                                : 1
TAXONS                                                : 1
TB                                                    : 1
TBHW                                                  : 1
TBox                                                  : 1
TBoxes                                                : 1   : TBox
TCL                                                   : 1
TCP                                                   : 1
TCPA                                                  : 1
TEAM                                                  : 1
TEIRESIAS                                             : 2
TEMPO                                                 : 1
TERF                                                  : 20
TERFs                                                 : 3
TFL                                                   : 1
TGGs                                                  : 1
THEO                                                  : 1
THERAC_25                                             : 1
THOMAS                                                : 1
THT                                                   : 1
TI                                                    : 1
TIDSE                                                 : 1
TILDE                                                 : 1
TIS_100                                               : 1
TLA                                                   : 1
TLOU2                                                 : 1
TLS                                                   : 1
TLTS                                                  : 2
TMI                                                   : 1
TMO_framework                                         : 1
TMS                                                   : 3
TNO                                                   : 1
TOAST                                                 : 1
TOGA                                                  : 1
TOM                                                   : 1
TOPLAP                                                : 1
TOPOI                                                 : 1
TOPSIS                                                : 1
TORCS                                                 : 2
TORG                                                  : 2
TO_CHECK                                              : 2
TPC-E                                                 : 1   : TPC_E
TPC_E                                                 : 1
TPM                                                   : 3
TPP                                                   : 5
TPS                                                   : 1
TPTL-BIH                                              : 1   : TPTL_BIH
TPTL_BIH                                              : 1
TRAC                                                  : 2
TRAME                                                 : 1
TREAT                                                 : 1
TRIPS                                                 : 1
TROPOS                                                : 1
TRURL                                                 : 1
TSA                                                   : 2
TSR                                                   : 1
TST                                                   : 1
TTRPG                                                 : 1   : table_top_rpg
TV                                                    : 1   : tv
TVA                                                   : 2
TWP                                                   : 1
T_M_O_framework                                       : 1
Tanagra                                               : 1   : TANAGRA
TransNet                                              : 1
TriG                                                  : 1
TropICAL                                              : 1
TuCSon                                                : 1
UAE                                                   : 1
UAV                                                   : 1
UBF                                                   : 1
UBI                                                   : 1
UCLA                                                  : 1
UCPD                                                  : 1
UCSA                                                  : 1
UCSC                                                  : 2
UC_berkeley                                           : 2
UFO                                                   : 1
UI                                                    : 57
UISF                                                  : 1
UI_                                                   : 1
UK                                                    : 169
UML                                                   : 7
UN                                                    : 11  : united_nations
UNC                                                   : 1
UNCLOS                                                : 1
UNESCO                                                : 2
UNHCR                                                 : 1
UNIVAC                                                : 1
UNIX                                                  : 1   : unix
UNLV                                                  : 1
UN_human_rights                                       : 1   : united_nations : human_rights
UO                                                    : 1   : ultima_online
UPPAAL                                                : 1
UPS                                                   : 3
URR                                                   : 1
US                                                    : 18  : USA
US Government                                         : 1   : US_government
USA                                                   : 343
USA_mexico_border                                     : 1   : US_mexico_border
USCIS                                                 : 1
USDA                                                  : 2
USGS                                                  : 1
USMCA                                                 : 1
USPO                                                  : 1
USPS                                                  : 2
USPTO                                                 : 4
USSR                                                  : 7
USS_Roosevelt                                         : 2
USTR                                                  : 2
US_DOJ                                                : 2
US_Government                                         : 2   : US_government
UTA                                                   : 1
UTAG                                                  : 1
UTC                                                   : 1
UT_Dallas                                             : 1
UV                                                    : 2
UX                                                    : 3
UX_planet                                             : 1
VA                                                    : 1
VAM                                                   : 1
VAS                                                   : 3
VAWA                                                  : 1
VC                                                    : 1
VCS                                                   : 2
VECTOR                                                : 1
VFX                                                   : 1
VGDL                                                  : 1
VHS                                                   : 2
VIATRA                                                : 1
VIRIs                                                 : 1
VLSI                                                  : 1
VM                                                    : 1
VOMAS                                                 : 1
VQR                                                   : 1
VR                                                    : 3
VRA                                                   : 4
VSD                                                   : 1
VTMB                                                  : 3
VVVVVVV                                               : 3
VeTo                                                  : 2
VisiCalc                                              : 1
VoIP                                                  : 1
WADE                                                  : 1
WAIST                                                 : 1
WASM                                                  : 1
WASPs                                                 : 1
WAT                                                   : 1
WAVES                                                 : 1   : waves
WEB                                                   : 1
WEBQUESTIONSSP                                        : 1
WEST                                                  : 1
WHCD                                                  : 1
WHEEZE                                                : 1
WHO                                                   : 2
WHY                                                   : 1
WIPO                                                  : 2
WIZARDABSS                                            : 1
WOC                                                   : 1
WOSPP                                                 : 1
WOZ                                                   : 1
WSJ                                                   : 5
WSM                                                   : 1
WSTS                                                  : 1
WUMPUS                                                : 1
WW1                                                   : 2   : world_war_1
WW2                                                   : 2   : world_war_2
WebDAV                                                : 1
WebDSL                                                : 1
WoW                                                   : 25  : world_of_warcraft
XAI                                                   : 1
XCON                                                  : 2
XCS                                                   : 1
XFT                                                   : 1
XKCD                                                  : 8
XML                                                   : 7
XML_schema                                            : 1
XNA                                                   : 3
XOD                                                   : 1
XPDL                                                  : 1
XSB                                                   : 1
XSB_prolog                                            : 1
XSPEM                                                 : 1
XTAG                                                  : 1
Xtext                                                 : 1
YARN                                                  : 1
YMIR                                                  : 1
YOLO                                                  : 1
ZChaff                                                : 1
_ccdc                                                 : 1
aBUILDER                                              : 1
aaihs                                                 : 1   : AAIHS
acab                                                  : 1   : ACAB
acda                                                  : 1
aclu                                                  : 1   : ACLU
acorn                                                 : 1   : ACORN
adb                                                   : 3
adhd                                                  : 9   : ADHD
adl                                                   : 1
aft                                                   : 1
agdq                                                  : 1
ai                                                    : 781
aids                                                  : 2
aies                                                  : 1   : AIES
aiide                                                 : 3   : AIIDE
aldi                                                  : 1
amw                                                   : 1
arxiv                                                 : 30
asir                                                  : 1
asp                                                   : 12  : ASP
ast                                                   : 3
atm                                                   : 1   : ATM
att                                                   : 2
awk                                                   : 3
aws                                                   : 1
bbai                                                  : 1
bdi                                                   : 2   : BDI
bdsm                                                  : 19  : BDSM
bioNEAT                                               : 1
bmi                                                   : 1   : BMI
bpd                                                   : 1
bpi                                                   : 1
byu                                                   : 1   : BYU
c#                                                    : 1   : c_sharp
c++                                                   : 1   : c_plus_plus
c3                                                    : 2
cPTSD                                                 : 1
cX                                                    : 1
cato                                                  : 9
cbs                                                   : 1   : CBS
ccaqdas                                               : 1
ccbt                                                  : 2   : CBT
ceo                                                   : 2
cfaa                                                  : 3
cfpb                                                  : 1   : CFPB
cfr                                                   : 1
cgNEAT                                                : 1
cgi                                                   : 1
chi                                                   : 2   : CHI
cia                                                   : 7   : CIA
cif                                                   : 2   : CiF
cli                                                   : 24
clips                                                 : 1   : CLIPS
cmu                                                   : 1   : carnegie_mellon_university
cnbc                                                  : 1   : CNBC
cnc                                                   : 1   : CNC
cnet                                                  : 1
cnn                                                   : 25  : CNN
co2                                                   : 3   : CO2
co_op                                                 : 3
cod                                                   : 2   : COD
cointelpro                                            : 1
comp_sci                                              : 8   : computer_science
compsci                                               : 2   : computer_science
coop                                                  : 1
csis                                                  : 2
cspan                                                 : 1   : CSPAN
css                                                   : 15  : CSS
cv                                                    : 1
dACA                                                  : 1   : DACA
d_and_d                                               : 11  : dungeons_and_dragons
d_n_d                                                 : 1   : dungeons_and_dragons
daca                                                  : 1   : DACA
damsl                                                 : 10  : DAMSL
darpa                                                 : 2   : DARPA
dc                                                    : 1   : DC
dea                                                   : 4   : DEA
devarea                                               : 1
devdocs                                               : 1
devops                                                : 2
df-9                                                  : 1   : DF_9
dhs                                                   : 3   : DHS
digra                                                 : 1   : DIGRA
diy                                                   : 4   : DIY
dna                                                   : 1   : DNA
doi                                                   : 1
doj                                                   : 2   : DOJ
dos                                                   : 2
dot_dsl                                               : 1
dota                                                  : 5   : DOTA
dow                                                   : 1   : DOW
dplp                                                  : 1
ds9                                                   : 2   : DS9
dsl                                                   : 2   : DSL
dslr                                                  : 1   : DSLR
dsm5                                                  : 1   : DSMV
dsp                                                   : 5   : DSP
dw                                                    : 1
dwp                                                   : 1   : DWP
eAOP                                                  : 1
eBDI                                                  : 1
e_WOM                                                 : 1
e_books                                               : 1   : ebook
eacl                                                  : 1
easyABMS                                              : 2
ebook                                                 : 24
ecXML                                                 : 1
ed_tech                                               : 1
edith                                                 : 1
edm                                                   : 2   : EDM
edtech                                                : 3   : education_tech
edu_games                                             : 1
eff                                                   : 5
elo                                                   : 1
emt                                                   : 1
epub                                                  : 9
epub3                                                 : 1
erasmatazz                                            : 1
es2015                                                : 1
es6                                                   : 16
evo_bio                                               : 1
evo_psych                                             : 2
ewg                                                   : 1
exif                                                  : 3
expats                                                : 1
fAST                                                  : 1
fMRI                                                  : 1
fbi                                                   : 12  : FBI
fcc                                                   : 1   : FCC
fda                                                   : 1   : FDA
fdg                                                   : 6   : FDG
fft                                                   : 3
fmri                                                  : 1   : fMRI
foia                                                  : 4   : FOIA
ftc                                                   : 1   : FTC
ftl                                                   : 2
ftp                                                   : 1
g7                                                    : 2
gaatw                                                 : 1
gaia                                                  : 2   : GAIA
gao                                                   : 1   : GAO
gba                                                   : 1
gcc                                                   : 1
gcdt_org                                              : 1
gchq                                                  : 1
gdc                                                   : 12  : GDC
gdc19                                                 : 1   : GDC19
gdp                                                   : 3   : GDP
gdpr                                                  : 2   : GDPR
ghc                                                   : 1
ghci                                                  : 1   : ghc
gif                                                   : 13
gifs                                                  : 3   : gif
gimp                                                  : 1
git                                                   : 21
gitmo                                                 : 1
gjson                                                 : 1
glChAoSP                                              : 1
glaad                                                 : 1   : GLAAD
glsl                                                  : 2   : GLSL
glut                                                  : 2
gmo                                                   : 4   : GMO
gns                                                   : 1
gnu                                                   : 21
gnupg                                                 : 8
goms                                                  : 3   : GOMS
gop                                                   : 95  : GOP
gpg                                                   : 3
gps                                                   : 1   : GPS
gpt3                                                  : 1
gpt_2                                                 : 2
gpt_3                                                 : 1
gpu                                                   : 2   : GPU
gq                                                    : 2
grailGM                                               : 1   : GrailGM
gta5                                                  : 1
gtags                                                 : 1
gtk                                                   : 3
gtk2                                                  : 1
h1n1                                                  : 1
h_r_4174                                              : 2
hb_1215                                               : 1
hbo                                                   : 2
hci                                                   : 26  : HCI
hiv                                                   : 4   : HIV
hp                                                    : 1
hpe                                                   : 1
hpoem                                                 : 1
hrt                                                   : 4
hrw                                                   : 1   : HRW
hsb                                                   : 1
hsfm                                                  : 1   : HSFM
hsl                                                   : 2   : HSL
hsv                                                   : 1   : HSV
hud                                                   : 1
iOS                                                   : 7
iTree                                                 : 1
iaddb                                                 : 1
ibm                                                   : 1   : IBM
ice                                                   : 1
ico                                                   : 2   : ICO
ict                                                   : 1   : ICT
ide                                                   : 1   : IDE
ieee                                                  : 1   : IEEE
imgui                                                 : 2
inc                                                   : 1
inews                                                 : 2
influxdb                                              : 1
infoq                                                 : 1
infosec                                               : 2   : information_security
instal                                                : 1
io9                                                   : 107 : io_9
io_9                                                  : 107
io_logic                                              : 10  : input_output_logics
iq                                                    : 3   : IQ
iq_tests                                              : 1   : IQ
isis                                                  : 6   : ISIS
iso                                                   : 1
isp                                                   : 3
istit                                                 : 1
ivf                                                   : 1   : IVF
jacamo                                                : 1   : JaCaMo
jan_6t                                                : 1   : january_6th_insurrection
jan_6th                                               : 3   : january_6th_insurrection
january_6th                                           : 3   : january_6th_insurrection
jason                                                 : 4   : JASON
jasss                                                 : 16  : JASSS
jrpg                                                  : 3   : JRPG
jsdoc                                                 : 1
json                                                  : 17
jstor                                                 : 3
jsx                                                   : 1
jvm                                                   : 1
kNN                                                   : 1   : kNN
karo                                                  : 1   : KARO
kbs                                                   : 1   : KBS
kgb                                                   : 2   : KGB
kkk                                                   : 11  : KKK
kptv                                                  : 1
la                                                    : 2   : LA
larp                                                  : 1   : LARP
latinx                                                : 1
lccrma                                                : 10
lego                                                  : 7   : LEGO
lgbtq                                                 : 35  : LGBTQ
lgtbq                                                 : 1   : LGBTQ
linq                                                  : 1   : LINQ
llvm                                                  : 8
lmtonline                                             : 1
lo_fi                                                 : 1
loaw                                                  : 1
lofi                                                  : 1
log4j                                                 : 4
los_angeles                                           : 10  : LA
lrb                                                   : 1
lse                                                   : 1   : LSE
lsp                                                   : 2
ltac                                                  : 1
ltac2                                                 : 1
lwjgl                                                 : 2
lxml                                                  : 1
mWater                                                : 1
macsyma                                               : 1   : MACSYMA
maia                                                  : 1   : MAIA
mas                                                   : 1   : MAS
matlab                                                : 1   : MATLAB
maxSAT                                                : 1
maxmsp                                                : 1   : max_msp
mbC                                                   : 1
mcu                                                   : 1   : MCU
md5                                                   : 2   : MD5
mda                                                   : 1   : MDA
mdn                                                   : 1   : MDN
mdpi                                                  : 1   : MDPI
mdsp                                                  : 1
memex                                                 : 3
mep                                                   : 1   : MEP
mfa                                                   : 1
mi5                                                   : 1   : MI5
mii                                                   : 7
mime                                                  : 2
minstrel                                              : 1   : MINSTREL
misc                                                  : 2
mit                                                   : 33  : MIT
ml                                                    : 1   : machine_learning
mmo                                                   : 49  : MMO
mmorpg                                                : 3   : MMORPG
mnist                                                 : 2
moba                                                  : 1
moise                                                 : 3   : MOISE
moocs                                                 : 1   : MOOCs
mp                                                    : 2   : member_of_parliament
mps                                                   : 1   : member_of_parliament
mri                                                   : 1   : MRI
ms13                                                  : 1
msg                                                   : 1   : MSG
msnbc                                                 : 11  : MSNBC
mta                                                   : 1   : MTA
mtg                                                   : 1   : MTG
mtv                                                   : 1   : MTV
mu4e                                                  : 1
mud                                                   : 1   : MUD
muds                                                  : 1   : MUD
mutex                                                 : 1
mypy                                                  : 1
nADICO                                                : 3
n_BDI                                                 : 1
n_gram                                                : 3
n_grams                                               : 2   : n_gram
nafta                                                 : 1
nanogenmo                                             : 1
nanwrimo                                              : 1
nasa                                                  : 19  : NASA
natgeo                                                : 1   : national_geographic
natsec                                                : 1   : national_security
nav_mesh                                              : 1
navmesh                                               : 1
nbc                                                   : 15  : NBC
nc9                                                   : 1
ncaa                                                  : 1
ncai                                                  : 1
ncbi                                                  : 9
ncdc                                                  : 8   : CDC
ncsl                                                  : 1
neh                                                   : 1
nes                                                   : 1   : NES
neurIPS                                               : 1
nfl                                                   : 3   : NFL
nhs                                                   : 4   : NHS
nimby                                                 : 2
nin                                                   : 2   : NIN
nine_inch_nails                                       : 1   : NIN
nlp                                                   : 119 : NLP
nlp. utterances                                       : 1   : NLP
nltk                                                  : 1   : NLTK
norMAS                                                : 7
normas                                                : 1   : norMAS
npc                                                   : 10  : NPC
npcs                                                  : 5   : NPC
npm                                                   : 2
npr                                                   : 13  : NPR
nsf                                                   : 1   : NSF
ntyimes                                               : 1   : new_york_times
nyc                                                   : 2
nymag                                                 : 1   : ny_mag
nypd                                                  : 4   : NYPD
nyt                                                   : 5
nytime                                                : 1   : new_york_times
nytimes                                               : 48  : new_york_times
o_MaSE                                                : 1
obgyn                                                 : 1
objc                                                  : 9   : objective_c
ode                                                   : 2   : ODE
ofcom                                                 : 1
ofom                                                  : 1   : ofcom
ogre                                                  : 11
ohchr                                                 : 1   : UN_human_rights
oia                                                   : 1
onExpose                                              : 1
ons                                                   : 1
op_ed                                                 : 1
openPGP                                               : 1   : open_pgp
openai                                                : 4
opencv                                                : 1
opf                                                   : 1
opsec                                                 : 1
osc                                                   : 10
osf                                                   : 1
osx                                                   : 23  : OSX
owl                                                   : 2   : OWL
p-log                                                 : 1   : p_log
p3                                                    : 1
p_hacking                                             : 7
p_k_metric                                            : 1
p_log                                                 : 1
p_np                                                  : 1   : p_vs_np
p_values                                              : 4
p_vs_np                                               : 1
parsl                                                 : 1
pbs                                                   : 1   : PBS
pdf                                                   : 197
pdfrw                                                 : 1
pdftk                                                 : 2
peerj                                                 : 1
pep8                                                  : 2   : pep_8
pep_8                                                 : 1
personage                                             : 1   : PERSONAGE
petro_violence                                        : 1   : TO_CHECK
pew                                                   : 15
pfas                                                  : 1   : PFAS
pfoa                                                  : 1
pfos                                                  : 1
pg&e                                                  : 1   : pg_and_e
pg_and_e                                              : 6
pico8                                                 : 2
pil                                                   : 2   : PIL
pip                                                   : 1
plaidml                                               : 1
plos_one                                              : 2
ply                                                   : 1
pnas                                                  : 1
poc                                                   : 5   : POC
popl                                                  : 1   : POPL
pos                                                   : 1
posh                                                  : 1   : POSH
pow                                                   : 1
pri                                                   : 1
procjam                                               : 1
produsage                                             : 1
prometheus                                            : 4   : PROMETHEUS
prop_8                                                : 1
psx                                                   : 1
psyarxiv                                              : 1
ptsd                                                  : 4   : PTSD
pub_med                                               : 2
py2                                                   : 1
py2exe                                                : 1
py_repr                                               : 1
py_str                                                : 1
pycodestyle                                           : 1
pycon                                                 : 1
pycx                                                  : 1
pycycle                                               : 1
pydot                                                 : 1
pygraphviz                                            : 7
pylint                                                : 1
pymc                                                  : 1
pymc3                                                 : 1
pymupdf                                               : 1
pyo3                                                  : 1
pypi                                                  : 2
pyqt                                                  : 1
pyre                                                  : 2
pyright                                               : 1
pysat                                                 : 1
pyside                                                : 1
pystan                                                : 1
pystm                                                 : 1
pytest                                                : 2
pytq                                                  : 1
q_learning                                            : 7
qanon                                                 : 3   : QAnon
qt                                                    : 3   : QT
quadtrees                                             : 1
queerSTS                                              : 1
qz                                                    : 1
rCOS                                                  : 1
rainn                                                 : 2   : RAINN
rand                                                  : 4   : RAND
rascal                                                : 2   : RASCAL
rdf                                                   : 3   : RDF
rebar3                                                : 1
recSys                                                : 1
recsys                                                : 1
recysys                                               : 1
redis                                                 : 1
regex                                                 : 1   : regexp
regexp                                                : 18
rehab                                                 : 1   : rehabilitation
renpy                                                 : 2
repl                                                  : 1
repo                                                  : 2
rete                                                  : 28  : RETE
rfc                                                   : 1
rgb                                                   : 2
rom                                                   : 1   : roms
roms                                                  : 2
rpg                                                   : 116 : RPG
rpgs                                                  : 46  : RPG
rps                                                   : 4   : rock_paper_shotgun
rss                                                   : 1   : RSS
ruleML                                                : 8   : RuleML
ruleml                                                : 1   : RuleML
sage                                                  : 2
sati                                                  : 1
scheherazade                                          : 2   : SCHEHERAZADE
sci_fi                                                : 115
scifi                                                 : 112 : sci_fi
scikit                                                : 3
scikit_learn                                          : 7
scipy                                                 : 5
scotus                                                : 31  : SCOTUS
scpr                                                  : 1   : SCPR
sdk                                                   : 1   : SDK
sdl                                                   : 3   : SDL
sed                                                   : 2
sex_ed                                                : 1
sfamv                                                 : 3
sfchronicle                                           : 1   : SF_chronicle
sfgate                                                : 10  : SF_gate
shrdlu                                                : 1   : SHRDLU
sim                                                   : 12  : simulation
simpy                                                 : 1
six4three                                             : 1   : Six4Three
sjw                                                   : 1   : SJW
sklearn                                               : 1
smax                                                  : 1
smbc                                                  : 1
smh                                                   : 3
snuff                                                 : 1
snuff_film                                            : 1   : snuff
soaps                                                 : 1   : soap
soar                                                  : 7   : SOAR
soe                                                   : 1
sof                                                   : 1
spec_ops                                              : 3
specs                                                 : 1   : specification
spl                                                   : 1
splc                                                  : 2   : SPLC
spss                                                  : 1   : SPSS
sql                                                   : 15  : SQL
ssl                                                   : 1   : SSL
ssri                                                  : 1   : SSRI
ssrn                                                  : 1
state_machine                                         : 1   : FSMs
state_machines                                        : 3   : FSMs
stit                                                  : 2   : STIT
stit_logic                                            : 5   : STIT_logic
stl                                                   : 1   : STL
sts                                                   : 5   : STS
sty                                                   : 1
supreme_court                                         : 1   : SCOTUS
svd                                                   : 1   : SVD
swat                                                  : 1   : SWAT
swf                                                   : 1
t_test                                                : 1
t_tests                                               : 1   : t_test
tanagra                                               : 1   : TANAGRA
tcf                                                   : 1
tchad                                                 : 1
tcp_ip                                                : 1
td_org                                                : 1
tdd                                                   : 2
ted                                                   : 1
terf                                                  : 1   : TERF
terfs                                                 : 1   : TERF
tf2                                                   : 6
tf_idf                                                : 1
the_OA                                                : 1
therac                                                : 1   : THERAC_25
tikz                                                  : 3
title_42                                              : 1
title_IX                                              : 1
tla                                                   : 1   : TLA
tlmgr                                                 : 2
toml                                                  : 1
tpm                                                   : 3   : TPM
tsa                                                   : 7   : TSA
ttrpg                                                 : 10  : table_top_rpg
tv                                                    : 24
tyt                                                   : 2
u.s.c                                                 : 1   : united_states_code
ucla                                                  : 1   : UCLA
ucsc                                                  : 2   : UCSC
udsa                                                  : 1   : UCSA
ufo                                                   : 3   : UFO
ui                                                    : 73  : UI
uk                                                    : 134 : UK
ukip                                                  : 2
um                                                    : 1
umass                                                 : 1
un                                                    : 2   : united_nations
unc_press                                             : 1
united_kingdom                                        : 5   : UK
urwid                                                 : 1
us                                                    : 11  : USA
usa                                                   : 14  : USA
usb                                                   : 1
uscc                                                  : 1   : US_commission_on_civil_rights
usccr                                                 : 1   : US_commission_on_civil_rights
usgs                                                  : 1   : USGS
usnews                                                : 1   : US_news
uspo                                                  : 1   : USPO
usps                                                  : 1   : USPS
uspto                                                 : 4   : USPTO
ussr                                                  : 1   : USSR
ustr                                                  : 2   : USTR
utf8                                                  : 1
utsnyc                                                : 1
uvs                                                   : 2
ux                                                    : 38  : UX
uxplanet                                              : 1   : UX_planet
va                                                    : 1   : VA
vhdl                                                  : 1
vhs                                                   : 1   : VHS
video_game_description_language                       : 1   : VGDL
violent_action                                        : 1   : TO_CHECK
visa                                                  : 3
viva                                                  : 10
vlsi                                                  : 4
vocab                                                 : 1   : vocabulary
voxdev                                                : 2
vqronline                                             : 6
vr                                                    : 2
vvvv                                                  : 1   : VVVVVVV
vvvvv                                                 : 1   : VVVVVVV
w3                                                    : 3
w3c                                                   : 1
wafb                                                  : 1
wapo                                                  : 52  : washington_post
wasps                                                 : 1   : WASPs
wbez                                                  : 2
wcbs880                                               : 1
wcd_fyi                                               : 1
web2                                                  : 10
web3                                                  : 8
webGL                                                 : 1   : web_GL
web_GL                                                : 10
webgl                                                 : 9   : web_GL
whcd                                                  : 1   : WHCD
who                                                   : 2   : WHO
wifi                                                  : 3
wiki                                                  : 18
wmmna                                                 : 1
woc                                                   : 1   : WOC
wol                                                   : 1
wreg                                                  : 1
wsbt                                                  : 1
wsbtv                                                 : 1
wsj                                                   : 5   : WSJ
wtf                                                   : 1
ww2                                                   : 1   : world_war_2
www                                                   : 1   : web
x11                                                   : 1
xTREE                                                 : 1
x_com                                                 : 14
xcom                                                  : 2   : x_com
xidel                                                 : 2
xkcd                                                  : 8   : XKCD
xml                                                   : 4   : XML
xmlcutty                                              : 1
xmllint                                               : 1
xmp                                                   : 1
xpath                                                 : 5
xsb                                                   : 1   : XSB
xunzi                                                 : 1
y2k                                                   : 2
yale                                                  : 4
yaml                                                  : 2
yarn                                                  : 5   : YARN
ymir                                                  : 1   : YMIR
yup_ik                                                : 1
z3                                                    : 14
