%% insitution subs blah
3M : 1
AAAI : 1
Aalto University : 1
ACLED : 1
ACLU : 1
Acornsoft : 1
Ada Lovelace Institute : 1
Adobe Systems Incorporated : 1
Advocates For Transgender Equality : 1
Aetna Steel Products Corporation : 1
Agency for Urban Environment : 1
AgentLink : 1
AI Now : 1
Air Force Institute of Technology : 1
Akron Commission on Civil Disorders : 1
Albert-Ludwigs University : 1
AMD : 1
American Association for Justice : 1
American Bar Association : 1
American Communities Project, Brown University : 1
American Enterprise Institute : 1
American Psychological Association : 1
APACS : 1
Arizona Secretary of State : 1
Arizona State University : 1
Army Personell Services Group : 1
ASP Standardization Working Group : 1
Australian Artificial Intelligence Institute : 1
Australian Housing and Urban Research Institute, AHURI : 1
Autonomy : 1
B'tselem : 1
Ballarat : 1
Baltimore City Public Schools : 1
Baltimore Police Department : 1
Bath Spa University : 1
BBC : 1
BBN Technologies : 1
Benefit changes and Larger Families : 1
Berggruen Institute : 1
Bethesda Softworks : 1
Bingham Centre For The Rule Of Law : 1
Bipartisan Policy Center : 1
BlueByte : 1
Boeing Scientific Research Labs Seattle : 1
Bolts Magazine : 1
Brennan Center For Justice : 1
Brown University : 1
Bullfrog : 1
Bureau of Justice Statistics : 1
Bureau of Labor Statistics : 1
C4ISR Cooperative Research Program (CCRP) : 1
CAGE : 1
California Task Force to Study and Develop Reparation Proposals for African Americans : 1
Cambridge University : 1
Cambridge-INET Institute : 1
Camera and Imaging Products Association : 1
Cardiff University : 1
Carleton University : 1
Carnegie Mellon University : 1
Cato Institute : 1
CDC : 1
Center for Disease Control, CDC : 1
Center for Economic Studies, U.S. Census Bureau : 1
Center for Strategic \& International Studies, CSIS : 1
Center On Budget and Policy Priorities : 1
Central Digital and Data Officce : 1
Central European University : 1
Centre for International Governance Innovation : 1
CESifo : 1
Charles University : 1
Chemical Weapons Research Consortium : 1
Child Poverty Action Group : 1
CIA : 1
City of Baltimore : 1
City of Chicago : 1
City of Chicago, Office of Inspector General : 1
City of Philadelphia : 1
City University of New York : 1
Civic Laboratory for Environmental Action Research, Memorial University of Newfoundland and Labrador : 1
Colby University : 1
Columbia University : 1
Comittee on Science and Technology, US House of Representatives : 1
Committee on Oversight and Reform : 1
Common Core State Standards Initiative : 1
Commons Network : 1
Computer History Museum : 1
Computer Science Dept., University of Illinois at Urbana-Champaign : 1
Computer Science Dept., University of Illinois at Urbana-Champaign : 1 : University of Illinois at Urbana-Champaign
Concordia University : 1
Congressional Budget Office : 1
Congressional Research Service : 1
Connecticut Office of the Child Advocate : 1
Connecticut Racial Profiling Prohibition Project : 1
Conservative Party : 1
Conservative Way Forward : 1
Conventional Commits : 1
Copenhagen Consensus Center : 1
Cornell University : 1
Council of Europe Annual Penal Statistics: Prison populations : 1
Council of the City of New York : 1
Counter Extremism Project : 1
Court of Appeal, Criminal Division : 1
Cybersecurity & Infrastructure Security Agency (CISA) : 1
Czech Technical University in Prague : 1
Darmstadt University of Technology : 1
Data \& Society : 1
de Technische Universiteit Delft : 1
de Universiteit van Amsterdam : 1
DeepMind : 1
Defend Public Science : 1
Delft University of Technology : 1
Democratic National Convention : 1
Department for Environment, Food and Rural Affairs : 1
Department for Exiting the European Union : 1
Department for Work and Pensions : 1
Department of Computer Science, University of Bath : 1
Department of Computer Science, University of Bath, UK : 1
Department of Economics and Business, Universitat Pompeu Fabra : 1
Department of Education : 1
Department of Housing and Urban Development, Office of Inspector General : 1
Digital Equipment Corporation : 1
Duke Sanford World Food Policy Center : 1
Duke University : 1
Durham University : 1
Dutch Research School for Information and Knowledge Systems : 1
Economic Development & Institutions : 1
Edinburgh                                                          : 1 : Edinburgh University
Edmond J. Safra Center for Ethics : 1
EDSK : 1
Electronic Arts : 1
Electronic Privacy Information Center : 1
Elevate Children Funders Group : 1
Embassy of the Republic of South Africa : 1
Ember Energy : 1
Embracer Group : 1
English Rural Housing Association : 1
ETH Zürich : 1
Eurogamer : 1
European Centre for International Political Economy (ECIPE) : 1
European Commission : 1
Executive Office of the President of USA : 1
Failbetter Games : 1
Fakultät für Mathematik, Informatik und Naturwissenschaften : 1
FBI : 1
Federal Elections Commission : 1
Federal Energy Regulatory Commission : 1
Federal Reserve Bank of Chicago : 1
FIPA : 1
Florida State University : 1
For Humanity : 1
Foreign Policy : 1
French Independent Commission on Sexual Abuse in the Catholic Church : 1
Fulton County Superior Court : 1
Fundação Getulio Vargas Law School at São Paulo : 1
Future of Humanity Institute, University of Oxford, Centre for the Study of Existential Risk, University of Cambridge, Center for a New American Security, Electronic Frontier Foundation, and OpenAI : 1
GCHQ : 1
George Senate Judiciary Committee : 1
Georgia Institute of Technology : 1
Georgia Secretary of State : 1
Georgia State University : 1
Global Change Institute : 1
GNU : 1
Goldman Sachs : 1
Goldsmiths, University of London : 1
Google : 1
Gothenburg University : 1
Government Accountability Office : 1
Government Office for Science : 1
Graduate Theological Union : 1
Grove City College : 1
Guidepost Solutions : 1
Göteborg University : 1
Harvard Business School : 1
Harvard University : 1
Hasler Foundation : 1
Hillsdale College : 1
House of Lords, Communications and Digital Select Committee Inquiry: Large Language Models : 1
House of Representatives : 1
Human Rights Campaign : 1
Human Rights Campaign and The American College of Osteopathic Pediatricians : 1
Human Rights Watch : 1
Hunton and Williams LLP : 1
ICA : 1
id software : 1
IETF : 1
Imperial College London : 1
imperial college london : 1
Imperial College London, UK : 1
Independent Commission On The Los Angelese Police Department : 1
Independent Inquiry into Child Sexual Abuse : 1
Indiana University : 1
Infocom : 1
INRIA : 1
Insight Center for Community Economic Development : 1
Institut National De Recherche En Informatique Et En Automatique, INRIA : 1
Institute for Advanced Study of Human Sexuality : 1
Institute for Communication Technologies : 1
Institute for Fiscal Studies : 1
Institute for Government : 1
Institute for Human and Machine Cognition : 1
Institute for Informatics, University of Potsdam : 1
Institute for Integrated and Intelligent Systems : 1
Institute for Justice : 1
Institute for Policy Studies : 1
Institute for Programming Research and Algorithmics : 1
Institute of Land Warfare : 1
Institute of Network Cultures : 1
Institution for Fiscal Studies : 1
Integrated Resources Working Group : 1
Intel : 1
Intergovernmental Panel on Climate Change (IPCC) : 1
International Association of Chiefs of Police : 1
International Centre for Counter-Terrorism : 1
International Forestry Resources and Institutions, IFRI : 1
International ISBN Agency : 1
International Rice Research Institute : 1
Interplay Entertainment : 1
Ion Storm : 1
Ipsos MORI rseearch for OFCOM : 1
Irish Government : 1
IT University of Copenhagen : 1
IZA Institute of Labor Economics : 1
JAMK University of Applied Sciences : 1
Johns Hopkins University : 1
Joint Committee on Taxation : 1
Kansas State University : 1
Karlsruhe Institute of Technology : 1
Kensington Labour : 1
King's College London : 1
KTH Royal Institute of Technology : 1
La Comisión para el Esclarecimiento de la Verdad, la Convivencia y la No Repetición : 1
Lapland University of Applied Sciences : 1
Law Commission of England & Wales, Scottish Law Commission. : 1
Lemkin Institute for Genocide Prevention : 1
Lift Louisiana : 1
London School of Economics : 1
Lorraine University : 1
Louisiana State University and Agricultural and Mechanical College : 1
LucasArts Entertainment : 1
Malmö University : 1
Maryland Department of Budget and Management : 1
Maryland Office of the Attorney General : 1
Maryland Office of the Public Defender : 1
Massachusetts Amherst : 1
Massachusetts Institute Of Technology                              : 1
Massachusetts Institute of Technology                              : 1 : Massachusetts Institute Of Technology
Massachusetts Institute of Technology : 1
Massachusetts Institute of Technology, Cambridge, MA, USA : 1
Maxis Software : 1
Metropolitan Police : 1
MicroProse, Inc                                                    : 1
Microprose, Inc                                                    : 1 : MicroProse, Inc
MicroProse, Inc : 1
Microsoft : 1
Microsoft Research : 1
Mikroelektronik och informationsteknik : 1
Military Police Complaints Commision of Canada : 1
Ministry of Electricity and Water, Kuwait City, Kuwait : 1
Minnesota Department of Human Rights : 1
Missouri Community Action : 1
MIT                                                                : 1 : Massachusetts Institute Of Technology
MIT : 1
MIT Center for Collective Intelligence : 1
MIT, Department of EECS : 1
MIT, Goodwin Proctor LLC. : 1
Montana State University : 1
NASA : 1
NASA Ames Research Center : 1
National Academies of Sciences, Engineering, and Medicine : 1
National Association for the Advancement of Colored People : 1
National Bureau of Economic Research, NBER : 1
National Congress Of American Indians : 1
National Disability Rights Network : 1
National Education Policy Center : 1
National Executive Committee of the Labour Party : 1
National Food Institute, Technical University of Denmark : 1
National Immigrant Justice Center : 1
National Registry of Exonerations : 1
National Security Commission on Artificial Intelligence : 1
National University of Singapore : 1
NATO Science and Technology Organization : 1
Neurodiversity in Business : 1
New World Computing : 1
New York City Comptroller : 1
New York City Department of Transportation : 1
New York Police Department : 1
New York State Task Force on Maternal Mortality and Disparate Racial Outcomes : 1
New York University : 1
Nielsen Norman Group : 1
Nijmegen Institute for Computing and Information Sciences : 1
Nintendo of America, Inc : 1
No Left Turn : 1
Nokia Research Center : 1
NORC at the University of Chicago : 1
North Carolina State University : 1
Northwestern University : 1
Norwegian University of Science and Technology : 1
NTNU : 1
Obsidian : 1
OFCOM : 1
Office of Budget Responsibility : 1
Office of Inspector General : 1
Office of Inspector General, United States Department of State : 1
Office of Management and Budget : 1
Office of National Statistics : 1
Office of the Inspector General : 1
Ohio House of Representatives : 1
Ohio State University : 1
Open Source Security Foundation : 1
OpenAI : 1
Oracle America, Inc : 1
Oregon Graduate Institute of Science and Technology : 1
Palestine Liberation Organization : 1
Palestinian Centre For Human Rights : 1
Palo Alto Research Center : 1
Paradox Interactive : 1
PeerJ Preprints : 1
Penn State : 1
Pew Research : 1
Philips Exeter Academy : 1
Physicians For Human Rights : 1
Police Executive Research Forum : 1
Policing Research : 1
Policy Exchange : 1
Princeton University : 1
Princeton University, NJ, USA : 1
Project Horseshoe : 1
ProPublica : 1
ProPublica and Northeast Mississippi Dailly Journal : 1
Public Citizen : 1
PWC : 1
Python Steering Council : 1
Queen Mary University of London : 1
Queen's University, Canada : 1
R Street Institute : 1
RAND Corporation : 1
Rare Games Ltd : 1
Raytheon BBN Technologies : 1
Red Hat : 1
Republican National Committee : 1
Rice University : 1
RMIT University : 1
Rock Paper Shotgun : 1
Rocky Mountain Institute : 1
Royal College of Art : 1
Royal Institute of Technology, Sweden : 1
Said Business School : 1
San Diego State University : 1
San José State University : 1
Santa Fe Institute : 1
Save the Children : 1
Sax Insitute : 1
Science Research Council : 1
Seattle University : 1
Sega : 1
Select Committee to Investigate the January 6th Attack on the United States Capitol : 1
Senate : 1
Sex Matters : 1
Sierra On-Line                                                     : 1
Sierra On-line                                                     : 1 :  Sierra On-Line
Sierra On-Line : 1
SIKS, the Dutch Research School for Information and Knowledge Systems. : 1
Simons University : 1
Smithsonian Institution : 1
SOAR : 1
Society of Family Planning : 1
Software Freedom Conservancy : 1
South-Eastern Finland University of Applied Sciences : 1
Southern Poverty Law Center : 1
SPARC International : 1
SRC : 1
SRI : 1
St. Thomas University : 1
Stanford University : 1
State of California Department of Justice, Office of the Attorney General : 1
State of New York Office of The Inspector General : 1
State of New York Office of the Inspector General : 1
stateof.ai : 1
Stockholm University : 1
Stop LAPD Spying Coalition : 1
StopCVE : 1
Supreme Court of Texas : 1
Supreme Court Of The United States : 1
Supreme Court of the United States : 1
Tampere University : 1
Task Force On Aiding & Abetting Felony Murder : 1
Technical University of Ilmenau : 1
Technische Universität München Institut Für Informatik : 1
Tennessee Valley Authority : 1
Texas A\&M University : 1
Texas Civil Rights Project : 1
Texas House of Representatives : 1
Texas Indigent Defense Commission : 1
The Associated Press : 1
The Brookings Institution : 1
The Center for Democracy and Technology : 1
The Century Foundation : 1
The Court of Justice of the European Union : 1
The European Network for the Advancement of Artificial Cognitive Systems : 1
The Green Party : 1
The Heritage Foundation : 1
The Home Office : 1
The House Of Commons Library : 1
The Initiative for Indigenous Futures and the Canadian Institute for Advanced Research, CIFAR : 1
The Interntional Organization for Standardization : 1
The Israel Project : 1
The LaTeX Project : 1
The Leadership Conference Education Fund : 1
The Ministry of Justice : 1
The Muslim Council of Britain : 1
The Navajo Nation: Office of the President and Vice President : 1
The Oklahoma Republican Party : 1
The Open University : 1
The President's Advisory 1776 Commisson : 1
The Republican Party : 1
The Republican Party of Texas : 1
The Republican Study Committee : 1
The Savannah College of Art and Design : 1
The Standish Group : 1
The Teaching Company : 1
The Vatican : 1
The White House : 1
The Yellowhead Institute : 1
Tilburg University : 1
TransActual : 1
TU Delft : 1
TU Wien : 1
Tufts University : 1
TUG Working Group on a TeX Directory Structure : 1
U.K Department For Education : 1
U.K Department of Work & Pensions : 1
U.S Army War College : 1
U.S Citizenship and Immigration Services : 1
U.S Commission on Civil Rights : 1
U.S Court of Appeals for The Eighth Circuit : 1
U.S Court of Appeals for The Eleventh Circuit : 1
U.S Court of Appeals for The Fifth Circuit : 1
U.S Court of Appeals for The Fourth Circuit : 1
U.S Court of Appeals for The Ninth Circuit : 1
U.S Court of Appeals for The Second Circuit : 1
U.S Court of Appeals for The Sixth Circuit : 1
U.S Customs and Border Protection : 1
U.S Department of Commerce, Bureau of the Census : 1
U.S Department of Defense : 1
U.S Department of Health and Human Services : 1
U.S Department of Health and Human Services, Children's Bureau : 1
U.S Department Of Health and Human Services, Office Of Inspector General : 1
U.S Department of Homeland Security : 1
U.S Department of Justice : 1
U.S Department of Justice, Drug Enforcement Administration : 1
U.S Department of State : 1
U.S Department of State, Office of Inspector General : 1
U.S Department of the Army : 1
U.S Department of the Interior : 1
U.S Department of Veterans Affairs : 1
U.S District Court for The District Of Columbia : 1
U.S District Court for The District of Columbia : 1
U.S District Court for The Eastern District of Louisiana : 1
U.S District Court for The Eastern Division of Arkansas, Central Division : 1
U.S District Court for The Middle District of Pennsylvania : 1
U.S District Court for The Northern District of Alabama, Southern Division : 1
U.S District Court for The Northern District of Florida, Tallahassee Division : 1
U.S District Court for The Northern District of Georgia, Atlanta Division : 1
U.S District Court for The Southern District of Florida : 1
U.S District Court for The Southern District of Mississippi : 1
U.S District Court for The Western District of Louisiana, Monroe Division : 1
U.S District Court for The Western District of Washington : 1
U.S District Court of Travis Country, Texas : 1
U.S District Court Western District of Kentucky Lousiville Division : 1
U.S District Court, Northern District of California : 1
U.S Global Change Research Program : 1
U.S House of Representatives, Committee on the Judiciary : 1
U.S House of Representatives, Judiciary Committee : 1
U.S Marine Corps : 1
U.S Office Of Special Counsel : 1
U.S Office of Special Counsel : 1
U.S Senate : 1
U.S Senate Committee on Commerce, Science and Transportation : 1
U.S Senate Committee on The Judiciary : 1
U.S. Global Change Research Program : 1
UC San Diego : 1
ucla : 1
UCSF Benioff Homelessness and Housing Initiative : 1
UIR : 1
UK High Court : 1
UK Home Office : 1
UK House of Commons : 1
UK in a Changing Europe : 1
UK Parliament : 1
Umea University : 1
UNESCO : 1
United Nations : 1
United Nations Institute for Disarmament Research : 1
United States Army Command and General Staff College               : 1 :  U.S Army Command and General Staff College
United States Army Command and General Staff College : 1
United States Civil Defense : 1
United States Department of Commerce : 1
United States Department of Justice : 1
United States Department of the Army                               : 1 :  U.S Department of the Army
United States Department of the Army : 1
United States Department Of The Interior: Bureau Of Indian Affairs : 1
United States Department of the Interior: Bureau of Indian Affairs : 1
United States Federal Government : 1
Univeristy of Bristol : 1
UNIVERSIDAD POLITECNICA DE VALENCIA : 1
Universidade Federal de Santa Catarina : 1
Universidade Técnica de Lisboa : 1
Universitat Politècnica de Catalunya : 1
Universitat Politècnica de València : 1
University and College Union : 1
University College Dublin : 1
University College London : 1
University College London, UK : 1
University Lyon I - Claude Bernard : 1
University Network For Human Rights : 1
University of Aarhaus : 1
University of Abertay Dundee : 1
University of Alberta : 1
University of Amsterdam : 1
University of Applied Sciences Technikum Wien : 1
University of Applied Sciences, Haaga-Helia : 1
University of Arizona : 1
University of Barcelona : 1
University of Bath : 1
University of Bath : 1
University of Bath, Department of Computer Science : 1
University of Bath, Somerset, UK : 1
University of Bayreuth : 1
University of Bern : 1
University of Birmingham : 1
University of Bonn and University of Mannheim : 1
University of Brescia : 1
University of British Columbia : 1
University of Calgary : 1
University of California, Berkeley : 1
University of California, Irvine : 1
University of California, Los Angeles : 1
University of California, San Francisco : 1
University of California, Santa Cruz : 1
University of California, Santa Cruz, UCSC : 1
University of Canterberry : 1
University of Central Florida : 1
University of Chicago : 1
University of Colorado : 1
University of Colorado at Colorado Springs : 1
University of Delaware : 1
University of Derby : 1
University of Dublin, Trinity College : 1
University of Durham : 1
University of Eastern Finland : 1
University of Edinburgh : 1
University of Edinburgh : 1
University of Freiburg : 1
University of Gothenburg : 1
University of Groningen : 1
University of Hamburg, Germany : 1
University of Hawa'i at Mānoa : 1
University of Helsinki : 1
University of Houston : 1
University of Illinois at Urbana-Champaign : 1
University of Kansas : 1
University of Limburg : 1
University of London : 1
University of Maryland : 1
University of Massachusetts : 1
University of Massachusetts Amherst : 1
University of Melbourne : 1
University of Michigan : 1
University of Montana : 1
University of Nevada : 1
University of North Texas : 1
University of Osijek : 1
University of Oslo : 1
University of Otago, Dunedin, New Zealand : 1
University of Oxford : 1
University of Paisley : 1
University of Pennsylvania : 1
University of Portsmouth : 1
University of Potsdam : 1
University of Pretoria : 1
University of Queensland : 1
University of Rochester : 1
University of Sheffield : 1
University of Skövde : 1
University of Southampton : 1
University of Southern California : 1
University of Sussex : 1
University of Sydney : 1
University of Tampere : 1
University of Tartu : 1
University of Tasmania : 1
University of Texas at Austin : 1
University of Toronto : 1
University of Utah : 1
University of Virginia School of Law : 1
University of Washington : 1
University of Western Ontario : 1
University of York : 1
University of Zagreb : 1
Universitá di Torino : 1
Université Du Québec à Montréal : 1
Univertät Tübingen : 1
Uppsala Universitet : 1
Upturn: Towards Justice in Technology : 1
Urban-Greater DC : 1
US Census Bureau                                                   : 1 :  U.S Census Bureau
US Census Bureau : 1
US Court of Appeals for the Fifth Circuit : 1
US Department of Commerce, Bureau of the Census                    : 1 :  U.S Department of Commerce, Bureau of the Census
US Department of Justice                                           : 1 :  U.S Department of Justice
US Department of Justice, Drug Enforcement Administration          : 1 :  U.S Department of Justice, Drug Enforcement Administration
US Department of Veterans Affairs                                  : 1 :  U.S Department of Veterans Affairs
US Election Assistance Commission                                  : 1 :  U.S Election Assistance Commission
US Election Assistance Commission : 1
US Geological Survey                                               : 1 :  U.S Geological Survey
US Geological Survey : 1
US House of Representatives : 1
US House Of Representatives, Energy & Commerce Committee : 1
US House of Representatives: House Permanent Select Committee on Intelligence : 1
US Immigration and Customs Enforcement : 1
US Senate : 1
US Senate Judiciary Committee, Majority : 1
US Sentencing Commission : 1
US Strategic Command                                               : 1 :  U.S Strategic Command
US Strategic Command : 1
US Surgeon General : 1
US White House : 1
USC Suzanne Dworak-Peck School of Social Work : 1
USDA : 1
Utah State House of Representatives : 1
Utrecht University : 1
Utrecht University, Netherlands : 1
Virginia Commonwealth University : 1
Virginia Polytechnic Institute and State University : 1
Virginia Tech : 1
W3c : 1
Washington Center for Equitable Growth : 1
Washington Post : 1
Washington State House of Representatives : 1
Wells Fargo : 1
WikiBooks : 1
Women's Justice Institute : 1
Woodrow Wilson School of Public and International Affairs, Princeton University : 1
Working Paper : 1
World Bank : 1
World Health Organization : 1
Worth Rises : 1
Yale                                                               : 1 :  Yale University
Yale Center for Computational Vision and Control : 1
Yale University : 1
Åbo Akademi University : 1
