%% use : for sep
A sense of place. The global and the local in mobile communication : 1
AAAI : 1
Academia.Edu : 1
Academic freedom in the modern British university: a historical perspective : 1
Academy Of Management                                                           : 1
Academy Of Management Annals                                                    : 1
Academy of Management Journal : 1
Academy of Management Perspectives : 1
Academy of Management Review : 1
Accountability in research : 1
Accounting Historians Journal : 1
ACM : 1
ACM Comput. Surv. : 1
ACM Comput. Surv. : 1 : ACM Computing Surveys
ACM Computers in Entertainment : 1
ACM Computing Surveys                                                           : 1 :  ACM Computing Surveys, CSUR
ACM Computing Surveys (CSUR)                                                    : 1
ACM Computing Surveys, CSUR : 1
ACM Crossroads : 1 
ACM Queue : 1
ACM Sigaccess Accessibility & Computing                                         : 1
ACM SIGACCESS Accessibility and Computing : 1
ACM Sigact News                                                                 : 1
ACM SIGACT News : 1
ACM SIGCHI Bull. : 1 : ACM SIGCHI Bulletin
ACM SIGCSE Bulletin : 1
ACM SIGDA Newsletter : 1
ACM SIGecom Exchanges : 1
ACM SIGGROUP Bulletin : 1
ACM SIGMOBILE Mob. Comput. Commun. Rev. : 1
ACM SIGMOD Record : 1
ACM SIGOIS Bulletin : 1
ACM SIGOPS Operating Systems Review : 1
ACM SIGPLAN Lisp Pointers : 1
ACM SIGPLAN Notices : 1
ACM SIGSOFT Softw. Eng. Notes : 1 : AMC SIGSOFT Software Engineering Notes
ACM SIGSOFT Software Engineering Notes : 1
ACM Trans. Auton. Adapt. Syst. : 1 : ACM Transactions on Autonomous and Adaptive Systems
ACM Trans. Comput. Educ. : 1 : ACM Transactions on Computing Education
ACM Trans. Comput. Hum. Interact. : 1 : ACM Transactions on Computer-Human Interaction
ACM Trans. Comput. Log. : 1 : ACM Transactions on Computational Logic
ACM Trans. Comput. Syst. : 1 : ACM Transactions on Computer Systems
ACM Trans. Graph. : 1 : ACM Transactions on Graphics
ACM Trans. Inf. Syst. : 1 : ACM Transactions on Information Systems
ACM Trans. Inf. Syst. Secur. : 1 : ACM Transactions on Information and System Security
ACM Trans. Intell. Syst. Technol. : 1 : ACM Transactions on Intelligent Systems and Technology
ACM Trans. Internet Techn. : 1 : ACM Transactions on Internet Technology
ACM Trans. Manag. Inf. Syst. : 1 : ACM Transactions on Management Information Systems
ACM Trans. Model. Comput. Simul. : 1 : ACM Transactions on Modeling and Computer Simulation
ACM Transactions of Modeling and Computer Simulation : 1
ACM Transactions On Autonomous & Adaptive Systems                               : 1
ACM Transactions on Autonomous and Adaptive Systems : 1 
ACM Transactions On Computational Logic                                         : 1
ACM Transactions on Computer-Human Interaction (TOCHI'03)                       : 1 : ACM Transactions on Computer-Human Interaction (TOCHI)
ACM Transactions On Computer-Human Interaction (TOCHI)                          : 1
ACM Transactions on Computer-Human Interaction, TOCHI : 1
ACM Transactions on Computing Education : 1
ACM Transactions on Database Systems : 1
ACM Transactions On Graphics                                                    : 1
ACM Transactions On Information Systems (TOIS)                                  : 1
ACM Transactions on Information Systems, TOIS : 1
ACM Transactions on Intelligent Systems and Technology : 1
ACM Transactions On Internet Technology (TOIT)                                  : 1
ACM Transactions on Internet Technology (TOIT) : 1
ACM Transactions On Multimedia Computing, Communications, & Applications (TOMM) : 1
ACM Transactions on Multimedia Computing, Communications, and Applications (TOMM) : 1
ACM Transactions On Office Information Systems                                  : 1
ACM Transactions on Office Information Systems : 1
ACM Transactions On Programming                                                 : 1
ACM Transactions On Programming Languages & Systems                             : 1
ACM Transactions on Programming Languages and Systems : 1
ACS Catalysis : 1
Acta Horticulturae : 1
Acta Naturae : 1
Ad Hoc Networks : 1
Adapt. Behav. : 1 : Adaptive Behavior
Adaptive Behavior : 1
Addiction : 1
Administration & Society : 1
Administrative Science Quarterly : 1
Administrative Sciences : 1
Adv. Complex Syst. : 1 : Advances in Complex Systems
Advanced Functional Programming : 1
Advanced Robotics : 1
Advanced Seminar on Logics and Models for Verification and Specification of Concurrent Systems : 1
Advances in Artificial Intelligence : 1
Advances in Artificial Life : 1
Advances in Developing Human Resources : 1
Advances in Methods and Practices in Psychological Science : 1
Advances in Neurodevelopmental Disorders : 1
Advances in Simulation : 1
AEA Papers and Proceedings : 1
Aether: The Journal of Media Geography : 1
African Journal of Business Management : 1
Afro-Latin American Religious Expressions and Representations Representaciones y expresiones religiosas afrolatinoamericanas : 1
Afterall: A Journal of Art, Context and Enquiry : 1
Agent Autonomy : 1
Agent-Based Social Systems : 1
Agent-Oriented Software Engineering : 1
AHURI Final Report : 1
AI \& Society : 1
AI and Ethics : 1
AI Commun. : 1 : AI Communications
Ai Communications                                                               : 1 : AI Communications
AI Communications : 1
AI Ethics : 1
AI Mag. : 1 : AI Mag.
AI Magazine                                                                     : 1
AI magazine                                                                     : 1 : AI Magazine
AI Magazine : 1
AI Matters : 1
AI Soc. : 1 : AI Society
Alabama Civil Rights and Civil Liberties Law Review : 1
Alabama Law Review : 1
Alberta Journal of Educational Research : 1
Aloma: Revista de Psicologia, Ciències de l'Educació i de l'Esport : 1
AlterNative : 1
Am. Math. Mon. : 1 : The American Mathematical Monthly
American Anthropologist : 1
American Anthropologist,                                                        : 1 : American Anthropologist
American behavioral scientist                                                   : 1 : American Behavioral Scientist
American Behavioral Scientist : 1
American Criminal Law Review : 1
American Economic Association Conference : 1
American Economic Journal: Applied Economics : 1
American Economic Journal: Economic Policy : 1
American Economic Journal: Microeconomics : 1
American Economic Review : 1
American Economic Review: Insights : 1
American Ethnologist : 1
American Immigration Council : 1
American Journal of Epidemiology : 1
American Journal of Physiology Regulatory, Integrative and Comparative Physiology : 1
American Journal of Political Science : 1
American Journal of Preventive Medicine : 1
American Journal of Psychiatry : 1
American Journal of Public Health : 1
American Journal of Sociology : 1
American Literature : 1
American Political Science Review : 1
American Politics Quarterly : 1
American Psychologist : 1
American Scientist : 1
American scientist : 1 : American Scientist
American Sociological Review : 1
American sociological review : 1 : American Sociological Review
Anali Pravnog fakulteta u Beogradu : 1
Analog Game Studies : 1
Analysis : 1
Analysis, Design and Evaluation of Man–Machine Systems : 1
Angelaki : 1
Anglia : 1
Animal Behaviour : 1
Animal Cognition : 1
Animals : 1
Ann. Math. Artif. Intell. : 1 : Annals of Mathematics and Artificial Intelligence
Ann. Math. Artificial Intelligence : 1 : Annals of Mathematics and Artificial Intelligence
Ann. Oper. Res. : 1 : Annals of Operations Research
Ann. Softw. Eng. : 1 : Annals of Software Engineering
Annali d'Italianistica : 1
Annals of Anthropological Practice : 1
Annals of Epidemiology : 1
Annals of Internal Medicine: Clinical Cases : 1
Annals of Mathematics and Artificial Intelligence : 1
Annals of Operations Research : 1
Annals of Pharmacotherapy : 1
Annals of Pure and Applied Logic : 1
Annals of the International Communication Asociation: Communication Yearbook : 1
Annual Review of Anthropology : 1
Annual Review of Computer Science : 1
Annual Review of Criminology : 1
Annual Review of Economics : 1
Annual review of entomology                                                     : 1 : Annual Review Of Entomology
Annual Review Of Entomology : 1
Annual Review of Law and Social Science : 1
Annual Review of Neuroscience : 1
Annual Review of Political Science : 1
Annual Review of Psychology : 1
Annual review of sociology                                                      : 1 : Annual Review Of Sociology
Annual Review of Sociology : 1
Anthropological Quarterly : 1
Anthropology : 1
Anthropology and Humanism : 1
Anthropology of Consciousness : 1
AoIR Selected Papers of Internet Research : 1
Apollo - University of Cambridge Repository : 1
Appl. Artif. Intell. : 1 : Applied Artificial Intelligence
Appl. Intell. : 1 : Applied Intelligence
Appl. Ontology : 1 : Applied Ontology
Applied Animal Behaviour Science : 1
Applied Artificial Intelligence : 1
Applied Cognitive Psychology : 1
Applied Ergonomics : 1
Applied Linguistics Review : 1
Applied Mathematics and Computation : 1
Applied Semiotics : 1
Applied Soft Computing : 1
Archaeometry : 1
Archivaria : 1
Archives of Disease in Childhood : 1
Archives of Sexual Behavior : 1
Argument Comput. : 1 : Argument and Computation
Argumentation in Artificial Intelligence : 1
Art in the Anthropocene: Encounters among aesthetics, politics, environments and epistemologies : 1
Art Sci. Eng. Program. : 1 : The Art, Science, and Engineering of Programming
Artif. Intell. : 1 : Artificial Intelligence
Artif. Intell. Eng. : 1 : Artificial Intelligence in Engineering
Artif. Intell. Law : 1 : Artificial Intelligence and Law
Artif. Intell. Medicine : 1 : Artificial Intelligence in Medicine
Artif. Intell. Rev. : 1 : Artificial Intelligence Review
Artif. Life                                                                     : 1 : Artificial Life
Artif. Life Robotics : 1 : Artificial Life and Robotics
Artificial intelligence : 1 : Artificial Intelligence
Artificial Intelligence : 1  
Artificial Intelligence and Law : 1
Artificial Intelligence for Engineering Design, Analysis and Manufacturing: AIEDAM : 1
Artificial Intelligence Review : 1
Artificial Intelligence Today : 1
Artificial Intelligence Today: Recent Trends and Developments : 1
Artificial Intelligence: The First Hundred Years. to appear : 1
Artificial life                                                                 : 1 : Artificial Life
Artificial Life : 1
Arts : 1
arXiv : 1
Asian Journal of Comparative Politics : 1
Asian Philosophy : 1
Assembly : 1
Atlanta: US Department of Health and Human Services, Centers for Disease Control and Prevention : 1
Australas. J. Inf. Syst. : 1 : Australasian Journal of Information Systems
Australasian Journal of Philosophy : 1
Australian & New Zealand Journal of Psychiatry : 1
Australian Journal of Public Administration : 1
Authoring Tools for Advanced Technology Learning Environments : 1
Autism : 1
Autism in Adulthood : 1
Autism Policy & Practice: The Open Access Autism Journal : 1
Autism Research : 1
Autom. Softw. Eng. : 1 : Automated Software Engineering
Automated Driving : 1
Automated Knowledge Base Construction, AKBC : 1
Automated Reasoning : 1
Automatica : 1
Automation in Construction : 1
Auton. Agents Multi Agent Syst. : 1 : Autonomous Agents and Multi-Agent Systems
Auton. Robots : 1 : Autonomous Robots
Autonomous Agents and Multi-Agent Systems : 1
Autonomous Robots : 1
Autonomy, the Critical Journal of Interdisciplinary Autism Studies : 1
Axiomathes : 1
Baltic Journal of Modern Computing : 1
Baltic Screen Media Review : 1
Bank of England Quarterly Bulletin : 1
Behav. Inf. Technol. : 1 : Behaviour and Information Technology
Behavioral and Brain Sciences : 1
Behavioral Science : 1
Behaviour & Information Technology : 1
Behavioural Processes : 1
Behavioural Public Policy : 1
Bereavement Care : 1
Berkeley Technology Law Journal Online : 1
Big Data & Society : 1
Bildung und Erziehung : 1
Biochemistry : 1
Bioethics : 1
Bioinform. : 1 : Bioinformatics
Bioinformatics : 1
Biological Invasions : 1
Biological Psychiatry : 1
bioRxiv : 1
BioScience : 1
Biosemiotics : 1
BJS Statistics : 1
Black Camera : 1
Black Educology Mixtape "Journal" : 1
BMC Bioinformatics : 1
BMC Biology : 1
BMC Health Services Research : 1
BMC Medical Research Methodology : 1
BMC Women's Health : 1
Bmj                                                                             : 1 : BMJ
BMJ : 1
BMJ Global Health : 1
BMJ Mental Health : 1
BMJ Open : 1
BMJ paediatrics open                                                            : 1 : BMJ Paediatrics Open
BMJ Paediatrics Open : 1
Borderline Personality Disorder and Emotion Dysregulation : 1
Boston University Law Review, Forthcoming : 1
Br. J. Educ. Technol. : 1 : British Journal of Educational Technology
Brain : 1
Brain and Behavioral Sciences : 1
Brain Connectivity : 1
Brain Sciences : 1
Brain, Behavior, and Immunity : 1
British Journal for the History of Philosophy : 1
British Journal of Criminology : 1
British Journal of Educational Psychology : 1
British Journal of Educational Technology : 1
British Journal of Industrial Relations : 1
British Journal of Management : 1
British Journal of Psychiatry : 1
British Journal of Social Psychology : 1
Brookings Papers On Economic Activity : 1
Buffalo Law Review : 1
Bull. EATCS : 1 : Bulletin of the EATCS
Bulletin of Symbolic Logic : 1
Bureau of Justice Statistics : 1
Business & Society : 1
Business and Information Systems Engineering : 1
Calif. L. Rev. : 1
California Law Review : 1
Callaloo : 1
Cambridge Journal of Economics : 1
Canadian Game Studies Association : 1
Canadian Journal of Political Science : 1
Canadian Public Policy : 1
Capitalism Nature Socialism : 1
Cardozo Law Review : 1
Case Western Reserve Law Review : 1
Case-Based Reasoning Research and Development : 1
Cataloging & Classification Quarterly : 1
Catalyst: Feminism, Theory, Technoscience : 1
Categories for the Working Philosopher : 1
Cato : 1
Cell : 1
Center for Law & Economics Working Paper Series : 1
Center of Languages and Literature : 1
Center on Budget and Policy Priorities : 1
Chaos, Solitons & Fractals : 1
Chemical Senses : 1
CHI EA '09: CHI '09 Extended Abstracts on Human Factors in Computing Systems : 1
Child Abuse Review : 1
Children & Society : 1
Children : 1
Chinese Studies in Philosophy : 1
Christianity Today : 1
Cig                                                                             : 1 : CIG
CIG : 1
Cig : 1
Cinergie - Il cinema e le altre arti : 1
Circa : 1
City : 1
City and Society : 1
Cladistics : 1
Class : 1
Clinical Epidemiology : 1
Clinical Infectious Diseases : 1
Clinical Psychology Review : 1
Clinics in dermatology : 1
Cluster Computing : 1
Code of Human Research Ethics Leicester British Psychological Society : 1
CoDesign : 1
Cogn. Comput. : 1 : Cognitive Computation
Cogn. Process. : 1 : Cognitive Processing
Cogn. Sci. : 1
Cogn. Sci. : 1 : Cognitive Science
Cogn. Syst. Res. : 1 : Cognitive Systems Research
Cognition : 1
Cognition and Instruction : 1
Cognitive Agents for Virtual Environments : 1
Cognitive Computation : 1 
Cognitive Linguistics : 1
Cognitive Neurodynamics : 1
Cognitive Neuropsychology : 1
Cognitive Processing : 1
Cognitive Psychology : 1
Cognitive Science : 1
Cognitive Systems Research : 1
Cognitive Technologies Laboratory : 1
Cognitive Therapy and Research : 1
Coling-2016 : 1
Collection Building : 1
COLT : 1
Columbia Business School Research Paper : 1
Columbia University : 1
Commun. ACM : 1 : Communications of the ACM
Communication Theory : 1
Communication Trends : 1
Communications Earth & Environment : 1
Communications in Computer and Information Science : 1
Communications Medicine : 1
Communications of the ACM : 1
Communications of the Association for Information Systems : 1
Compact Textbooks in Mathematics : 1
Comparative and Continental Philosophy : 1
Comparative Political Studies : 1
Comparative politics : 1
Complex. : 1 : Complexity
Complexity : 1
Composition Studies : 1
Comput. : 1 : Computers
Comput. Animat. Virtual Worlds : 1 : Computer Animation and Virtual Worlds
Comput. Educ. : 1 : Computers and Education
Comput. Entertain. : 1 : Computers in Entertainment
Comput. Hum. Behav. : 1 : Computers in Human Behavior
Comput. Intell. : 1 : Computational Intelligence
Comput. J. : 1 : The Computer Journal
Comput. Lang. Syst. Struct. : 1 : Computer Languages, Systems and Structures
Comput. Linguistics : 1 : Computational Linguistics
Comput. Math. Organ. Theory : 1 : Computational and Mathematical Organization Theory
Comput. Music. J. : 1 : Computer Music Journal
Comput. Networks ISDN Syst. : 1 : Computer Networks and ISDN Systems
Comput. Sci. Educ. : 1 : Computer Science Education
Comput. Support. Cooperative Work. : 1 : Computer Supported Cooperative Work (CSCW)
Computation for Metaphors, Analogy and Agents : 1
Computational & Mathematical Organization Theory : 1
Computational and Mathematical Organization Theory : 1
Computational and Mathematical Organization Theory : 1 
Computational Brain & Behavior : 1
Computational Communication Research : 1
Computational Economics : 1
Computational Intelligence : 1
Computational intelligence : 1 : Computational Intelligence 
Computational Linguistics : 1
Computational Statistics & Data Analysis : 1
Computer : 1
Computer Aided Verification : 1
Computer Applications in Engineering Education : 1
Computer Engineering : 1
Computer Graphics Forum : 1
Computer Science and Information Systems : 1
Computer Science Department Faculty Publication Series : 1
Computer Science Education : 1
Computer Speech & Language : 1
Computers : 1
Computers and Biomedical Research : 1
Computers and Composition : 1
Computers and Graphics (Pergamon) : 1
Computers in Entertainment (CIE) : 1
Computers in Entertainment : 1
Computers in Human Behavior : 1
Computers in Industry : 1
Computing in Science & Engineering : 1
Computing Surveys : 1
Comunicação e Sociedade : 1
Concurrency Theory, CONCUR : 1
Connect. Sci. : 1 : Connection Science
Connection Science : 1
Consumption Markets & Culture : 1
Contagion: Journal of Violence, Mimesis, and Culture : 1
Contemporary Psychoanalysis : 1
Contemporary Voice of Dalit : 1
Contestations in Contemporary Southeast Asia : 1
Context : 1
Continuum : 1
Contraception : 1
Contributions to Indian Sociology : 1
Convergence: The International Journal of Research into New Media Technologies : 1
Coordination, Organizations, Institutions and Norms in Agent Systems V : 1
Coordination: Principles, Artefacts and Theories (SOCIAL. PATH) : 1
Cornell Law Review : 1
CoRR : 1
Correct Reasoning : 1
Counter Terrorist Trends and Analyses : 1
Crime & Delinquency : 1
Crime and Justice : 1
Crime, Law and Social Change : 1
Crime, Media, Culture : 1
Critical Inquiry : 1
Critical inquiry : 1
Critical Philosophy of Race : 1
Critical Public Health : 1
Critical Research on Religion : 1
Criticism : 1
Critique of Political Economy : 1
Croation International Relations Review : 1
CrossCurrents : 1
Cryptologia : 1
Cultural Anthropology : 1
Cultural Studies : 1
Culture and Organization : 1
Culture, Agriculture, Food and Environment : 1
Culture, Theory and Critique : 1
Current Anthropology : 1
Current Biology : 1
Current Directions in Psychological Science : 1
Current Issues in Language Planning : 1
Current Sociology : 1
Curriculum Inquiry : 1
Cursor Mundi : 1
Cybern. Syst. : 1 : Cybernetics and Systems
Cybernetics : 1
CyberPsychology & Behavior : 1
Cyberpsychology & behavior : the impact of the Internet, multimedia and virtual reality on behavior and society : 1
Cyberpsychology, Behavior, and Social Networking : 1
Cyberpsychology: Journal of Psychosocial Research on Cyberspace : 1
CyberTherapy     Rehabilitation Magazine : 1 : CyberTherapy Rehabilitation Magazine
D3-Tips-and-Tricks [Accessed: 1 May 2016] : 1
Daedalus : 1
Dagstuhl Artifacts Ser. : 1 
Dagstuhl Manifestos : 1
Dagstuhl Reports : 1
Dagstuhl Reports : 1 
Data & Knowledge Engineering : 1
Data & Society : 1
Data Knowl. Eng. : 1 : Data and Knowledge Engineering
Datamation : 1
Debating Institutionalism : 1
Decis. Support Syst. : 1 : Decision Support Systems
Decision Support Systems : 1
Decolonization: Indigeneity, Education and Society : 1
Defra : 1
Delhi Psychiatry Journal : 1
Democratization : 1
Demography : 1
Deontic Logic in Computer Science: Normative System Specification : 1
Department of Information and Computing Sciences Utrecht University Tech Rep UU-CS-2001-35 : 1
Derrida Today : 1
Design Issues : 1
Developmental Medicine & Child Neurology : 1
Developments in Plant Breeding : 1
Deviant Behavior : 1
Dialectics and Humanism : 1
Dialogue Discourse : 1 
Digit. Creativity : 1 : Digital Creativity
Digital Arts and Culture (DAC) : 1
Digital Creativity : 1
Digital Culture & Society : 1
Digital Games Research Association (DiGRA) : 1
Digital Humanities Quarterly : 1
Digital Journalism : 1
Diogenes : 1
Diplomatic History : 1
Directions and Implications of Advanced Computing,(DIAC-87) : 1
Disability & Society : 1
Discourse & Communication : 1
Discourse & Society : 1
Discourse Processes : 1
Discourse: Studies in the Cultural Politics of Education : 1
Discover Artificial Intelligence : 1
Discover Sustainability : 1
Discrete Applied Mathematics : 1
Distributed Computing : 1
Dreaming : 1
Driven Architecture : 1
Duke Law Journal : 1
Dyn. Games Appl. : 1 : Dynamic Games and Applications
Dynamic Games and Applications : 1
E-Learning and Digital Media : 1
E:CO Emergence: Complexity and Organization : 1
EAI Endorsed Trans. Creative Technol. : 1 : EAI Endorsed Transactions on Creative Technologies
Early Years: An International Journal of Research and Development. : 1
Ecological Economics : 1
Econometrica : 1
econometrica : 1 : Econometrica
Economic and Political Weekley : 1
Economic and Social Review : 1
Economic Anthropology : 1
Economica : 1
Economics and Philosophy : 1
Economics of Education Review : 1
Economics of transition : 1
ECOOP'97 - Object-Oriented Programming : 1
Education : 1
Educational and Psychological Measurement : 1
Educational Philosophy and Theory : 1
Educational Studies in Mathematics : 1
Educational Studies, AESA : 1
Educational Technology Research and Development : 1
Edusemiotics - A Handbook : 1
EGA Revista de Expression Grafica Arquitectonica : 1
Electron. Commer. Res. : 1 : Electronic Commerce Research
Electron. Commer. Res. Appl. : 1 : Electronic Commerce Research and Applications
Electron. Mark. : 1 : Electronic Markets
Electron. Notes Theor. Comput. Sci. : 1 : Electronic Notes in Theoretical Computer Science
Electron. Publ. : 1 : Electronic Publishing
Electron. Trans. Artif. Intell. : 1 : Electronic Transactions on Artificial Intelligence
Electronic Communications of the EASST : 1
Electronic Journal of Combinatorics : 1
Electronic Notes in Theoretical Computer Science, ENTCS : 1
Electronic Proceedings in Theoretical Computer Science : 1
Eleventh Annual International Workshop on Software Technology and Engineering Practice : 1
eLife : 1
Embodied Conversational Agents : 1
Emergency medicine clinics of North America : 1
Emotion : 1
Emotion, Space and Society : 1
Empirical Software Engineering : 1
Encyclopedia of Autism Spectrum Disorders : 1
Encyclopedia of Electrical and Electronics Engineering : 1
EndNotes : 1
Eng. Appl. Artif. Intell. : 1 : Engineering Applications of Artificial Intelligence
Engineering : 1
Engineering Applications of Artificial Intelligence : 1
Engineering Multi-Agent Systems, EMAS : 1
Enterp. Inf. Syst. : 1 : Enterprise Information Systems
Enterp. Model. Inf. Syst. Archit. Int. J. Concept. Model. : 1 : Enterprise Modelling and Information Systems Architectures
Entertain. Comput. : 1 : Entertainment Computing
Entertainment Computing : 1
Environ. Model. Softw. : 1 : Environmental Modelling and Software
Environment and Behavior : 1
Environment and Planning A : 1
Environment and Planning B : 1
Environment and Planning C: Politics and Space : 1
Environment and Planning D: Society and Space : 1
Environment and Planning E: Nature and Space : 1
Environmental Governance Reconsidered: Challenges, Choices, and Opportunities : 1
Environmental Management : 1
Environmental Politics : 1
Environmental Science & Technology : 1
Environments for Multi-Agent Systems : 1
Environmetrics : 1
Epidemiology : 1
EPJ Data Sci. : 1 : EPJ Data Science
Equity and Access in Algorithms, Mechanisms, and Optimization : 1
Erasmus Journal for Philosophy and Economics : 1
ERCIM News : 1
Ergonomics : 1
Erkenntnis : 1
Erwägen Wissen Ethik : 1 
Essays in Philosophy : 1
Estudios/Working Papers (Centro de Estudios Avanzados en Ciencias Sociales) : 1
Ethics and Education : 1
Ethics and Information Technology : 1
Ethics and Information Technology : 1
Ethics and Politics : 1
Ethics in Science and Environmental Politics : 1
Ethics Inf. Technol. : 1 : Ethics and Information Technology
Ethnic and Racial Studies : 1
Ethnographic Studies : 1
Ethnography : 1
Ethos : 1
Etnofoor : 1
Eur. J. Oper. Res. : 1 : European Journal of Operational Research
EURO Journal on Decision Processes : 1
Eurographics : 1
European Conference on e-Learning : 1
European Economic Review : 1
European journal of American studies : 1 : European Journal of American Studies
European Journal of Operational Research : 1
European Journal of Social Psychology : 1
European Journal of Sociology : 1
European Journal of Trauma & Dissociation : 1
European Physical Journal: Special Topics : 1
European Political Science Review : 1
European Review : 1
European Scientific Journal : 1
European Society for Ecological Economics. : 1
Evaluation : 1
Evidence Based Nursing : 1
Evol. Comput. : 1 : Evolutionary Computation
Evolution: Education and Outreach : 1
Evolutionary Computation : 1
Evolutionary computation : 1 : Evolutionary Computation
Evolutionary Psychology : 1
Executive Office of the President of USA : 1
Experimental Interactive Learning in Industrial Management: New approaches to Learning, Studying and Teaching : 1
Expert Syst. Appl. : 1 : Expert Systems with Applications
Expert Systems with Applications : 1
EXTRAPOLATION : 1
F1000Research : 1
Facets of Systems Science : 1
Family Relations : 1
Fantastika : 1
Fed. Probation : 1
Federal Register : 1
Feminism & Psychology : 1
Feminist Media Histories : 1
Feminist Studies : 1
Filozofija i drustvo : 1
Finance : 1
Finance and Economics Discussion Series 2018-001 : 1
First Monday : 1
FLAP : 1
Florida International University Law Review : 1
Focaal : 1
Folia Primatologica : 1 
Food and Foodways : 1
Food, Culture and Society : 1
Forensic Anthropology and Medicine : 1
Forensic Science International : 1
Forensic Science, Medicine, and Pathology : 1
Formal Aspects Comput. : 1 : Formal Aspects of Computing
Formal Aspects of Computing : 1
Formal Methods in System Design : 1
Forthcoming in Judgment and Decision Making : 1
Forthcoming: Journal of Causal Inference : 1
Foundations and Trends in Machine Learning : 1
Foundations and Trends in Programming Languages : 1
Foundations and Trends in Web Science : 1
Foundations for Undergraduate Research in Mathematics : 1
Framework: The Journal of Cinema and Media : 1
From Object-Orientation to Formal Methods : 1
Frontiers Comput. Sci. : 1 : Frontiers of Computer Science
Frontiers in Artificial Intelligence and Applications : 1
Frontiers in Human Neuroscience : 1
Frontiers in Neuroinformatics : 1
Frontiers in Psychology : 1
Frontiers in Robotics and AI : 1
Frontiers in Sociology : 1
Frontiers in Sports and Active Living : 1
Frontiers in Veterinary Science : 1
Frontiers Inf. Technol. Electron. Eng. : 1 : Frontiers of Information Technology and Electronic Engineering
Frontiers of Narrative Studies : 1
Frontiers Virtual Real. : 1 : Frontiers in Virtual Reality
Fundam. Informaticae : 1 : Fundamenta Informaticae
Fundamenta Informaticae : 1
Future Gener. Comput. Syst. : 1 : Future Generation Computer Systems
Future Generation Computer Systems : 1 
Futures : 1
Fuzzy Sets and Systems : 1
Gait & Posture : 1
Game AI Pro 2: Collected Wisdom of Game AI Professionals : 1
Game Stud. : 1 : Game Studies
Game Studies : 1
Games and Culture : 1
Games and Economic Behavior : 1
gamevironments : 1
Gastroenterology : 1
GDC : 1
Gender & Development : 1
Gender & Society : 1
Gender, Place & Culture : 1
Genet. Program. Evolvable Mach. : 1 : Genetic Programming and Evolvable Machines
Genetic Programming and Evolvable Machines : 1
Genome Biology : 1
GeoInformatica : 1 
Geosphere : 1
Germanic Review : 1
GetMobile Mob. Comput. Commun. : 1 : GetMobile Mobile Computing and Communications
Github : 1
GLO Discussion Paper : 1
Global Networks : 1
Global Political Sociology : 1
GLQ: A Journal of Lesbian and Gay Studies : 1
Governance : 1
Graduate Texts in Mathematics : 1
Granta : 1
Group & Organization Management : 1
Group Decision and Negotiation : 1
H-Asia : 1
Handbook of Chemistry and Physics. : 1
Handbook of Comics and Graphic Narratives : 1
Handbook of Computer Game Studies : 1
Handbook of Social Cognition : 1
Handbook of the History of Logic : 1
Handbuch der Künstlichen Intelligenz : 1
Harm Reduction Journal : 1
Harper's Magazine : 1
Harvard Business Review : 1
Harvard Journal of Law and Public Policy : 1
Harvard Law Review : 1
Haskell : 1
Hastings Law Journal : 1
Hastings Women's Law Journal : 1
HAU: Journal of Ethnographic Theory : 1
Hazardous Waste : 1
HCI Models, Theories, and Frameworks : 1
Headache : 1
Health & place : 1
Health Affairs : 1
Health care disparities and the LGBT population : 1
Health Technology Assessment : 1
Heidelberg University Publishing : 1
High. Order Symb. Comput. : 1 : Higher-Order and Symbolic Computation
Higher Education Research & Development : 1
Higher Education Review : 1
HIGHER EDUCATION REVIEW-LONDON- : 1
Higher-Order and Symbolic Computation : 1
Historical Social Research : 1
Historical Studies in the Natural Sciences : 1
History : 1
History and Philosophy of Logic : 1
History of Education : 1
Hormones and behavior : 1
Hum. Comput. Interact. : 1 : Human–Computer Interaction
Human Behavior and Emerging Technologies : 1
Human Development : 1
Human Factors: The Journal of the Human Factors and Ergonomics Society : 1
Human organization : 1
Human Relations : 1
Human Reproduction Update : 1
Human Resource Development Review : 1
Human Resource Management : 1
Human Service Organizations: Management, Leadership & Governance : 1
Human Studies : 1
Human Technology : 1
Human-Computer Interaction : 1
Human-Computer Interaction and Complex Systems : 1
Hybrid Systems : 1
IAENG International Journal of Computer Science : 1
IBM J. Res. Dev. : 1 : IBM Journal of Research and Development
IBM Syst. J. : 1 : IBM Systems Journal
IBM Systems Journal : 1
Ibn AL- Haitham Journal For Pure and Applied Sciences : 1
IEEE Access : 1
IEEE Access : 1 
IEEE Ann. Hist. Comput. : 1 : IEEE Annals of the History of Computing
IEEE Annals of The History of Computing : 1
IEEE Annals of the History of Computing : 1
IEEE Communications Magazine : 1
IEEE Comput. Intell. Mag. : 1 : IEEE Computational Intelligence Magazine
IEEE Computational Intelligence Magazine : 1
IEEE Computer : 1
IEEE Computer : 1 
IEEE Computer Graphics and Applications : 1
IEEE Computer Graphics and Applications : 1 
IEEE Concurr. : 1 : IEEE Concurrency
IEEE Data Engineering Bulletin : 1
IEEE Expert : 1
IEEE Intell. Syst. : 1 : IEEE Intelligent Systems
IEEE Intelligent Systems : 1
IEEE Internet Comput. : 1 : IEEE Internet Computing
IEEE Internet Computing : 1
IEEE J. Biomed. Health Informatics : 1 : IEEE Journal of Biomedical and Health Informatics
IEEE Pervasive Comput. : 1 : IEEE Pervasive Computing
IEEE Robotics and Automation Letters : 1
IEEE Security & Privacy : 1
IEEE Softw. : 1 : IEEE Software
IEEE Software : 1
IEEE Technol. Soc. Mag. : 1 : IEEE Technology and Society Magazine
IEEE Technology and Society Magazine : 1
IEEE Technology and Society Magazine : 1
IEEE Trans. Affect. Comput. : 1
IEEE Trans. Comput. Intell. AI Games : 1
IEEE Trans. Comput. Soc. Syst. : 1
IEEE Trans. Computers : 1
IEEE Trans. Evol. Comput. : 1
IEEE Trans. Games : 1
IEEE Trans. Hum. Mach. Syst. : 1
IEEE Trans. Hum. Mach. Syst. : 1 : IEEE Transactions on Human-Machine Systems
IEEE Trans. Inf. Theory : 1
IEEE Trans. Knowl. Data Eng. : 1 : IEEE Transactions on Knowledge and Data Engineering
IEEE Trans. Learn. Technol. : 1
IEEE Trans. Pattern Anal. Mach. Intell. : 1
IEEE Trans. Serv. Comput. : 1
IEEE Trans. Software Eng. : 1
IEEE Trans. Syst. Man Cybern. : 1
IEEE Trans. Syst. Man Cybern. Part A : 1
IEEE Trans. Syst. Man Cybern. Part B : 1
IEEE Trans. Syst. Man Cybern. Part C : 1
IEEE Trans. Vis. Comput. Graph. : 1
IEEE Transactions on Affective Computing : 1
IEEE Transactions on Cognitive and Developmental Systems : 1
IEEE Transactions on Communications : 1
IEEE Transactions on Computational Intelligence and AI In Games : 1
IEEE Transactions on Computational Intelligence and AI in Games : 1
IEEE Transactions on Computers : 1
IEEE Transactions on Engineering Management : 1
IEEE Transactions on Evolutionary Computation : 1
IEEE Transactions on Fuzzy Systems : 1
IEEE Transactions on Games : 1
IEEE Transactions on Human-Machine Systems : 1
IEEE Transactions on Human-Machine Systems : 1
IEEE Transactions on Industrial Informatics : 1
IEEE Transactions on Information Theory : 1
IEEE Transactions on Intelligence and AI in Games : 1
IEEE Transactions on Knowledge and Data Engineering : 1
IEEE transactions on knowledge and data engineering : 1
IEEE Transactions on Professional Communication : 1
IEEE Transactions on Robotics : 1
IEEE Transactions on Software Engineering : 1
IEEE Transactions on Systems, Man and Cybernetics Part B—Cybernetics : 1
IEEE Transactions on Systems, Man and Cybernetics, Part C (Applications and Reviews) : 1
IEEE Transactions on Visualization and Computer Graphics : 1
IEEE transactions on Visualization and Computer Graphics : 1
IEEE/ACM Transactions on Networking : 1
IET Commun. : 1
IJCAI : 1
IMAGE. Zeitschrift für interdisziplinäre Bildwissenschaft. : 1
Imperial College London : 1
Imprimis : 1
Incidence, and Underreporting of Gun Violence: New Evidence Using Shotspotter Data : 1
Indian Journal of Psychological Medicine : 1
Indoor Air : 1
Industrial and Corporate Change : 1
Industrial and Labor Relations Review : 1
Inf. Comput. : 1
Inf. Control. : 1
Inf. Process. Manag. : 1
Inf. Res. : 1
Inf. Sci. : 1
Inf. Soc. : 1
Inf. Softw. Technol. : 1
Inf. Syst. Frontiers : 1
Inf. Syst. Manag. : 1
Infant and Child Development : 1
Inform : 1
Informal Logic : 1
Informatica (Slovenia) : 1
Informatica : 1
Informatik-Fachberichte : 1
Informatik/Informatique : 1
Information : 1
Information and Computation : 1
Information And Knowledge Management, CIKM : 1
Information and Learning Sciences : 1
Information and Organization : 1
Information and Software Technology : 1
Information Communication and Society : 1
Information Systems : 1
Information Systems Research : 1
Information Visualization : 1
Information, Communication & Society : 1
INFORMS J. Comput. : 1
Injury : 1
Inmaterial : 1
Innovations In Systems and Software Engineering : 1
Innovative Leadership in Times of Compelling Changes : 1
Inside Higher Ed : 1
Insight Turkey : 1
Int. J. Agent Oriented Softw. Eng. : 1
Int. J. Agent Technol. Syst. : 1
Int. J. Ambient Comput. Intell. : 1
Int. J. Approx. Reason. : 1
Int. J. Artif. Intell. Educ. : 1
Int. J. Artif. Intell. Tools : 1 : International Journal on Artificial Intelligence Tools
Int. J. Auton. Adapt. Commun. Syst. : 1
Int. J. Bioinform. Res. Appl. : 1
Int. J. Bus. Process. Integr. Manag. : 1
Int. J. Comput. Intell. Stud. : 1
Int. J. Comput. Sci. Eng. : 1
Int. J. Comput. Support. Collab. Learn. : 1
Int. J. Comput. Vis. : 1
Int. J. Cooperative Inf. Syst. : 1
Int. J. Electron. Commer. : 1
Int. J. Hum. Comput. Stud. : 1
Int. J. Humanoid Robotics : 1
Int. J. Intell. Syst. : 1
Int. J. Knowl. Based Intell. Eng. Syst. : 1
Int. J. Knowl. Learn. : 1
Int. J. Man Mach. Stud. : 1
Int. J. Medical Informatics : 1
Int. J. Parallel Emergent Distributed Syst. : 1
Int. J. Parallel Program. : 1
Int. J. Pattern Recognit. Artif. Intell. : 1
Int. J. Semantic Web Inf. Syst. : 1
Int. J. Softw. Eng. Knowl. Eng. : 1
Int. J. Softw. Informatics : 1
Int. J. Synth. Emot. : 1
Int. J. Web Based Communities : 1
Int. J. Wirel. Inf. Networks : 1
Integrated Manufacturing Systems : 1
Integrated Network Management II : 1
Inteligencia Artif. : 1
Intell. Autom. Soft Comput. : 1
Intell. Syst. Account. Finance Manag. : 1
Intelligent Narrative Technologies : 1
Intelligent Virtual Agents, IVA : 1
Intelligenza Artificiale : 1
INTERACT 2015 : 1
Interact. Comput. : 1
Interacting with Computers : 1
Interaction Studies : 1
Interactions : 1
Interactive Advertising : 1
Interactive Theorem Proving : 1
Interdisciplinary Description of Complex Systems : 1
Interfaces : 1
International Business Machines Corporation : 1
International Economic Review : 1
International Environmental Agreements: Politics, Law and Economics : 1
International Feminist Journal of Politics : 1
International Journal Of Advanced Computer Science & Applications (IJACSA)      : 1 
International Journal of Advanced Computer Science and Applications, (IJACSA) : 1
International Journal of Agent-Oriented Software Engineering : 1
International Journal of Ambient Computing and Intelligence (IJACI) : 1
International Journal of Applied Engineering Research : 1
International Journal of Approximate Reasoning : 1
International Journal of Artificial Intelligence in Education : 1
International Journal of Artificial Intelligence in Education, IJAIED : 1
International Journal of Bifurcation and Chaos : 1
International Journal of Child-Computer Interaction : 1
International Journal of Collaborative Enterprise : 1
International Journal of Communication : 1
International Journal of Computer Games Technology : 1
International Journal of Computer Science and Information Technologies : 1
International Journal of Contemporary Economics and Administrative Sciences : 1
International Journal of Contemporary Hospitality Management : 1
International Journal of Cooperative Information Systems : 1
International Journal of Critical Pedagogy : 1
International Journal of Design : 1
International Journal of Disability, Development and Education : 1
International Journal of Doctoral Studies : 1
International Journal of Education Through Art : 1
International Journal of Educational Technology in Higher Education : 1
International Journal of Energy, Information and Communications : 1
International Journal of Epidemiology : 1
International Journal of Evidence Based Coaching & Mentoring : 1
International Journal of Expert Systems : 1
International Journal of Health Services : 1
International Journal of Heritage Studies : 1
International Journal of Human Computer Studies : 1
International Journal of Human-Computer Interaction : 1
International Journal of Human-Computer Studies : 1
International Journal of Inclusive Education : 1
International Journal of Intelligent Information Systems : 1
International Journal of Intelligent Systems in Accounting, Finance & Management : 1
International Journal of Islamic Architecture : 1
International Journal of Machine Consciousness : 1
International Journal of Man-Machine Studies : 1
International Journal of Management Reviews : 1
International Journal of Occupational and Environmental Health : 1
International Journal of Qualitative Methods : 1
International Journal of Qualitative Studies in Education : 1
International Journal of Science and Research : 1
International Journal of Social Research Methodology : 1
International Journal of Special Education : 1
International Journal of Sustainability in Higher Education : 1
International Journal of Synthetic Emotions : 1
International Journal of the Sociology of Law : 1
International Journal of Transgender Health : 1
International Journal of Transgenderism : 1
International Journal of Urban and Regional Research : 1
International Journal on Digital Libraries : 1
International Labor and Working-Class History : 1
International Organization : 1
International Politics : 1
International Public Management Journal : 1
International Research Journal of Engineering and Technology (IRJET) : 1
International Review of Financial Analysis : 1
International Review of Law and Economics : 1
International Security : 1
International security : 1 : International Security
International Series in Operations Research & Management Science : 1
International Series on Computer Entertainment and Media Technology : 1
International Statistical Review : 1
International Studies Quarterly : 1
International Studies Review : 1
International Theory : 1
International Transactions on Electrical Energy Systems : 1
International Transactions on Systems Science and Applications, Special Issue on Agent Based Systems for Human Learning : 1
International Workshop on Programming Based on Actors, Agents, and Decentralized Control : 1
Internationales Begegnungs und Porschungszentrum fur Informatik (IBFI) : 1
Internet Policy Review : 1
Invictus : 1
Iowa Law Review : 1
IRE Trans. Inf. Theory : 1
Irvine, CA.: University of California : 1
Iscience : 1
Isis : 1
Israel Affairs : 1
Issues In Law & Medicine : 1
it Inf. Technol. : 1
It's Complicated: the Social Lives of Networked Teens : 1
Itsec : 1
IVA : 1
J. ACM : 1
J. Am. Soc. Inf. Sci. : 1
J. Appl. Log. : 1
J. Appl. Non Class. Logics : 1
J. Artif. Gen. Intell. : 1
J. Artif. Intell. Res. : 1
J. Artif. Soc. Soc. Simul. : 1
J. Assoc. Inf. Sci. Technol. : 1
J. Biomed. Informatics : 1
J. Braz. Comput. Soc. : 1
J. Commun. : 1
J. Comput. Assist. Learn. : 1
J. Comput. Neurosci. : 1
J. Comput. Syst. Sci. : 1
J. Data Semant. : 1
J. Exp. Theor. Artif. Intell. : 1
J. Grid Comput. : 1
J. Inf. Law Technol. : 1
J. Inf. Secur. Appl. : 1
J. Inf. Technol. : 1
J. Int. Comput. Games Assoc. : 1
J. Intell. Fuzzy Syst. : 1
J. Intell. Inf. Syst. : 1
J. Log. Algebraic Methods Program. : 1
J. Log. Comput. : 1 : Journal of Logic and Computation
J. Log. Lang. Inf. : 1
J. Log. Program. : 1
J. Medical Syst. : 1
J. Object Oriented Program. : 1
J. Object Technol. : 1
J. Oper. Res. Soc. : 1
J. Parallel Distributed Comput. : 1
J. Philos. Log. : 1
J. Symb. Comput. : 1
J. Symb. Log. : 1
J. Syst. Integr. : 1
J. Univers. Comput. Sci. : 1
J. Vis. Lang. Comput. : 1
JAMA Network Open : 1
JAMA Psychiatry : 1
JAMA Surgery : 1
Janus Unbound : 1
Johnson Matthey Technology Review : 1
Journal Computacional Linguistics : 1
Journal for the Scientific Study of Religion : 1
Journal for the Study of Food and Society : 1
Journal for the Theory of Social Behaviour : 1
Journal of Abnormal Psychology : 1
Journal of Adolescent Health : 1
Journal of Adolescent Research : 1
Journal of Adult and Continuing Education : 1
Journal of Aesthetics and Art Criticism : 1
Journal of Anthropological Archaeology : 1
Journal of Applied Ecology : 1
Journal of Applied Ethics and Philosophy : 1
Journal of Applied Logic : 1
Journal of Applied Logics : 1
Journal of Applied Non-Classical Logics : 1
Journal of Applied Psychoanalytic Studies : 1
Journal of Art Historiography : 1
Journal of Artificial General Intelligence : 1
Journal of Artificial Intelligence Research : 1
Journal of Artificial Societies and Social Simulation, JASSS : 1
Journal of Asian and African Studies : 1
Journal of Autism and Developmental Disorders : 1
Journal of Automated Reasoning : 1
Journal of Behavioral and Experimental Economics : 1
Journal of Behavioral Public Administration : 1
Journal of Biomedical Semantics : 1
Journal of Broadcasting & Electronic Media : 1
Journal of Business Ethics : 1
Journal of Causal Inference : 1
Journal of Cell Science : 1
Journal of Chemical Education : 1
Journal of Child Psychology and Psychiatry : 1
Journal of Chinese History : 1
Journal of Clinical Child & Adolescent Psychology : 1
Journal of Clinical Epidemiology : 1
Journal of Cognitive Neuroscience : 1
Journal of Communication Disorders : 1
Journal of Community Psychology : 1
Journal of Comparative Economics : 1
Journal of Computational and Graphical Statistics : 1
Journal of Computational Social Science : 1
Journal of Computer and System Sciences : 1
Journal of Computer Assisted Learning : 1
Journal of Computer Game Design : 1
Journal of Computing and Information Technology : 1
Journal of Conflict Resolution : 1
Journal of Conflict resolution : 1 : Journal of Conflict Resolution
Journal of Consciousness Studies : 1
Journal of Constructivist Psychology : 1
Journal of Consumer Policy : 1
Journal of Consumer Research : 1
Journal of Contemporary Archival Studies : 1
Journal of Contemporary Ethnography : 1
Journal of Counseling Psychology : 1
Journal of Creating Value : 1
Journal of Creativity in Mental Health : 1
Journal of Criminal Justice : 1
Journal of Data-Centric Machine Learning Research : 1
Journal of Developmental & Behavioral Pediatrics : 1
Journal of Diabetes Science and Technology : 1
Journal of Documentation : 1
Journal of Economic Behavior & Organization : 1
Journal of Economic Issues : 1
Journal of Economic Literature : 1
Journal of Economic Perspectives : 1
Journal of Economic Theory : 1
Journal of Education Policy : 1
Journal of Educational Psychology : 1
Journal of Electronic Testing : 1
Journal of Emergency Nursing : 1
Journal of Empirical Research on Human Research Ethics : 1
Journal of English Studies and Comparative Literature : 1
Journal of Environmental Law : 1
Journal of Environmental Policy & Planning : 1
Journal of Epidemiology : 1
Journal of Ethnic and Migration Studies : 1
Journal of Evolutionary Economics : 1
Journal of Experimental & Theoretical Artificial Intelligence : 1
Journal of Experimental and Theoretical Artificial Intelligence : 1
Journal of Experimental Child Psychology : 1
Journal of experimental psychology. Applied : 1
Journal of Experimental Psychology. General : 1
Journal of Experimental Psychology. Learning, Memory, and Cognition : 1
Journal of Experimental Psychology: Applied : 1
Journal of Experimental Psychology: Human Perception and Performance : 1
Journal of Experimental Psychology: Learning, Memory, and Cognition : 1
Journal of Experimental Social Psychology : 1
Journal of Family History : 1
Journal of Family Practice : 1
Journal of Financial Economics : 1
Journal of Fixed Point Theory and Applications : 1
Journal of Fluid Mechanics : 1
Journal of Folklore Research : 1
Journal of Forensic Practice : 1
Journal of Functional Programming : 1
Journal of Further and Higher Education : 1
Journal of Game Development : 1
Journal of Gaming & Virtual Worlds : 1
Journal of Gender Studies : 1
Journal of General Physiology : 1
Journal of Geophysical Research: Solid Earth : 1
Journal of GLBT Family Studies : 1
Journal of Global Business and Technology : 1
Journal of Graduate Education : 1
Journal of Health Disparities Research and Practice : 1
Journal of Health, Social and Environmental Issues : 1
Journal of Historical Sociology : 1
Journal of Homosexuality : 1
Journal of Human-Technology Relations : 1
Journal of Humanistic Psychology : 1
Journal of Illinois History : 1
Journal of Inclusive Practice in Further and Higher Education : 1
Journal of Industrial and Business Economics : 1
Journal of Information and Telecommunication : 1
Journal of Information Ethics : 1
Journal of Information Processing : 1
Journal of Information Science : 1
Journal of Institutional Economics : 1
Journal of Instructional Development : 1
Journal of Integrative Neuroscience : 1
Journal of Intelligent Information Systems : 1
Journal of King Saud University - Computer and Information Sciences : 1
Journal of Knowledge Management : 1
Journal of Labor Economics : 1
Journal of Language and Social Psychology : 1
Journal of Language Modelling : 1
Journal of Latin American and Caribbean Anthropology : 1
Journal of Law and Economics : 1
Journal of LGBT Youth : 1
Journal of Librarianship and Information Science : 1
Journal of Literary & Cultural Disability Studies : 1
Journal of Logic and Computation : 1
Journal of Logic, Language and Information : 1
Journal of Machine Learning Research : 1
Journal of Management : 1
Journal of Management Control : 1
Journal of Management Information Systems : 1
Journal of Management Inquiry : 1
Journal of Management Studies : 1
Journal of Marriage and Family : 1
Journal of Material Culture : 1
Journal of Mathematical Psychology : 1
Journal of Mathematical Sociology : 1
Journal of Mathematics and Music : 1
Journal of Medical Ethics : 1
Journal of Medical Virology : 1
Journal of Memory and Language : 1
Journal of Microbiology & Biology Education : 1
Journal of Modern Literature : 1
Journal of Music, Technology & Education : 1
Journal of Narrative and Life History : 1
Journal of Nervous & Mental Disease : 1
Journal of Neuroscience, Psychology, and Economics : 1
Journal of Object Technology : 1
Journal of Open Source Education : 1
Journal of Parallel and Distributed Computing : 1
Journal of Peace Research : 1
Journal of Personality and Social Psychology : 1
Journal of Philosophical Logic : 1
Journal of Philosophy : 1
Journal of Physical Agents : 1
Journal of Planning Education and Research : 1
Journal of Policy Analysis and Management : 1
Journal of Policy and Complex Systems : 1
Journal of Political Economy : 1
Journal of Political Philosophy : 1
Journal of Popular Culture : 1
Journal of Popular Film and Television : 1
Journal of Psychoactive Drugs : 1
Journal of Psychosomatic Research : 1
Journal of Public Administration Research and Theory : 1
Journal of Public Economics : 1
Journal of Quantitative Description: Digital Media : 1
Journal of Racial and Ethnic Health Disparities : 1
Journal of Reproductive and Infant Psychology : 1
Journal of Research in Crime and Delinquency : 1
Journal of Research in Science Teaching : 1
Journal of Risk Research : 1
Journal of Semantics : 1
Journal of Sex Education and Therapy : 1
Journal of Sex Research : 1
Journal of Simulation : 1
Journal of Small Animal Practice : 1
Journal of Social Entrepreneurship : 1
Journal of Social Issues : 1
Journal of Software Engineering and Applications : 1
Journal of Sports Economics : 1
Journal of Statistical Software : 1
Journal of Symbolic Logic : 1
Journal of Systems and Software : 1
Journal of Systems Science and Systems Engineering : 1
Journal of Tax Practice and Procedure : 1
Journal of Teaching Writing : 1
Journal of the ACM : 1
Journal of the American Academy of Arts and Sciences : 1
Journal of the American Academy of Child & Adolescent Psychiatry : 1
Journal of the American Academy of Religion : 1
Journal of the American Medical Informatics Association : 1
Journal of the American Planning Association : 1
Journal of the American Society for Information Science and Technology : 1
Journal of the College of Languages : 1
Journal of the Fantastic in the Arts : 1
Journal of the National Medical Association : 1
Journal of the Operational Research Society : 1
Journal of the Pakistan Historical Society : 1
Journal of the Royal Anthropological Institute : 1
Journal of The Royal Society Interface : 1
Journal of the Science of Food and Agriculture : 1
Journal of the Society for American Music : 1
Journal of Theoretical Biology : 1
Journal of Theoretical Politics : 1
Journal of Transport & Health : 1
Journal of Trauma and Acute Care Surgery : 1
Journal of Trauma and Dissociation : 1
Journal of Urban Economics : 1
Journal of Urban History : 1
Journal of Vegetation Science : 1
Journal of Verbal Learning and Verbal Behavior : 1
Journal of Veterinary Behavior : 1
Journal of Virtual Worlds Research : 1
Journal of Visual Culture : 1
Journal of Visual Languages & Computing : 1
Journal of Visual Languages and Sentient Systems : 1
Journal of Women's Health : 1
Journal of World Popular Music : 1
Journal of World-Systems Research : 1
Journal:Metro Magazine: Media & Education Magazine : 1
Journalism History : 1
Judgement and Decision Making : 1
Judicature : 1
Jurix : 1
Kant-Studien : 1
Kill Screen : 1
Knowl. Based Syst. : 1
Knowl. Eng. Rev. : 1 : The Knowledge Engineering Review
Knowl. Inf. Syst. : 1
Knowledge Acquisition : 1
Knowledge Engineering Review : 1
Knowledge-Driven Computing : 1
Knowledge: Critical Concepts : 1
Kognitionswissenschaft : 1
Korean Economic Review : 1
Kvinder, Køn & Forskning : 1
Kyklos : 1
Künstliche Intell. : 1 : Künstliche Intelligenz 
Künstliche Intelligenz : 1
Labour Economics : 1
Labour History : 1
Land Use Policy : 1
Landscape and Urban Planning : 1
Lang. Resour. Evaluation : 1
Language & Communication : 1
Language : 1
Language and Speech : 1
Language in Mind: Advances in the Study of Language and Thought : 1
Language in Society : 1
Languages, Methodologies and Development Tools for Multi-Agent Systems : 1
Law and History Review : 1
Law and Inequality : 1
Law, Governance and Technology Series : 1
Leadership : 1
Learned Publishing : 1
Learning : 1
Learning and Cognition in Autism : 1
Learning, Media and Technology : 1
Lecture notes from the Formosan Summer School on Logic, Language, and Computation : 1
Lecture Notes in Computer Science : 1
Lecture Notes in Electrical Engineering : 1
Legal Communication & Rhetoric: JALWD : 1
Legalities : 1
Legislative Studies Quarterly : 1
LGBTQ+ Family: An Interdisciplinary Journal : 1
Library Hi Tech : 1
Library Trends : 1
Limm : 1
Linear Logic in Computer Science : 1
Lingua ac Communitas : 1
Linguistics : 1
Linguistics and Language Compass : 1
Linguistics and Philosophy : 1
Lisp and Symbolic Computation : 1
LISP Symb. Comput. : 1
Lit. Linguistic Comput. : 1
Literature and Theology : 1
Literature in North Queensland, LiNQ : 1
Local Government Studies : 1
Log. J. IGPL : 1 : Logic Journal of IGPL
Logic and Logical Philosophy : 1
Logic and Philosophy of Science : 1
Logic for Programming and Automated Reasoning : 1
Logic Journal of IGPL : 1
Logic Journal of the IGPL : 1
Logic Programming : 1
Logic, Rationality, and Interaction : 1
Logica Universalis : 1
Logical Methods in Computer Science : 1
Logics of Programs : 1
Longitudinal and Life Course Studies : 1
Los Alamos Science : 1
Loyola University Chicago Law Journal : 1
Mach. Learn. : 1 : Machine Learning
Mach. Learn. Sci. Technol. : 1
Machine Learning : 1
Man and World : 1
Management & Organizational History : 1
Management Communication Quarterly : 1
Management Learning : 1
Management Science : 1
Maritime Archaeology : 1
Massachusetts Institute of Technology : 1
Math Horizons : 1
Math. Log. Q. : 1
Math. Struct. Comput. Sci. : 1
Math. Syst. Theory : 1
Mathematical Structures in Computer Science : 1
Mathematics Magazine : 1
Mathematics Unlimited - 2001 and Beyond : 1
Media : 1
Media and Communication : 1
Media in Transition : 1
Media International Australia : 1
Media Psychology : 1
Media, Culture & Society : 1
Medical Anthropology Quarterly : 1
Medical Journal of Australia : 1
Medicina Sportiva : 1
MedieKultur : 1
Medium : 1
medRxiv : 1
Mehmet Akif Ersoy Üniversitesi İktisadi ve İdari Bilimler Fakültesi Dergisi : 1
Memory & cognition : 1
Men and Masculinities : 1
Metaphor and Symbol : 1
Metascience : 1
Methods and Techniques in Urban Engineering : 1
Microsoft Internal Memo : 1
Middle East Critique : 1
Middle East Journal : 1
Middle Eastern Studies : 1
Millennium: Journal of International Studies : 1
Mind     Society : 1
Mind & Society : 1
Mind : 1
Mind and Society : 1
Mind, Culture, and Activity : 1
Minds     Machines : 1
Minds and Machines : 1
Minds Mach. : 1
MIS Q. : 1
MIS Quarterly : 1
MMWR. Morbidity and Mortality Weekly Report : 1
Model Driven Engineering Languages and Systems : 1
Modeling and Verification of Parallel Processes : 1
Modern American History : 1
Monthly Review : 1
Mortality : 1
Multi-Agent Programming : 1
Multiagent Grid Syst. : 1
Multiagent Systems, Artificial Societies, and Simulated Organizations : 1
Multim. Syst. : 1
Multimodal Technologies and Interaction : 1
Multivariate behavioral research : 1
Music and Arts in Action : 1
Music Education Research : 1
Narrative Inquiry : 1
Narrative Intelligence : 1
National Crime Information Center : 1
National Geographic : 1
Nature : 1
Nature Biotechnology : 1
Nature Climate Change : 1
Nature Communications : 1
Nature communications : 1
Nature Ecology & Evolution : 1
Nature Human Behaviour : 1
Nature Machine Intelligence : 1
Nature Medicine : 1
Nature Physics : 1
Nature Reviews Earth & Environment : 1
Nature Reviews Microbiology : 1
Nature Reviews Physics : 1
Nature Sustainability : 1
Naturwissenschaften : 1
NBER Working Paper Series : 1
NCHS data brief : 1
Neural Comput. Appl. : 1
Neural Networks : 1
Neural Networks IEEE Transactions on : 1
NeuroImage : 1
NeuroImage : 1
Neuron : 1
Neuropsychologia : 1
Neuroscience & Biobehavioral Reviews : 1
New computational paradigms for computer music : 1
New England Journal of Medicine : 1
New Gener. Comput. : 1
New Generation Computing : 1
New German Critique : 1
New Ideas in Psychology : 1
New Media \& Society : 1
New Media Soc. : 1
New Political Science : 1
NEW SOLUTIONS: A Journal of Environmental and Occupational Health Policy : 1
New Structures for Physics : 1
New Theoretical Insights into Untruthfulness : 1
New York University Law Review : 1
Newspaper Research Journal : 1
NICTA : 1
NII Shonan Meet. Rep. : 1
NIST SPECIAL PUBLICATION SP : 1
Noise Mapping : 1
Norms, Logics and Information Systems: New Studies in Deontic Logic and Computer Science : 1
North Carolina Journal of Law & Technology : 1
Northwestern Law Review : 1
Northwestern Mimeo : 1
Northwestern University Libraries : 1
Notes on the Institute of Mathematical Analysis : 1
Notre Dame J. Formal Log. : 1
Novel : 1
Noûs : 1
npj: Climate and Atmospheric Science : 1
Nucleic acids research : 1
Obstetrics & Gynecology : 1
Obstetrics \& Gynecology : 1
Oceania : 1
October : 1
Omega : 1
Online Communities and Social Computing : 1
Online Readings in Psychology and Culture : 1
Open Access Journal of Addition and Psychology : 1
Open Anthropological Research : 1
Oper. Res. : 1
Operations Research : 1
Organised Sound : 1
Organization : 1
Organization Science : 1
Organization Studies : 1
Organization Theory : 1
Organizational Ethnography : 1
Our digital rights to the city : 1
Oxford Bibliographies : 1
Oxford Music Online : 1
Oxford Research Encyclopedia of African History : 1
Oxford Research Encyclopedia of Literature : 1
Paedagogica Historica : 1
Palgrave Studies in Creativity and Culture : 1
Palgrave Studies in Literary Anthropology : 1
Palgrave Studies in Relational Sociology : 1
Paper for Jon Barwise memorial volume : 1
Parallax : 1
Past & Present : 1
PEACE & CHANGE : 1
PEDIATRICS : 1
Pediatrics : 1
PeerJ Computer Science : 1
PeerJ Preprints : 1
People and Computers V : 1
Performance Paradigm : 1
Performance Research : 1
Pers. Ubiquitous Comput. : 1
Personal and Ubiquitous Computing : 1
Personality and Individual Differences : 1
Personality and Social Psychology Review : 1
Perspectives on Politics : 1
Perspectives on Psychological Science : 1
Perspectives on Sexual and Reproductive Health : 1
Perspectives on Terrorism : 1
Phenomenology and Mind : 1
Phenomenology and the Cognitive Sciences : 1
Phi Delta Kappan : 1
Philological Encounters : 1
Philosophers' Imprint : 1
Philosophical Explorations : 1
Philosophical Studies : 1
Philosophical Topics: Gendered Oppression and its Intersections : 1
Philosophical Transactions of the Royal Society B: Biological Sciences : 1
Philosophical Transactions of the Royal Society, B — Biology : 1
Philosophy     Technology : 1
Philosophy & Technology : 1
Philosophy : 1
Philosophy and Rhetoric : 1
Philosophy Compass : 1
Philosophy East and West : 1
Philosophy of Engineering and Technology : 1
Philosophy of Science : 1
Philosophy of the Social Sciences : 1
Philosophy Study : 1
Philosphy of Law Issues : 1
Physica A: Statistical Mechanics and its Applications : 1
Physical Review Letters : 1
Physics of Life Reviews : 1
Piccola Impresa / Small Business : 1
Places Journal : 1
Places to Intervene in a System : 1
Planning Perspectives : 1
PLoS Biology : 1
PLoS biology : 1
PLoS Comput. Biol. : 1
PLoS Computational Biology : 1
PLoS Genetics : 1
PLoS Global Public Health : 1
PLoS ONE : 1
Poetics : 1
Policing: An International Journal : 1
Policy & Internet : 1
Policy and Society : 1
Policy Design and Practice : 1
Policy Studies Journal : 1
Politica & Societa : 1
Political and Legal Anthropology Review : 1
Political Behavior : 1
Political Communication : 1
Political Geography : 1
Political Psychology : 1
Political Science : 1
Political Science Research and Methods : 1
Political Studies : 1
Politics & Society : 1
Politics and Policy Making in the UK : 1
Politics and Religion : 1
Politics and the Life Sciences : 1
Politics, Groups, and Identities : 1
Polity : 1
Polskie Forum Psychologiczne : 1
Prehospital and Disaster Medicine : 1
Presence Teleoperators Virtual Environ. : 1
Presence: Teleoperators and Virtual Environments : 1
Prevention Researcher : 1
Proc. ACM Hum. Comput. Interact. : 1
Proc. ACM Interact. Mob. Wearable Ubiquitous Technol. : 1
Proc. Natl. Acad. Sci. USA : 1
Proc. of the Foundations of Digital Games 2013 (Doctoral Consortium) : 1
Proc. VLDB Endow. : 1 : Proceedings of the VLDB Endowment
Procedia CIRP : 1
Procedia Computer Science : 1
Procedia Engineering : 1
Proceedings at Cognitive Science Society : 1
Proceedings of the 14th International Conference on the Foundations of Digital Games, FDG : 1
Proceedings of the 2021 CHI Conference on Human Factors in Computing Systems : 1
Proceedings of the 5th ACM international workshop on Data Warehousing and OLAP : 1
Proceedings of the ACM on Human-Computer Interaction : 1
Proceedings of the ACM on Programming Languages : 1
Proceedings of the ACM on Programming Languages, POPL : 1
Proceedings of the ACM twelfth international workshop on Data warehousing and OLAP : 1
Proceedings of the American Mathematical Society : 1
Proceedings of the Association for Information Science and Technology : 1
Proceedings of the Human Factors and Ergonomics Society Annual Meeting : 1
Proceedings of the IEEE : 1
Proceedings of the IRE : 1
Proceedings of the National Academy of Sciences : 1
Proceedings of the National Academy of Sciences of the United States of America : 1
Proceedings of the Royal Society of London, Philosophical Transactions of the Royal Society : 1
Proceedings of the Royal Society of Medicine : 1
Proceedings of the VLDB Endowment : 1
Programming Languages and Systems : 1
Progress in Astronautics and Aeronautics : 1
Progress in Computer Science and Applied Logic : 1
Progress in Drug Research : 1
Progress in Oceanography : 1
Progress in Quantum Electronics : 1
Project Horseshoe : 1
Projections : 1
Protein Science : 1
Przegla̧d Kulturoznawczy : 1
PS: Political Science & Politics : 1
Psicologia: Reflexão e Crítica : 1
Psychiatric Services : 1
Psychiatry and Clinical Psychopharmacology : 1
Psychiatry Research: Neuroimaging : 1
PsychNology J. : 1
Psychoanalytische Perspectieven : 1
Psychological Bulletin : 1
Psychological Inquiry : 1
Psychological Medicine : 1
Psychological Review : 1
Psychological Science : 1
Psychological Science in the Public Interest : 1
Psychology and Psychotherapy: Theory, Research and Practice : 1
Psychology in the Schools : 1
Psychology of Language and Communication : 1
Psychology of Music : 1
Psychology Today : 1
Psychonomic Bulletin & Review : 1
Psychopathology : 1
Psychosomatic Medicine : 1
Public Administration : 1
Public Administration Review : 1
Public administration review : 1 : Public Administration Review
Public Choice : 1
Public Culture : 1
Public culture : 1 : Public Culture
Public Integrity : 1
Public Opinion : 1
Public Opinion Quarterly : 1
Punishment & Society : 1
Qualitative and Multi-Method Research : 1
Qualitative Inquiry : 1
Qualitative Research : 1
Qualitative Sociology : 1
Quality and Quantity : 1
Quality Assurance in Education : 1
Quarterly Journal of Experimental Psychology Section A: Human Experimental Psychology : 1
Quarterly Journal of Speech : 1
Quaternary Science Reviews : 1
Queue : 1
Race Ethnicity and Education : 1
Ratio : 1
Ratio Juris : 1
Rationality and Society : 1
RCC Perspectives : 1
Reading Research Quarterly : 1
Readings in Distributed Artificial Intelligence : 1
Readings in Human-Computer Interaction : 1
Reasoning and Cognition : 1
Recoletos Multidisciplinary Research Journal : 1
Regional Studies : 1
Reinforcement Learning : 1
Relational Data Mining : 1
Religion and Society : 1
Religion, Brain     Behavior : 1
Remarks at the Reserve Bank's Topical Talks Event for Educators : 1
Reproductive Health : 1
Reproductive Health Matters : 1
Res Publica : 1
Research and Advanced Technology for Digital Libraries : 1
Research in Autism Spectrum Disorders : 1
Research in Engineering Design : 1
Research in Nursing & Health : 1
Research in Personnel and Human Resources Management : 1
Research in Phenomenology : 1
Research in Political Economy : 1
Research in the Sociology of Organizations : 1
Research in the Sociology of Work : 1
Research Journal of Economics, Business AND ICT : 1
Research on Language and Computation : 1
Research Policy : 1
Researchgate.Net : 1
Resources, Conservation and Recycling : 1
Responsibility and Judgment : 1
Resuscitation : 1
Reti, saperi, linguaggi : 1
Rev. d'Intelligence Artif. : 1
Review Journal of Autism and Developmental Disorders : 1
Review Literature And Arts Of The Americas : 1
Review of African Political Economy : 1
Review of Communication : 1
Review of Economic Studies : 1
Review of Economics and Statistics : 1
Review of General Psychology : 1
Review of Philosophy and Psychology : 1
Review of Radical Political Economics : 1
Reviews in American History : 1
Reviews in Mineralogy and Geochemistry : 1
Reviews in Obstetrics & Gynecology : 1
Reviews of Modern Physics : 1
ReVision : 1
Revista de Economía Institucional : 1
Rhetoric Review : 1
Rights, Regulation, and the Technological Revolution : 1
RITA : 1
Robotics : 1
Robotics and Autonomous Systems : 1
Robotics Auton. Syst. : 1
Roeper Review : 1
Role Playing : 1
Royal Society Open Science : 1
RSF: The Russell Sage Foundation Journal of the Social Sciences : 1
Rule Technologies. Research, Tools, and Applications : 1
Sage Research Methods Cases Part 2 : 1
Saratoga Springs : 1
Scalable Comput. Pract. Exp. : 1
Scalable Computing: Practice and Experience : 1
Scandinavian Journal of Child and Adolescent Psychiatry and Psychology : 1
Scandinavian Journal of Disability Research : 1
Scandinavian Journal of Management : 1
Scandinavian journal of psychology : 1
Schloss Dagstuhl - Leibniz-Zentrum für Informatik : 1
Sci. Comput. Program. : 1
Science : 1
Science Advances : 1
Science and Engineering Ethics : 1
Science And Technology : 1 : Science and Technology 
Science as Culture : 1
Science Communication : 1
Science Fiction Film and Television : 1
Science Fiction Studies : 1
Science in Context : 1
Science Of Computer Programming : 1 : Science of Computer Programming 
Science of Computer Programming : 1
Science, Technology, & Human Values : 1
Scientific American : 1
Scientific Annals of Computer Science : 1
Scientific Reports : 1
Scientometrics : 1
SCRIPT-ed : 1
Security Dialogue : 1
Security Studies : 1
Seeds : 1
Senses & Society : 1
Sensors : 1
Settler Colonial Studies : 1
Sexual Abuse : 1
Sexualities : 1
SIAM Journal on Computing : 1
SIAM Review : 1
SIGART Bull. : 1
SIGART Newsl. : 1
SIGCHI Bulletin : 1
SIGCSE Bulletin : 1
SIGKDD Explor. : 1
SIGMOD Rec. : 1
SIGMOD Rec. : 1 : ACM SIGMOD Record
Signs: Journal of Women in Culture and Society : 1
Simul. : 1
Simul. Model. Pract. Theory : 1
Simulating organizations : 1
Simulation & Gaming : 1
SIMULATION : 1
Simulation : 1
Simulation Modelling Practice and Theory : 1
Sixth Working Conference on Reverse Engineering (Cat. No.PR00303) : 1
Slavic Review : 1
Small Group Research : 1
Soc. Choice Welf. : 1
Soc. Netw. Anal. Min. : 1
Social Choice and Welfare : 1
Social Forces : 1
Social Media + Society : 1
Social Movement Studies : 1
Social Networks : 1
Social Problems : 1
Social psychological and personality science : 1
Social Psychology : 1
Social Psychology Matters : 1
Social Psychology Quarterly : 1
Social Research : 1
Social Research: An International Quarterly : 1
Social Science & Medicine : 1
Social Science Quarterly : 1
Social Semiotics : 1
Social Service Review : 1
Social Studies of Science : 1
Social Thought and Research : 1
Social.Path.Sintelnet.Eu : 1
Sociation : 1
Societies : 1
Society & Animals : 1
Society : 1
Society and Culture in South Asia : 1
Socio-Economic Review : 1
Sociologica : 1
Sociological Analysis : 1
Sociological Methods & Research : 1
Sociological Perspectives : 1
Sociological quarterly : 1
Sociological Science : 1
Sociological Theory : 1
Sociology Compass : 1
Sociology of Health & Illness : 1
Sociology of health & illness : 1 : Sociology of Health & Illness
Sociology of Race and Ethnicity : 1
Sociometry : 1
Sociopedia. isa : 1
Softw. Test. Verification Reliab. : 1
Software & Systems Modeling : 1
Software and Systems Modeling : 1
Software Engineering for Self-Adaptive Systems : 1
Software Quality Journal : 1
Software: Practice and Experience : 1
SoftwareX : 1
Solutions : 1
Souls : 1
Sound on Sound : 1
South Atlantic Quarterly : 1
Southwest Philosophy Review : 1
Space and Culture : 1
Special Report, Bureau of Justice Statistics : 1
Sports Medicine : 1
Springer Proceedings in Complexity : 1
Springer Series in Statistics : 1
Springer Texts in Social Sciences : 1
SSRN Electronic Journal : 1
Stat : 1
Statistical Science : 1
Statistics in Medicine : 1
Strategic Management Journal : 1
Strategic Organization : 1
Structure : 1
Stud Logica : 1 : Studia Logica
Studia Logica : 1
Studies in Computational Intelligence : 1
Studies in Conflict & Terrorism : 1
Studies in Economic Ethics and Philosophy : 1
Studies in History : 1
Studies in History and Philosophy of Science Part A : 1
Studies in Language Companion Series : 1
Studies in Popular Culture : 1
Studies in the Novel : 1
Surface Science : 1
Sustainability Science : 1
Swarm and Evolutionary Computation : 1
Swarm Evol. Comput. : 1
Symbolic Interaction : 1
Synth. : 1
Synthese : 1
Synthesis Lectures on Computer Science : 1
Synthesis Lectures on Human-Centered Informatics : 1
Systema: Connecting Matter, Life, Culture and Technology : 1
Systems Engineering : 1
Systems Modeling : 1
Tax Notes : 1
Tax Notes Federal : 1
Teacher Education Quarterly : 1
Teachers College Record: The Voice of Scholarship in Education : 1
Teaching Sociology : 1
Teaching Theology & Religion : 1
Team cognition: Understanding the factors that drive process and performance : 1
Teatervitenskapelige studier : 1
Technical Communication Quarterly : 1
Technical Reports (CIS) : 1
Technical Services Quarterly : 1
Technische Universität Dortmund : 1
Techno:Phil - Aktuelle Herausforderungen der Technikphilosophie : 1
Technological and Economic Development of Economy : 1
Technology : 1
Technology and Culture : 1
Technology and the Future : 1
Technology in Society : 1
Technology, Instruction, Cognition & Learning (TICL) : 1
Telematics Informatics : 1
Television & New Media : 1
Terrorism and Political Violence : 1
TESOL Quarterly : 1
The Academy of Management Review : 1
The AISB Quarterly : 1
The American Archivist : 1
The American Economic Review : 1
The American Economist : 1
The American Historical Review : 1
The American Journal of Human Genetics : 1
The American Journal of Psychiatry : 1
The American Naturalist : 1
The American political science review : 1
The American Statistician : 1
The Annals of Applied Statistics : 1
The Annals of Thoracic Surgery : 1
The Anthropology of the State: A Reader : 1
The Arab Studies Journal : 1
The Art, Science, and Engineering of Programming : 1
The Asia-Pacific Education Researcher : 1
The Atlantic Monthly : 1
The Banking Law Journal : 1
The British Interplanetary Society : 1
The British Journal for the History of Science : 1
The British Journal for the Philosophy of Science : 1
The British Journal of Criminology : 1
The British Journal of Politics and International Relations : 1
The British Journal of Psychiatry : 1
The British journal of social psychology / the British Psychological Society : 1
The British Journal of Sociology : 1
The Bulletin of Mathematical Biophysics : 1
The Cambridge companion to critical theory : 1
The Chronicle of Higher Education : 1
The Computer After Me: Awareness And Self-Awareness In Autonomic Systems : 1
The Computer Journal : 1
The CRC Press International Series on Computational Intelligence : 1
The Distributors, South Bend, Ind : 1
The European Journal of Development Research : 1
The European Physical Journal Special Topics : 1
The Florida Sun-Sentinel : 1
The Gerontologist : 1
The Green Bag : 1
The Heritage Foundation : 1
The Information Science Discussion Paper Series : 1
The Information Society : 1
The International Journal of Health Planning and Management : 1
The International Journal of Humanoid Robotics : 1
The International Journal of Information, Diversity, & Inclusion (IJIDI) : 1
The Jerusalem Philosophical Quarterly : 1
The Journal of Academic Librarianship : 1
The Journal of American Folklore : 1
The Journal of Development Studies : 1
The Journal of Economic History : 1
The Journal of Finance : 1
The Journal of Higher Education : 1
The Journal of Legal Studies : 1
The Journal of Logic and Algebraic Programming : 1
The Journal of Logic Programming : 1
The Journal of Mathematical Sociology : 1
The Journal of Negro Education : 1
The Journal of Neuroscience : 1
The Journal of Neuroscience Nursing : 1
The Journal of Philosophy : 1
The Journal of Political Economy : 1
The Journal of Politics : 1
The Journal of Race, Ethnicity, and Politics : 1
The Journal of Sex Research : 1
The Journal of Sexual Medicine : 1
The Journal of Symbolic Logic : 1
The Journal of the Centre for Freudian Analysis and Research. : 1
The Journal of the Midwest Modern Language Association : 1
The Journal of Urology : 1
The Knowledge Engineering Review : 1
The Lancet : 1
The Lancet Global Health : 1
The Lancet Public Health : 1
The Lancet Regional Health - Europe : 1
The Lancet Respiratory Medicine : 1
The Library Quarterly : 1
The Mathematical Gazette : 1
The Milbank Quarterly : 1
The Monad.Reader : 1
The Nordic Journal of Aesthetics : 1
The Open Virtual Reality Journal : 1
The Oxford Handbook of Philosophy of Technology : 1
The Philosophers' Magazine : 1
The Psychologist : 1
The Psychology of Habit : 1
The Psychology of Love : 1
The Quarterly Journal of Economics : 1
The Quarterly Journal of Experimental Psychology : 1
The Review of Economic Studies : 1
The Review of Symbolic Logic : 1
The Routledge Companion to Qualitative Research in Organization Studies : 1
The Sage Handbook of Organizational Institutionalism : 1
The Sociological Quarterly : 1
The Sociological Review : 1
The Structuring of Work in Organizations : 1
The U.S Army War College Quarterly: Parameters : 1
The University of Chicago Law Review : 1
The Velvet Light Trap : 1
The VLDB Journal : 1
The World Bank Research Observer : 1
The Yale Law Journal : 1
Theater : 1
Theor. Comput. Sci. : 1
Theoretical and Applied Climatology : 1
Theoretical and Computational Chemistry : 1
Theoretical Computer Science : 1
Theoretical computer science : 1 : Theoretical Computer Science
Theoretical Foundations of Artificial General Intelligence : 1
Theoria : 1
Theory & Psychology : 1
Theory and Applications of Ontology: Computer Applications : 1
Theory and Practice : 1
Theory and Practice of Logic Programming : 1
Theory and Practice of Logic Programming : 1
Theory and Practice of Object Systems : 1
Theory and Society : 1
Theory Into Practice : 1
Theory Pract. Log. Program. : 1 : Theory and Practice of Logic Programming
Theory, Culture & Society : 1
Therapy Today : 1
Third Text : 1
Third World Quarterly : 1
Third World Thematics: A TWQ Journal : 1
Tidskrift Journal of Research in Teacher Education : 1
Time : 1
Top. Cogn. Sci. : 1
Topics in Information Systems : 1
Topoi : 1
Topology : 1
Touchepas : 1
Town Planning Review : 1
Trans. Assoc. Comput. Linguistics : 1
Trans. Comput. Collect. Intell. : 1
Trans. Data Priv. : 1
Trans. Edutainment : 1
Trans. Large Scale Data Knowl. Centered Syst. : 1
Trans. SDPS : 1
Transactional Analysis Journal : 1
Transactions of the American Mathematical Society : 1
Transactions of the Association for Computational Linguistics : 1
Transactions of the Digital Games Research Association : 1
Transactions of the Institute of British Geographers : 1
Transformations: The Journal of Inclusive Scholarship and Pedagogy : 1
Transforming Anthropology : 1
Translational Behavioral Medicine : 1
Transnational Environmental Law : 1
Transportation research record : 1
Trauma, Violence, and Abuse : 1
Traumatology : 1
Trends and Applications of Serious Gaming and Social Media : 1
Trends in Cognitive Sciences : 1
Trends in Ecology & Evolution : 1
Trends in Functional Programming : 1
tripleC: Communication, Capitalism & Critique. : 1
Trolltech, Nokia : 1
Trust and deception in virtual societies : 1
Twenty-first Century Perspectives on War, Peace, and Human Conflict : 1
UCLA Law Review : 1
Under consideration for publication in the Journal on Software and Systems Modeling : 1
Understanding Complex Systems : 1
Universal Access in the Information Society : 1
Universal Logic: An Anthology : 1
University of Memphis Law Review : 1
University of Michigan : 1
University Politehnica of Bucharest Scientific Bulletin Series C-Electrical Engineering and Computer Science : 1
Urban Education : 1
Urban Forum : 1
Urban Geography : 1
US Government : 1
User Model. User Adapt. Interact. : 1
Utopian Studies : 1
Vanderbilt Law Review : 1
Virtual Real. : 1
Virtual Reality : 1
VIS 05. IEEE Visualization, 2005. : 1
Visual Anthropology Review : 1
VLDB J. : 1 : The VLDB Journal
Wall Street Journal : 1
Wash. L. Rev. : 1 : Washington University Law Review
Washington University Law Review : 1
Water : 1
Water Resources Management : 1
Waterlines : 1
Web Intell. Agent Syst. : 1 : Web Intelligence and Agent Systems: An International Journal 
Web Intelligence and Agent Systems: An International Journal : 1
Western Development Museum/Saskatchewan Indian Cultural Centre Partnership Project : 1
Wiley Interdisciplinary Reviews: Computational Statistics : 1
WIREs Cognitive Science : 1
Women: A Journal of Liberation : 1
Work : 1
Working It Out : 1
World Development : 1
World Future Review : 1
World Health Forum : 1
World Policy Journal : 1
World Wide Web : 1
Written Communication : 1
XRDS : 1
XRDS: Crossroads, The ACM Magazine for Students : 1
Yale French Studies : 1
Yale Journal Of Law and Liberation : 1
Yale Journal of Law and Technology : 1
Yale Journal on Regulation : 1
Yearbook of Medical Informatics : 1
Youth and Policy : 1
Zeitschrift fur Soziologie : 1
Zine Bakery Bakeshop : 1
Zurich: Swiss National Bank : 1
